### ISSUE TITLE
binary-search: what is expected answer for an array with duplicates ?

### ISSUE THREAD

**Issue by ferhatelmas** [exercism/problem-specifications#1003]
* first index
* last index
* any one of them
* delegate to language for an idiomatic solution

**Comment by Insti** [comment]
A bit more context would be helpful here:
Link to description, link to canonical-data.json, Example test data showing the problem you are trying to solve.

**Comment by Insti** [comment]
e) Don't test for it.

**Comment by NobbZ** [comment]
Binary search is meant to return on the first time it finds something.

So given `search([1,1,1,1], 1)` it shall of course return 1.

We are searching in 0..3, 3 div 2 is 1, we check index 1, we find the searched element, so we return the current index.

Anything else would be against the spirit of the algorithm.

**Comment by coriolinus** [comment]
> So given search([1,1,1,1], 1) it shall of course return 1.

Or 0, in languages which count from 0.

**Comment by NobbZ** [comment]
I did count from zero, please re-read my explanation

**Comment by ErikSchierboom** [comment]
@ferhatelmas Has your question successfully been answered?

**Comment by ferhatelmas** [comment]
Yes, it's answered. Thanks all who contributed. 

@Insti I will try to be more clear with context next time :wink:
