### ISSUE TITLE
documentation: Update README.md to reflect the "input key as an object" policy.

### ISSUE THREAD

**Issue by Insti** [exercism/problem-specifications#1007]
In https://github.com/exercism/problem-specifications/issues/996 it was decided that the canonical data should have an explicit input key whose value is an object containing the input(s) to the code under test.

For example:

```json
{
  "description": "year not divisible by 4: common year",
  "property": "leapYear",
  "input": {
    "year": 2015
  },
  "expected": false
}
```

**Task**

Update the example canonical-data.json in the [Readme.md](https://github.com/exercism/problem-specifications/blob/master/README.md) to reflect the "input key as an object" policy.

**Questions**
Is this documented anywhere else?
Should there also be json-schema changes?

**Comment by Insti** [comment]
> Should there also be json-schema changes?

Not at this stage, the input key should already be valid according to the current schema and we probably do not want to strictly enforce the policy until the existing exercises are converted to the new format.

**Comment by rpottsoh** [comment]
I'll work on this.

**Comment by Insti** [comment]
Thanks @rpottsoh :heart:
