### ISSUE TITLE
documentation: README.md conventions corrections.

### ISSUE THREAD

**Issue by Insti** [exercism/problem-specifications#1010]
The [README.md test data format section](https://github.com/exercism/problem-specifications/blob/master/README.md#test-data-format-canonical-datajson) has some  issues that need fixing.

**Task**

Update the "There are also some convention about expected that you must follow:" section of [README.md](https://github.com/exercism/problem-specifications/blob/master/README.md#test-data-format-canonical-datajson)

Suggested changes:

>
> There are also some convention**s** ~~about expected~~ that you must follow:

>    All keys should follow the lowerCamelCase convention.
    **I**f the input is valid but there is no result for the input, the value at "expected" should be null.
    **I**f an error is expected (because the input is invalid, or any other reason), the value at "expected" should be an object containing exactly one property, "error", whose value is a string.
        The string should explain why the error would occur.
        A particular track's implementation of the exercise need not necessarily check that the error includes that exact string as the cause, depending on what is idiomatic in the language (it may not be idiomatic to check strings for error messages).

There may be other changes that need making within that section, these were just the ones that caused me to create the issue. 

(The bullet points should probably stay, they just disappeared when I copy/pasted the text.)

See also: #1009

**Comment by rpottsoh** [comment]
@insti, according to the README the canonical data is considered optional (about line 33 I think).  Since the desire is for every exercise to have canonical data present should the optional call out be removed from this document?

I am working on the revisions you brought up when you opened this issue.

**Comment by Insti** [comment]
> should the optional call out be removed from this document?

Yes, that sounds sensible.
