### ISSUE TITLE
New exercise idea: Armstrong numbers

### ISSUE THREAD

**Issue by pheanex** [exercism/problem-specifications#1017]
https://en.wikipedia.org/wiki/Narcissistic_number
I'd like to add this as an exercise.
The idea would be to implement a test for Armstrong-Numbers
Objections? Approvals?

**Comment by coriolinus** [comment]
Could be interesting. I certainly don't object to your adding an exercise of this type! 

I'd recommend that you structure your examples in `canonical-data.json` in the following way:

```json
  {
    "description": "153 is an Armstrong number in base 10",
    "property": "armstrong",
    "input": {
      "number": 153,
      "base": 10
    },
    "expected": true
  }
```

I'd also encourage some test cases in octal and hexadecimal.

**Comment by rpottsoh** [comment]
I have completed this exercise in Ruby [here](https://www.codeeval.com/open_challenges/82/) a few years ago.  As long as there are no licensing issues then I see no reason that this couldn't be added as an exercise.  You need to follow the process for [implementing a completely new exercise](https://github.com/exercism/problem-specifications/blob/master/CONTRIBUTING.md#implementing-a-completely-new-exercise) via PR.  The README for this repo also provides some information as well.

Three files are required to be submitted via a single PR:
1.  description.md
1.  canonical-data.json
1.  metadata.yml

The documentation may refer to the canonical data as optional or bonus.  Exercism is in the process of implementing canonical data to all exercises that are lacking this information.  If you end up undertaking this project a canonical-data.json file will be expected.

There are plenty of people here to help.  I don't know if you are new or have ever undertaken adding an exercise before to Exercism.  We're happy to help and appreciate you wanting to take the time to make an improvement to this project, thanks!

**Comment by pheanex** [comment]
Thank you for the feedback and encouragement.
I'd planned to also include the canonical-test-data :-)
Brace yourself, PR incoming
