### ISSUE TITLE
rail-fence-cipher: must cover white spaces and special characters

### ISSUE THREAD

**Issue by Meenohara** [exercism/problem-specifications#1043]
(I do not use github much, but shall be active now on)

I began coding for railfence cipher as it was mentioned as an unattempted exercise for Javascript.
I have now coded for the encoding part i.e. generate a rail fence cipher.
I am yet to start decoding. 
But when I visited this github for exercism, I am finding that whitespaces are being omitted and special characters are not taken care of.
It is the same with test cases where strings are mention without any white spaces or characters. 

Can we add that the ciphers and deciphers also need to be take care of spaces and speial characters?

**Comment by Stargator** [comment]
@Meenohara It is correct the problem set does not include white spaces or special characters.

I do think special characters may be a neat addition.

And would not agree about adding white spaces since the comments in canonical-data notes:
> "The tests do not expect any normalization or cleaning.",
> "That trade is tested in enough other exercises."

**Comment by rpottsoh** [comment]
Problem specifications need to remain generic (if generic is the correct word here).  The specifications in this repo are available for all the language tracks of Exercism to draw from.  With that, the problem definitions should not contain any characters that may not be allowed in certain languages.

Some tracks are utilizing test generators, which process the canonical data and produce a test suite.  Characters that might give a track grief would only serve to create more work for the maintainers of those tracks to have to deal with the illegal characters.

I'm not saying that perhaps the test data for Railfence, as it is defined here in this repo might not be changed per your suggestion.  However, for now, it may be more prudent to raise this as an issue in the javascript track .  Each track is permitted to add new tests to their test suites if they feel they are warranted.  Sometimes these changes make their way back to this repo.

[description.md](https://github.com/exercism/problem-specifications/blob/master/exercises/rail-fence-cipher/description.md) and [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/rail-fence-cipher/canonical-data.json)

**Comment by Meenohara** [comment]
Okay I am still writing the decoding part in JS and may write for C too
Like @rpottsoh  Suggested I shall raise the issues separately if the need comes up
The mentioned test cases are fine with me, I just felt they could cover more
