### ISSUE TITLE
pig-latin: Description not complete

### ISSUE THREAD

**Issue by marcuslxxii** [exercism/problem-specifications#1049]
The problem's description of Pig Latin does not mention cases where "y" (which is a vowel) has a consonant sound, nor does the case where words start with "x" (consonant), but it does have a vowel sound. Yet there are 2 tests, one with "yellow" and one with "xray", so why not mention these cases?

**Comment by rpottsoh** [comment]
[description.md](https://github.com/exercism/problem-specifications/blob/master/exercises/pig-latin/description.md)

**Comment by rpottsoh** [comment]
I don't know why those cases are not mentioned.  `Y` is both a vowel and a consonant, depending on its usage in a word.  If you have a suggestion for changing either of the two rules, or for a third rule, I welcome you to submit a PR.  We're always interested in input from others.

**Comment by rpottsoh** [comment]
Perhaps a third rule isn't needed here as either rule applies depending on where `Y` is in the word.  Perhaps a short blurb to warn the reader to not dismiss the tricky letter `Y` while considering their solutions?.....

**Comment by rpottsoh** [comment]
I think this issue has been handled via #1171.
