### ISSUE TITLE
Acronym: Remove test case

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [exercism/problem-specifications#1068]
The test case with description `all caps words` and `non-acronym all caps word` seem to be testing for the same thing. Perhaps we can remove 1 of them.

Same goes for the test case with description `punctuation` and `hyphenated`.

**Comment by rpottsoh** [comment]
[canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/acronym/canonical-data.json)
[description](https://github.com/exercism/problem-specifications/blob/master/exercises/acronym/description.md)

**Comment by rpottsoh** [comment]
**all caps words:**
```JSON
        {
          "description": "all caps words",
          "property": "abbreviate",
          "input": {
            "phrase": "PHP: Hypertext Preprocessor"
          },
          "expected": "PHP"
        },
```
**non-acronym all caps word:**
```JSON
        {
          "description": "non-acronym all caps word",
          "property": "abbreviate",
          "input": {
            "phrase": "GNU Image Manipulation Program"
          },
          "expected": "GIMP"
        }
```
---
**punctuation:**
```JSON
        {
          "description": "punctuation",
          "property": "abbreviate",
          "input": {
            "phrase": "First In, First Out"
          },
          "expected": "FIFO"
        }
```
**hyphenated:**
```JSON
        {
          "description": "hyphenated",
          "property": "abbreviate",
          "input": {
            "phrase": "Complementary metal-oxide semiconductor"
          },
          "expected": "CMOS"
        }
```

**Comment by rpottsoh** [comment]
@Zhiyuan-Amos why do you think `all caps words` and `non-acronym all caps word` appear to be testing for the same thing?  Their expectations are different.  The subtle difference is knowing when to return just the acronym that appears in `"phrase"` or just treat the acronym in `"phrase"` as just another word and only return its first letter.

**Comment by rpottsoh** [comment]
@Zhiyuan-Amos regarding `punctuation` and `hyphenated` maybe there is something to this.  I do not have first hand experience with this exercise so I don't fully understand the relevance of punctuation followed by space vs. punctuation not followed by a space plays into ones solution.

**Comment by Zhiyuan-Amos** [comment]
@rpottsoh thank you for your comments :)

> The subtle difference is knowing when to return just the acronym that appears in "phrase" or just treat the acronym in "phrase" as just another word and only return its first letter.

Actually, I don't think that the code is able to do what you have mentioned above. Rather, the general solution is to simply return the first letter of each word.
1. For "**P**HP: **H**ypertext **P**reprocessor", return "PHP".
1. For "**G**NU **I**mage **M**anipulation **P**rogram", return "GIMP"

> punctuation followed by space vs. punctuation not followed by a space plays into ones solution.

Ah I didn't notice this! :) That way, the description should be updated to reflect what it's actually testing for. Now that you have said it, I think both test cases are necessary because if someone splits the string using only whitespace as the delimiter, then the result of "Complementary metal-oxide semiconductor" will be "CMS" which is wrong.

**Comment by petertseng** [comment]
It would be appropriate to delete PHP case and only leave GIMP.

It would not be appropriate to delete GIMP case and only leave PHP because https://github.com/exercism/problem-specifications/pull/405 (PHP, being recursive, is ambiguous)

**Comment by rpottsoh** [comment]
It seems to me that `all caps word` should be removed.

**Comment by Zhiyuan-Amos** [comment]
Alright! Shall I open a PR for this? Also, should I update the description of `punctuation` and `hyphenated` as per the [comment](https://github.com/exercism/problem-specifications/issues/1068#issuecomment-355707623) i mentioned earlier?

**Comment by rpottsoh** [comment]
A PR to deal with `all caps word`?  Sure.  What kind of change do you propose for `punctuation` and `hyphenated`?

**Comment by Zhiyuan-Amos** [comment]
How about `punctuation followed by space` and `punctuation not followed by space`?

**Comment by rpottsoh** [comment]
I'm thinking `punctuation` should be left as is.  `hyphenated` should be worded to indicate that the hyphen is like a space.  The parts on either side of the hyphen are each treated like individual words.
