### ISSUE TITLE
javascript Simple-cipher problem. Explanation is unclear

### ISSUE THREAD

**Issue by norricorp** [exercism/problem-specifications#1091]
Step 1 makes sense; increase each letter by 3 
Step 2 makes less sense.  For each character in the key, increment corresponding letter in message where a (in key) = 0, b=1, c=2, d=3 etc?? Is that correct. Does that not mean that each key has to be at least the length of the message? Is that practical?

**Comment by coriolinus** [comment]
[link to description](https://github.com/exercism/problem-specifications/blob/master/exercises/simple-cipher/description.md)

**Comment by coriolinus** [comment]
To answer you @norricorp, yes, you've correctly understood step 2's mechanism, and it does mean that each key needs to be at least the length of the message to handle things without repetition. 

If you approach this problem by distributing a series of very long keys to all senders and recipients and requiring that they destroy the key after it's been used once, then you have [one-time pads](https://en.wikipedia.org/wiki/One-time_pad). However, the more conventional approach is to just repeat the key as many times as necessary to fit the length of the message. For example, to encrypt the message `thiscontainsthirtyonecharacters` with the key `key`, you'd effectively use the generated key `keykeykeykeykeykeykeykeykeykeyk`.

Make sense?

**Comment by coriolinus** [comment]
Also, to answer the question of practicality, the simple answer is no: the shorter your key, the more vulnerable your cyphertext becomes to cryptanalysis, and whenever practicable you'd really prefer your key length to exceed your message length. However, we're not really generating secure messages here so much as going over basic principles of cryptography.

**Comment by norricorp** [comment]
Many thanks. makes sense now
