### ISSUE TITLE
Transpose  "first line longer than second line" appears incorrect 

### ISSUE THREAD

**Issue by martinfreedman** [exercism/problem-specifications#1092]
`"first line longer than second line"` appears incorrect - the last row should read `". "` not `"."` (compare to the last line of `"second line longer than first line"`)

Has anyone used this generator in their track and can confirm or deny this issue?

**Comment by petertseng** [comment]
I would say `"."` because https://github.com/exercism/problem-specifications/blob/master/exercises/transpose/description.md

> If the input has rows of different lengths, this is to be solved as follows:
> 
> * Pad to the left with spaces.
> * Don't pad to the right.

**Comment by martinfreedman** [comment]
Aha! Thanks
