### ISSUE TITLE
complex-numbers: description for exponential function is unclear

### ISSUE THREAD

**Issue by wolf99** [exercism/problem-specifications#1094]
The `description.md` of the complex-numbers exercise is rather unclear on exactly what mathematical operation is meant to implemented by the algorithm mentioned as "exponent of a complex number". The full text of that item reading:

>Exponent of a complex number can be expressed as exp(a + i * b) = exp(a) * exp(i * b), and the last term is given by Euler's formula exp(i * b) = cos(b) + i * sin(b).

Is this supposed to be `ln(complex-number)` or `e^(complex-number)` or even something else?

The C track has recently seen an [issue](https://github.com/exercism/c/issues/256) for this exact question, where I (a maintainer) had no real idea from reading the description, how to answer the OP without more mathematical knowledge than would strictly be required for a programming exercise.

Luckily in this case for the C track, the exercise was implemented very recently and the implementer was still around and able to help out, other cases might not be so lucky.

Essentially the `description.md` could do with rewriting in a somewhat less terse manner.

**Comment by cmccandless** [comment]
[description.md](https://github.com/exercism/problem-specifications/blob/8380763e95a013a795787e6efbba76e982675e95/exercises/complex-numbers/description.md)

**Comment by clementi** [comment]
I'm the recent implementer of this exercise. I might rewrite the description thus, using the word "exponentiation":

> Exponentiation of _e_ to a complex number can be expressed as e^(a + i * b) = e^a * e^(i * b), and the last term is given by Euler's formula e^(i * b) = cos(b) + i * sin(b).

**Comment by wolf99** [comment]
Another possible alternative:

>Raising _e_ to a complex exponent can be expressed as e^(a + i * b) = e^a * e^(i * b), where the last term is given by Euler's formula e^(i * b) = cos(b) + i * sin(b).

**Comment by wolf99** [comment]
This may be a good candidate for good-first-patch labeling as it's basically a markdown rewording change.
