### ISSUE TITLE
ISBN verifier: missing edge cases 

### ISSUE THREAD

**Issue by kytrinyx** [exercism/problem-specifications#1096]
Reported by @uranusjr in https://github.com/exercism/exercism.io/issues/3711.

The original report mentions Rust specifically, but I believe that this is likely a problem with the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/canonical-data.json).

(Note: for ease of reference I copied the code example into the issue)

-----

They do not ensure implementations check for ISBN length. No tests for strings that’s too short (< 10 digits), and although there are tests for > 10 digits, their checksum results are not 0 to begin with so implementations can get away just adding everything up. [Here’s an example.](http://exercism.io/submissions/ffdb9198456c4873b97faa0a5d5392cf)

-----

```rust
/// Determines whether the supplied string is a valid ISBN number
pub fn is_valid_isbn(isbn: &str) -> bool {
    let mut check = 0;
    for (i, c) in isbn.chars().rev().filter(|&c| c != '-').enumerate() {
        check += (i as u32 + 1) * match c {
            'X' if i == 0 => 10,
            c @ '0'...'9' => c.to_digit(10).unwrap(),
            _ => { return false; },
        }
    }
    check % 11 == 0
}
```

**Comment by rpottsoh** [comment]
I am not opposed to there being a test for ISBN codes that are less than 10 characters, but first I want to confirm that "empty isbn" doesn't already cover this case.

**Comment by uranusjr** [comment]
The empty ISBN would cover the case, but the Rust implementation does not contain it 😮

**Comment by kytrinyx** [comment]
> the Rust implementation does not contain it

Ah, in that case, would you be willing to submit a fix to the Rust exercise? https://github.com/exercism/rust/tree/master/exercises/isbn-verifier

/cc @exercism/rust

**Comment by rpottsoh** [comment]
"empty isbn" was only added 15 days ago, #1055.

**Comment by rpottsoh** [comment]
Should this issue be moved to Rust?

**Comment by kytrinyx** [comment]
It should definitely be closed here. If someone wants to open a PR or issue in the Rust repository, I'll leave that up to them.
