### ISSUE TITLE
roman-numerals: Suggest test case addition

### ISSUE THREAD

**Issue by Zarimax** [exercism/problem-specifications#1138]
I suggest adding a test case where more than one normalization has to occur on a given number.

For example, 49 would have two normalizations. Starting with "XXXXVIIII", "XXXX" should be "XL" and "VIIII" should be "IX", resulting in a final string of "XLIX".

This will catch solutions that do after-the-fact normalizations but only do one pass.

I can submit a pull request if nobody objects.

https://github.com/exercism/problem-specifications/blob/master/exercises/roman-numerals/canonical-data.json

**Comment by rpottsoh** [comment]
X should not be repeated more than 3 times.  It is possible to to get to XLIX in one normalization.
See https://www.math.nmsu.edu/~pmorandi/math111f01/RomanNumerals.html

**Comment by Zarimax** [comment]
Both of those points are true. "XXXXVIIII" is an invalid string, but someone could get it as an intermediate step by applying a naive algorithm and then using pattern-matching to normalize. For example:
```
while (x / 10 > 0)
{
   add 'X' to result string
   x = x - 10
}
while (x / 5 > 0)
{
    add 'V' to result string
    x = x - 5
}
while (x / 1 > 0)
{
    add 'I' to result string
    x = x - 1
}
```

For an input value of 48, this algorithm yields "XXXXVIII".  If the solution is only looking for a single point to normalize, it will find "XXXX", replace it with "XL", and return "XLVIII". That is the correct result for 48.

For an input value of 49, this algorithm yields "XXXXVIIII". If the solution is only looking for a single point to normalize, it will find "XXXX", replace it with "XL", and return "XLVIIII". That is the wrong result. That approach misses "VIIII", which needs to become "IX".

But because all of the test cases in this solution only have a single substring to normalize, such an error in an algorithm would not be detected.

**Comment by coriolinus** [comment]
This sounds like a useful case to test, to me.

**Comment by rpottsoh** [comment]
I think you have a valid point.  It might also be worthwhile to improve the README to give more detailed instruction on the correct method for converting Arabic to Roman numerals.  Testing 49 would then catch those instances where the conversion rule wasn't followed correctly.

I just want to add that I added a test for 49 to my solution and it passed without needing to change my solution.
