### ISSUE TITLE
bracket-push: description is ambiguous 

### ISSUE THREAD

**Issue by tleen** [exercism/problem-specifications#1178]
[A reasonable question](https://github.com/exercism/go/issues/1072) popped up on the Go track. 

Our API for the problem contains a true/false bool if they match and an error value. Looking at the [problem description](https://github.com/exercism/problem-specifications/blob/master/exercises/bracket-push/description.md): 

> Given a string containing brackets [], braces {} and parentheses (), verify that all the pairs are matched and nested correctly.

I could see the **Given a string** being interpreted in two ways. 

- The string *will* have brackets [], braces {} and(/or?) parentheses ()
- The string *may* have brackets [], braces {} and(/or?) parentheses ()

If it is the former an error condition is an indicator of an incorrect string, if the latter an error condition in probably unnecessary.

[The test cases for the problem](https://github.com/exercism/problem-specifications/blob/master/exercises/bracket-push/canonical-data.json#L14-L19) suggest the latter. If it is the latter perhaps we should tighten up the description a bit? If it is the former we should adjust the test cases.

Thoughts?

**Comment by coriolinus** [comment]
So, you'd prefer a sentence reading as follows: "Given a string which may
contain brackets [], braces {}, parentheses (), or any combination of
these, verify that all the pairs are matched and nested correctly."

Works for me. Create a PR?
