### ISSUE TITLE
book-store: missing test case?

### ISSUE THREAD

**Issue by tierchen** [exercism/problem-specifications#1215]
Hi.
I was working on the book-store problem (python track) and realised that there are a few cases that were not covered in [canonical-data](https://github.com/exercism/problem-specifications/blob/master/exercises/book-store/canonical-data.json)
What if the set of books wasnt't reassigned and sorted by occurrence and looks like [1, 2, 3, 3, 4, 4, 5, 5]? I couldn't find any restriction on this in specification.
The majority of existing solutions (at least on python track) and even [example.py](https://github.com/exercism/python/blob/master/exercises/book-store/example.py) don't handle this case, but pass all other existing tests.

For them:
[1, 1, 2, 2, 3, 3, 4, 5] gives 5120 and that is the right answer, but
[1, 2, 3, 3, 4, 4, 5, 5] (the same case, but different naming) gives 5160, which seems to be wrong

**Comment by petertseng** [comment]
You are correct that the case you describe `[1, 2, 3, 3, 4, 4, 5, 5]` is a valid input. Since you have found implementations that do the wrong thing on that case, it seems that it'll be good to add this case.

For my curiosity, would you describe how it came to be that the solutions handle `[1, 1, 2, 2, 3, 3, 4, 5]` but do not handle `[1, 2, 3, 3, 4, 4, 5, 5]` ?

**Comment by rpottsoh** [comment]
> For my curiosity

Mine too.  I was curious and tried both forms of the input with my solution, 5120 was returned both times.

**Comment by tierchen** [comment]
> would you describe how it came

The main problem of incomplete implementations is wrong process of group choosing.
Let's take a look on [example.py](https://github.com/exercism/python/blob/master/exercises/book-store/example.py) based on recursion, using the case of `[1, 2, 3, 3, 4, 4, 5, 5]`.

`groups = list(set(books))` gives us `[1, 2, 3, 4, 5]`

Snippet responsible for a recursion tree building looks like

```
for i in range(len(groups)):
	remaining_books = books[:]
	for v in groups[:i + 1]:		# !!! just list accumulation
	    	remaining_books.remove(v)	# !!!
price = calculate_total(remaining_books, price_so_far + _group_price(i + 1))
min_price = min(min_price, price)
```

Thus, 1st level of the recursion tree consists of `[1]`, `[1, 2]`, `[1, 2, 3]`, `[1, 2, 3, 4]`, `[1, 2, 3, 4, 5]` which means that any possible solution should include at least one of these sets.

Hovewer, there is one and only one right partition for the present example -- `[1, 3, 4, 5]` and `[2, 3, 4, 5]`

@rpottsoh On python track only 2 out of recent 10 implementations nonetheless give right answer on that case.
