### ISSUE TITLE
isbn-verifier: lacks a test case for 0 < length < 10

### ISSUE THREAD

**Issue by petertseng** [exercism/problem-specifications#1216]
https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/canonical-data.json has a case for 0 length, but no case for a nonzero length that is less than 10.

Without such a case, incorrect implementations such as those in https://github.com/petertseng/exercism-problem-specifications/blob/verify/exercises/isbn-verifier/verify.rb#L59-L74 will pass the tests, even though they should not.

Task:

* Craft an input(s) with 9 digits that those incorrect implementations would incorrectly declare to be a valid ISBN. This may be one input that covers both implementations, or one for each.
* Add those input(s) to the JSON file.
* Increase second version component of the JSON file. If current version is `x . y . z`, make the new version `x . y+1 . 0`
* Use a word in https://help.github.com/articles/closing-issues-using-keywords/ in your commit message to indicate that you have closed this issue.

**Comment by mikestratton** [comment]
I am working on this.
