### ISSUE TITLE
wordy: Confusing expected result for test case involving operator priorities

### ISSUE THREAD

**Issue by mRcfps** [exercism/problem-specifications#1233]
When I was implementing my solution to this exercise, I was perplexed by the expected result of this test case:

```json
{
  "description": "addition and multiplication",
  "property": "answer",
  "input": {
  "question": "What is -3 plus 7 multiplied by -2?"
  },
  "expected": -8
}
```

It seems the correct output should be `-17`, since multiplication is prioritized over addition. And here is a screenshot when I ask Google this question:

<img width="790" alt="qq20180429-210555 2x" src="https://user-images.githubusercontent.com/23410977/39406969-b4c3c798-4bf1-11e8-9be5-249d22150f91.png">

**Comment by rpottsoh** [comment]
Nice find.  Looks like a PR is warranted.  Any PR should claim that it fixes or closes this issue.

Sent from my android device.

**Comment by mRcfps** [comment]
@rpottsoh I'll handle this.

**Comment by rpottsoh** [comment]
I would like to point out that if you enter `-3 + 7 * -2` into the standard Windows calculator you will get `-8`.  If you enter the same input into the Windows scientific calculator you will get `-17`.  The standard calculator doesn't follow PEMDAS.  The Google calculator used in the example in the opening comment is a scientific calculator.  In a standard calculator PEMDAS is usually applied before inputting anything.
