### ISSUE TITLE
Exercise Idea: implement a simple REST API

### ISSUE THREAD

**Issue by cmccandless** [exercism/problem-specifications#1254]
# rest-api

## Blurb

Implement a RESTful API for tracking IOUs.

## Description

Four roommates have a habit of borrowing money from each other frequently, and have trouble remembering who owes whom, and how much.

Your task is to implement a simple [RESTful API](https://en.wikipedia.org/wiki/Representational_state_transfer) that receives [IOU](https://en.wikipedia.org/wiki/IOU)s as POST requests, and can deliver specified summary information via GET requests.

#### User object
```json
{
  "name": "Adam",
  "owes": {
    "Bob": 12.0,
    "Chuck": 4.0,
    "Dan": 9.5
  },
  "balance": "<(total owed by other users) - (total owed to other users)>"
}
```

#### Methods

| Description | HTTP Method | URL | Payload Format | Response w/o Payload | Response w/ Payload |
| --- | --- | --- | --- | --- | --- |
| List of user information | GET | /users | `{"users":["Adam","Bob"]}` | `{"users":<List of all User objects>}` | {"users":<List of User objects for <users>>} |
| Create user | POST | /add | {"user":<name of new user (unique)} | N/A | \<User object for new user\> |
| Create IOU | POST | /iou | {"lender:<name of lender>,"borrower":<name of borrower>,"amount":5.25} | N/A | {"users":<updated User objects for <lender> and <borrower>} |

### Other Resources:
- https://restfulapi.net/
- Example RESTful APIs
  - [GitHub](https://developer.github.com/v3/)
  - [Reddit](https://www.reddit.com/dev/api/)

**Comment by rpottsoh** [comment]
Interesting idea.  
> "balance": "<(total owed by other users) - (total owed to other users)>"

Seems like `"balance"` is trying to do too much.  Determining the total owed to other users is straightforward enough.  Seems like there needs to be a mechanism in place to maintain the tally owed by other users.

Any thoughts on how the testdata might appear for an exercise like this?  Do you envision the test suite to essentially be a REST client to the students server?

**Comment by cmccandless** [comment]
I thought it would be easiest to uncouple the API handling code from any sort of server. Instead, I would suggest treating this similarly to a text-parsing exercise, where the input might be as follows:

`"POST /iou\n\n{"lender":"Adam","borrower":"Bob","amount":5.25}"`

or (to add spacing for readability),

```
POST /iou

{
  "lender": "Adam",
  "borrower":"Bob",
  "amount":5.25
}
```

The expected output would be similar, simply the HTTP start line and body (for simplicity).
