### ISSUE TITLE
grep: conflicting flags

### ISSUE THREAD

**Issue by rstockbridge** [exercism/problem-specifications#1256]
I just completed the grep exercise, and noticed that the tests didn't cover cases where flags conflict. E.g., what should happen in the following cases?
1. `-n` and `-l`
2. `-x` and `-v`

Some experimentation with grep shows that
1. `-n` takes precedence over `-l`
2. checks that the entire line does not match the pattern

The tests `oneFileNoMatchesVariousFlags()` and `multipleFilesNoMatchesVariousFlags()` contain the flags `-n`, `-l`, `-x`, and `-i`, but don't actually test the situations described above because there are no matches. 

I did make sure that my solution produces the behavior described above (http://exercism.io/submissions/74bcc15ff83b4a00aeb7a919e0f1158d) although certainly I may have missed other conflicting flag combinations.

It might be helpful to either include tests that indicate how to resolve conflicting flags, or the README should indicate that this level of detail is not necessary. What do you think?

(Originally posted on the Java track and was encouraged to move it here.)

**Comment by cmccandless** [comment]
[Exercise Description](https://github.com/exercism/problem-specifications/blob/master/exercises/grep/description.md)

**Comment by cmccandless** [comment]
I like the idea of adding these tests. It should be fairly straightforward to add them to the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/grep/canonical-data.json).
