### ISSUE TITLE
bob: consider sentence ending with question mark followed by other punctuation marks

### ISSUE THREAD

**Issue by queleok** [exercism/problem-specifications#1257]
It looks like the current test suite for the Bob exercise is missing a case when a sentence is ending with a question mark followed by other punctuation marks, e.g.:
- What the heck?!
- Does it make any sense to you?..

**Comment by rpottsoh** [comment]
@queleok I am not sure where you would like to go with the examples you provided.  I thought I would provide some background regarding sentences that end in a manner like you have described:
https://litreactor.com/columns/punctuation-pairs-how-to-combine-punctuation

Are you considering both examples to be questions?  I am guessing they are both questions since the `?` comes first.

**Comment by queleok** [comment]
@rpottsoh , thanks for the link! Sorry, I probably should've started with something like that. Yes, I would consider both sentences to be questions, but I am not a native English speaker, so I may very well be wrong about that. Your link indicates I'm not exactly wrong about the first sentence, but I couldn't find any information on the second one.

Anyway, I think it would make sense to either:
- explicitly define rules determining a question sentence,
- or limit the scope of the incoming messages that could be received mentioning something like: 

> Bob's interlocutor is a purist in written communication, and always follows the grammar.

**Comment by cmccandless** [comment]
> Bob's interlocutor is a purist in written communication, and always follows the grammar.

I like this.

**Comment by cmccandless** [comment]
Some minor modifications to @rpottsoh 's suggestion:

- Remove reference to "pen pal"; adds context to description that did not exist before
- Specify `in English` (maybe unnecessary, as Exercism always uses English for exercises unless otherwise specified)


```
Bob's conversational partner is a purist when it comes to written communication and always follows normal rules regarding sentence punctuation in English.
```

**Comment by rpottsoh** [comment]
@cmccandless my suggestion was kind of tongue-in-cheek, I think you've nailed the intent of what I was trying to say.

**Comment by queleok** [comment]
I like @cmccandless's version

**Comment by rpottsoh** [comment]
Task to be completed:

- Prepend sentence `Bob's conversational partner is a purist when it comes to written communication and always follows normal rules regarding sentence punctuation in English.` to [description.md](https://github.com/exercism/problem-specifications/blob/master/exercises/bob/description.md)
- Use a word in https://help.github.com/articles/closing-issues-using-keywords/ in your commit message to indicate that you have closed this issue.
