### ISSUE TITLE
Exercise Idea: Affine Cipher

### ISSUE THREAD

**Issue by guygastineau** [exercism/problem-specifications#1260]
After doing an atbash exercise I researched the affine cipher and found it to be much more engrossing.
I believe that it could make an excellent addition to the exercism family of problems!

Here you can see the files I have prepared for the bash track:

[README.md.txt](https://github.com/exercism/problem-specifications/files/2194562/README.md.txt)

[affine_cipher_test.sh.txt](https://github.com/exercism/problem-specifications/files/2194564/affine_cipher_test.sh.txt)

[example.sh.txt](https://github.com/exercism/problem-specifications/files/2194565/example.sh.txt)

In the above test I check for pipe functionality.  The pipe functionality is pretty bash specific so I'm not expecting it for other languages.

The example.sh(.txt) above can be invoked as:
    `bash example.sh encode 3 7 "string/or/file"` or 
    `echo "string/or/file" | bash example.sh encode/decode 15 4`

The files for bash are most polished but here are two (unpolished) ruby example solutions to an affine cipher:

This one, named first_affine uses true affine encryption and decryption with the functions
 E(x) = (ax + b) % m and D(y) = a^-1(y - b) % m where a^-1 is the modular multiplicative inverse of a
[first_affine.rb.txt](https://github.com/exercism/problem-specifications/files/2194576/first_affine.rb.txt)
 
This one, simply called affine, encrypts the alphabet from the key and saves resources (and eyes) by encoding and decoding with a simple call of tr with the encrypted alphabet.  I'm developing this implementation into an object with a lot of possibilities
[affine.rb.txt](https://github.com/exercism/problem-specifications/files/2194583/affine.rb.txt)

I haven't made a test for ruby yet. I have tested this class in irb.  The advantage for learners using
OO languages is in building the real decryption function first -  requiring a method to find the modal multiplicative inverse of a - and then developing the simpler implementation. Then, in the tr implementation adding functionality such as changing the key of the object and regenerating the cipherbet without making a new object.

Well, I hope this hasn't been too long winded.  Everyone, please let me know what you think.
I would really like to get this available for any tracks with interest as it really gets participants to dig deeper into ciphers.

Cheers
Guy Gastineau

**Comment by guygastineau** [comment]
@budmc29

**Comment by rpottsoh** [comment]
@guygastineau thanks for taking the time to create this issue.  I think it would be helpful if you could format the proposed exercise into the format outlined in this tracks README.  Submitting a PR that contains the three files that are needed to define an exercise.  Others can then see what you have and can help if you run into problems.

**Comment by guygastineau** [comment]
@rpottsoh thank you.  I didn't see that readme before posting this. I originally tried to submit it to the bash track and they pointed me here 

I'll work on fitting it to the specifications here.

I was also told that people might be more likely to review this issue if the files are inline with syntax highlighting instead of being linked for download.  I'll edit my post above to be like that when I've made the changes.

**Comment by guygastineau** [comment]
@rpottsoh 
Here is the pull request I made #1262
