### ISSUE TITLE
When submitting a new exercise should a glyph for the exercise also be included?

### ISSUE THREAD

**Issue by rpottsoh** [exercism/problem-specifications#1268]
@kytrinyx or @iHid,

I think this issue has not been raised.  I know, right now, the development team is taking care of glyphs for the exercises.  Is there a mechanism in place (or planned) to help take care of implementing icons for new exercises as they are added to this repo?

**Comment by rpottsoh** [comment]
I realize that the glyphs do not exist in this repo, at the moment.

**Comment by iHiD** [comment]
The best method would be to create an issue on exercism/website-icons and tag @nicolechalmers and me in it.

**Comment by rpottsoh** [comment]
Issue moved to [exercism/website-icons #7](https://github.com/exercism/website-icons/issues/7) via [**ZenHub**](https://www.zenhub.com/)
