### ISSUE TITLE
README.md: should have a statement regarding informing design team when a new glyph is needed for a new exercise

### ISSUE THREAD

**Issue by rpottsoh** [exercism/problem-specifications#1271]
When creating a new exercise the design team needs to be informed that there is a need for a new glyph for the new exercise.

@iHiD said in exercism/website-icons#7:
> ...when a new exercises is added to specifications, a new issue should be opened here to inform the design team that a new icon needs designing. Any suggestions or examples in that issue will be appreciated too.

Task to be completed:
The README for this repo should have a statement added to document the need for this new measure to be taken when creating a new exercise.

When a new issue is opened in exercism/website-icons it should make a reference to the new exercise's PR that is slated to be merged or was recently merged.  Having easy access to the new exercise documentation could be useful during the design of a new glyph.

**Comment by iHiD** [comment]
Thanks @rpottsoh!
