### ISSUE TITLE
Difference-of-squares: name should change

### ISSUE THREAD

**Issue by guygastineau** [exercism/problem-specifications#1273]
Hi,

It has come to my attention while updating bash exercises that the this exercise has three different processes.
- only one of these gets the difference of anything.
- I am willing to do the manual work for the PR, but I wanted community feedback regarding the name.

**Comment by Stargator** [comment]
What would the proposed new name be? Or if there are several proposed names to choose from, what are they?

**Comment by rpottsoh** [comment]
Changing an exercise name is kind of a big deal.  From what I have seen it involves deprecating the exercise and then starting a new exercise, with the new name.

If this is a real problem for this exercise perhaps it would be better to add test cases that are more in line with the name of this exercise if you feel it is light in that department.

**Comment by guygastineau** [comment]
@rpottsoh thanks for letting me know.

I kind of figured that would be the case.
I guess the problem for me is that I think the test cases make for a good exercise.

Furthermore, it is nice that it tests arms that come together in the end to get what the name suggests.

In bash it just feels weird to type in `diff-of-squares -s 12` and get the sum of squares back.

**Comment by guygastineau** [comment]
Maybe I'll start thinking about an exercise that has these test types and perhaps some others that all would fit nicely under one exercise name dealing with sqaures and other operations working with them.

Would it be a good idea to submit something like that before proposing depricated?

**Comment by rpottsoh** [comment]
I don't think there is anything wrong with proposing a new exercise.  During the course of discussion the consensus might decide that certain exercises should be deprecated.  This happened when all-your-base was developed, several exercises were deprecated.

**Comment by guygastineau** [comment]
Okay.

@rpottsoh. I guess I'll close this for now. 
Thanks for pointing me in a good direction for working on this.

**Comment by rpottsoh** [comment]
My pleasure and good luck!

**Comment by guygastineau** [comment]
Thanks for your input @NobbZ.

- I don't completely understand what you mean about the uuid making this easier in V2.

- I like how it leads the student. The ruby implementation of the test makes sense with the name.  A bash implementation feels a little weird with a program named `difference_of_squares.sh` returning those other types of information, but changing it is not an absolute must.

**Comment by NobbZ** [comment]
> I don't completely understand what you mean about the uuid making this easier in V2.

As long as the UUID remains the same, we can name it however we want and it will still be the same exercise.

**Comment by NobbZ** [comment]
Also no-one forces you to actually name your file `difference_of_squares.sh`, you can name it `gauß.sh` as well, but that probably is a too big spoiler ;)

**Comment by guygastineau** [comment]
I see what you mean. That is cool.

I wouldn't be interested in taking away any test cases, but there could be some more that might fit better with another name.

Personally if I had a class who's sole purpose was to return the difference of the two other methods, then I would make the other methods private in something like ruby.

Since it tests that they are public methods I think it's a good idea for the name to change.

Do you think I should reopen this?

Also, to everyone: I am interested in brain storming here about a new name that more adequately represents or broadens the scope of the exercise

**Comment by guygastineau** [comment]
@BobbZ haha

That's a good point. I am working on a generator for the bash track.

I suppose the template could just use a different file name in the run string for the test cases.

I'll see what everyone thinks over there.
