### ISSUE TITLE
allergies: Why is 257 "eggs only"?

### ISSUE THREAD

**Issue by seccobit** [exercism/problem-specifications#1284]
Hi, qq, on exercise "Allergies"
on the note: 

"Note: a given score may include allergens not listed above (i.e. allergens that score 256, 512, 1024, etc.). Your program should ignore those components of the score. For example, if the allergy score is 257, your program should only report the eggs (1) allergy."

What's the rationale to have score 257 meaning allergy to Eggs only
and from 'allergies_test.py' --> Allergies(509).lst, [
'eggs', 'shellfish', 'strawberries', 'tomatoes', 'chocolate',
'pollen', 'cats'
])

This doesn't look right?

**Comment by petertseng** [comment]
>

**Comment by petertseng** [comment]
> What's the rationale to have score 257 meaning allergy to Eggs only

257 is 256 + 1, and 1 is eggs, so 257 indicates the person is allergic to eggs (1), and if there were an allergen of 256, the person would be allergic to that as well.

> Allergies(509).lst
> 'eggs', 'shellfish', 'strawberries', 'tomatoes', 'chocolate', 'pollen', 'cats'

509 is 1 + 4 + 8 + 16 + 32 + 64 + 128 + 256, so 509 indicates the person is allergic to eggs (1), shellfish (4), straweberries (8), tomatoes (16), chocolate (32), pollen (64), cats (128), and if there were an allergen of 256, the person would be allergic to that as well.

**Comment by petertseng** [comment]
> This doesn't look right?

It looked right to me, please tell me if I made a mistake in my calculation

**Comment by seccobit** [comment]
wow, thanks...pretty imaginative. 
I was interpreting it as after the sum of all allergens values (258), the count will start over... so 259 would be 'Egg', 264 [Eggs,Shellfish] and so on... 

Assume, based on your answer, the code should account for 'any' allergen value which are NOT in the given list?

**Comment by seccobit** [comment]
Also sorry, for the second example (509), why this take into account the first non-listed allergens? 
Why the non-listed allergens would not be 508 and hence 509 representing 1 --> [Eggs]?
Do we need to take into account/keep a list of all previous non-listed allergens? In this example 256? 

The below is bit confusing, not clear if the i.e. value are random example or if they are the actual values of non-listed allergens that we have keep track of: 

"a given score may include allergens not listed above (i.e. allergens that score 256, 512, 1024, etc.)"

**Comment by petertseng** [comment]
> I was interpreting it as after the sum of all allergens values (258)

The sum of all allergen values is 255, not 258 (one can verify this by typing `1 + 2 + 4 + 8 + 16 + 32 + 64 + 128` into some program capable of calculating it)

> the count will start over... so 259 would be 'Egg', 264 [Eggs,Shellfish] and so on...

That's a valid way to see it. 256 would be [], 257 would be [Egg], 258 would be [Peanuts], 259 would be [Egg, Peanuts], and so on.

> the code should account for 'any' allergen value which are NOT in the given list

That appears that that's what the https://github.com/exercism/problem-specifications/blob/master/exercises/allergies/canonical-data.json says. I make no judgments of what should be, only what is.

> the second example (509), why this take into account the first non-listed allergen?

Each allergen's score is always twice the one previous, so they can only take on the values 128, 256, etc. There is no single allergen with value 508. 508 is 4 + 8 + 16 + 32 + 64 + 128 + 256, so represents someone allergic to all of those things.

> The below is bit confusing, not clear if the i.e. value are random example or if they are the actual values of non-listed allergens that we have keep track of:
> "a given score may include allergens not listed above (i.e. allergens that score 256, 512, 1024, etc.)"

Each allergen's score is always twice the one previous, so they can only take on the values 128, 256, 512, 1024, 2048, etc.

**Comment by petertseng** [comment]
Occurs to me: Look at what I said:

> Each allergen's score is always twice the one previous

That's never mentioned in https://github.com/exercism/problem-specifications/blob/master/exercises/allergies/description.md .

**Comment by mienaikage** [comment]
I personally find it easier to understand by picturing it in binary. Each bit represents an allergen:

`00000000`

So for example, eggs and shellfish would be `00000101`

256 gives an extra bit which doesn't apply to any allergen `100000000`, but 257 would be `100000001`, which has the bit for eggs.

**Comment by Insti** [comment]
Closing, it looks like this got a satisfactory answer.
