### ISSUE TITLE
What is the definitive list of core exercises?

### ISSUE THREAD

**Issue by macta** [exercism/problem-specifications#1286]
The config.json has an entry "core": true/false - where is the list of exercises that are considered core that a new language track should implement?

Do I just copy what one of the prime languages has done (I'm assuming go or python are pretty well used?)

**Comment by rpottsoh** [comment]
There is no list of core exercises.  Technically each track is free to determine which exercises make the most sense to be core.  If you are not sure, then your thought of looking to another track, that is well established, but is also maybe most similar to your track, is a good one.

**Comment by ErikSchierboom** [comment]
As @rpottsoh said, there is no such definite list, although there are several exercises that many tracks include as core, such as `leap`, `bob` and `two-fer`. It is up to the track maintainers themselves to define the core exercises such that: 

- The difficulty gradually increases.
- The user is slowly introduced to new concepts.

**Comment by ErikSchierboom** [comment]
Do the above posts answer your question @macta?

**Comment by macta** [comment]
Kind of  - but I think it’s worthy of having a common list for new tracks to start with. If learning a new
Language(s),comparing the approach across a number of common exercises is useful.

The work in the cSharp track looks very worthy - and I fact it seems like many tracks have it specified quite badly (it’s just grown organically in a confusing way) - eg two-fer is trivial yet appears quite late in many tracks as an afterthought.

For me, I’ll learn from cSharp and report back (unless there is a better track that comes to mind)

**Comment by ErikSchierboom** [comment]
Well, that might be a good starting point (I'm a maintainer of the C# track ;)), but there is also an issue on that we should tweak the core exercises of the C# track: https://github.com/exercism/csharp/issues/611. It might be relevant to also check that thread.

**Comment by Insti** [comment]
Is this (OP) question documented anywhere? It is a FAQ that probably should be.

**Comment by F3PiX** [comment]
How about we use this repo's wiki to record questions/answers/discussions that we want to document? (I'm not a big fan of the leaving-issues-open-kind-of-documentation ;-) )

**Comment by sshine** [comment]
@mata: Trusting that your question was answered, I'm closing this issue.

**Comment by macta** [comment]
Leave it closed - but as a newcomer in a language that several strong tracks are derived from (ruby, python, c#) I find it unfathomable. I can’t work out any common groupings,  keywords or difficulty - I’ll muddle through 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
