### ISSUE TITLE
tree-building: working code isn't working

### ISSUE THREAD

**Issue by hilary** [exercism/problem-specifications#1296]
The description for tree-building says

> Your job will be to refactor a working but slow and ugly piece of code that implements the tree building logic for highly abstracted records.

yet the initial code for both the golang and python implementations of the exercise does not pass the tests, which substantially alters the nature of the problem given to the student.

What is the intended behavior of the tree-building exercise? Should the initial code given to the student pass the tests? If not, we ought to, at the least, update the README. If yes, golang and python have some work to do on their versions (If only a customized version of the README).

See also https://github.com/exercism/go/issues/1119

**Comment by rpottsoh** [comment]
For convenience https://github.com/exercism/problem-specifications/blob/master/exercises/tree-building/description.md

**Comment by hilary** [comment]
Thanks @rpottsoh

**Comment by hilary** [comment]
I'm closing this as both the python and golang tracks have updated their initial interpretations. Yay!
