### ISSUE TITLE
simple-cipher: validating input strings

### ISSUE THREAD

**Issue by xarxziux** [exercism/problem-specifications#1298]
I've already raised this as a separate issue in exercism/ecmascript#445, but have just discovered that I should be raising it here.

The unit tests for the Simple Cipher include testing for an error if the cipher is all caps, or all digits, but this is in adequate for the description.  Part of the instructions state:  "Let's make your substitution cipher a little more fault tolerant by ... ensuring that the key contains only lowercase letters".

Unfortunately this is not checked for, and I've seen one case where the submission passed the tests but did not conform to the description.  The addition of tests for spaces or punctuation marks in the key would have failed the submission.

The specification needs to be updated to include these kind of checks.

**Comment by rpottsoh** [comment]
[description](https://github.com/exercism/problem-specifications/blob/master/exercises/simple-cipher/description.md)
[testdata](https://github.com/exercism/problem-specifications/blob/master/exercises/simple-cipher/canonical-data.json)

**Comment by rpottsoh** [comment]
@xarxziux thanks for bringing this issue to light.  Would you be willing to submit a PR that fixes this issue?

**Comment by xarxziux** [comment]
Willing: yes, able: not at the moment.  If you're OK with waiting a week or so, then I'll put something up.

**Comment by rpottsoh** [comment]
There is no rush.

**Comment by Insti** [comment]
I'm in favour of removing the case checking from the description rather than adding it to the tests. This exercise is about simple cipher not string validation.

See also: https://github.com/exercism/problem-specifications/issues/523

**Comment by Insti** [comment]
See also: https://github.com/exercism/problem-specifications/issues/902

**Comment by rpottsoh** [comment]
#1346 has been merged and #1345 closed, which should now close this issue as well.
