### ISSUE TITLE
prime-factors: should test for set intersection, instead of array equality

### ISSUE THREAD

**Issue by bennypowers** [exercism/problem-specifications#1302]
Current tests for prime-factors have assumptions about implementation built in.

For example

`primeFactors(4) == [2]` will fail but `primeFactors(4) == [2, 2]` will pass.

Solutions that build a list of factors (or primes) and then filter them will fail.

Let me know if I've missed the spirit of the exercise.

**Comment by Insti** [comment]
The intention of the exercise is to generate the *list* of prime factors.

> list of prime factors of 60: 2, 2, 3, and 5.

Can suggest a change to the [problem description](https://github.com/exercism/problem-specifications/blob/master/exercises/prime-factors/description.md) that would make this more clear?

**Comment by cmccandless** [comment]
Additionally, the definition of prime factorization is to find *all* factors that are prime such that the product of that resulting list equals the original number.

See:
- https://en.wikipedia.org/wiki/Table_of_prime_factors#1_to_100
- http://mathworld.wolfram.com/PrimeFactorization.html

**Comment by bennypowers** [comment]
Thanks for the explanations, closing.
