### ISSUE TITLE
isogram: no test for duplicate if the second one is upper case 

### ISSUE THREAD

**Issue by wiredancer** [exercism/problem-specifications#1303]
I suggest adding this test (C track):
```
void test_duplicated_letter_mixed_case2(void)
{
   TEST_ASSERT_FALSE(is_isogram("alphAbet"));
}
```

**Comment by petertseng** [comment]
Oh, interesting, so it is different from https://github.com/exercism/problem-specifications/blob/master/exercises/isogram/canonical-data.json#L58 (`Alphabet`) because explicitly that the second one is upper case. It will be an interesting implementation that would reject `Alphabet` but accept `alphAbet`. What might one look like?

**Comment by wiredancer** [comment]
a student came up with one :-)
https://exercism.io/mentor/solutions/d01117e2bbd44856a332ed7c61e231f5?iteration_idx=3
```
#include <stdio.h>
#include <ctype.h>
#include "isogram.h"

bool is_isogram(const char phrase[])
{
    const char *phrase_letter = phrase;

    // process each char in the phrase
    while (*phrase_letter != 0)
    {
        // copy the character we're currently processing
        // and make it lower case if need be
        char current = tolower(*phrase_letter);

        // we only care about letters though
        if (current < 'a' || current > 'z')
        {
            phrase_letter++;
            continue;
        }

        // check if each remaining letter in the phrase is
        // the same as the one we're currently processing
        const char *remaining_letter = phrase_letter + 1;
        while (*remaining_letter != 0)
        {
            // grab a copy of the possible duplicate
            // and make it lower case as well if need be
            char possible_dup = *remaining_letter;

            // if we found a duplicate return false
            if (current == possible_dup)
            {
                return false;
            }
            remaining_letter++;
        }
        phrase_letter++;
    }

    return true;
}
```

**Comment by petertseng** [comment]
I see. The intent was there (in the comment), just needed to actually be done.

Yes, it figures that some of the solution that choose to use this model (the O(n^2) model) would be sensitive to the ordering.

It seems that the case should be added.

**Comment by rpottsoh** [comment]
@wiredancer this sounds like a worthwhile test case to be added to the canonical data of this exercise.  Would you be willing to open a PR to update the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/isogram/canonical-data.json) file for this exercise?

**Comment by wiredancer** [comment]
created new PR #1307
