### ISSUE TITLE
rest-api: sorting of user list

### ISSUE THREAD

**Issue by cmccandless** [exercism/problem-specifications#1304]
from @karelvancamp (https://github.com/exercism/exercism/issues/4293#issue-)353830321
> It's not defined in the Instruction Methods if and how the users should be sorted.

    {"users":<List of User objects for >}

> Though it does seem to require alphabetic sort based on object.name to pass the tests.

**Comment by rpottsoh** [comment]
@cmccandless any desire to implement a change to testdata or README to resolve this issue?
