### ISSUE TITLE
change: Which, if any, input/coin combinations are errors?

### ISSUE THREAD

**Issue by petertseng** [exercism/problem-specifications#1313]
Notice that https://github.com/exercism/problem-specifications/blob/master/exercises/change/canonical-data.json uses `-1` to indicate "cannot make the target amount using the coins given". The question: Should this be considered an error? If so, `change` is covered by https://github.com/exercism/problem-specifications/issues/1311.

I consider searching for a negative target an occurrence that an implementation should not be expected to handle. So I think using an `error` object is reasonable here. We can discuss implementations that should handle negative targets with negative coins, but I think it can be considered out of scope for the exercise. But you can see my previous comments https://github.com/exercism/problem-specifications/issues/336#issuecomment-280231149 on it.

I consider searching for a non-negative but unattainable target an occurrence that the implementation should expect to routinely happen -- in a language with exceptions, for example, I would not recommend the use of an exception for this. A language with optionals would use its `None` for this case, and use `Some(coins)` when there actually is a coin combination.

I would normally refrain from commenting on whether this should be represented in JSON as a `-1` sentinel or an `error` object or `null`.

But, as I say in https://github.com/exercism/problem-specifications/issues/905#issuecomment-330184896 , I also wouldn't encourage languages with *both* optionals and errors (Rust's `Option` and `Result`, or Haskell's `Maybe` and `Either`) to use both of those. So in the target language, I'd suggest just using one.

So this leads me to think they should all be expressed as an `error` object.

In the absence of any other preference, I would suggest to say that all of these should be represented by an `error` object, so this should be handled as part of https://github.com/exercism/problem-specifications/issues/1311. In that case, we can close this issue, for https://github.com/exercism/problem-specifications/issues/1311 will remind us to change `change`'s JSON appropriately.

**Comment by petertseng** [comment]
EBWODP:

> I'll refrain from commenting

That's incorrect. I commented. So, I amend that to "I would normally refrain"

**Comment by Insti** [comment]
```
    {
      "description": "no coins make 0 change",
      "property": "findFewestCoins",
      "input": {
        "coins": [1, 5, 10, 21, 25],
        "target": 0
      },
      "expected": []
    },
    {
      "description": "error testing for change smaller than the smallest of coins",
      "property": "findFewestCoins",
      "input": {
        "coins": [5, 10],
        "target": 3
      },
      "expected": -1
},
```
I don't understand why an error even needs to be considered here.
These cases should be equivalent.
The expected value should be an empty array.

I propose all the `-1`s be changed to empty arrays.

**Comment by NobbZ** [comment]
@Insti there is a clear distinction between those cases. In the first, we need none of the coins available to create a stack of value `0`, while in the latter case, we can not reach the target value with the coins provided.

In my opinion, there should be an error in the latter case.

**Comment by Insti** [comment]
:heart: Thanks for clearing that up for me.
Also with my proposal it would not be possible to tell the difference between 'total is zero' and 'total is not possible'

proposal withdrawn.
