### ISSUE TITLE
phone-number: test cases could be more thorough

### ISSUE THREAD

**Issue by LyleCharlesScott** [exercism/problem-specifications#1320]
I noticed when fixing some problems with the JavaScript test cases for phone-number that there is room for improvement, specifically around 11-digit numbers starting with 1. There are tests covering 11-digit numbers that pass and fail based on the first digit being 1, but the tests do not cover whether the rest of the number fits the NXX-NXX-XXXX format 
(N >= 2 && N <= 9) && (X >= 0 && X <= 9). 

Numbers like 1-123-456-7890 and 1-223-156-7890 are invalid and should fail, but would pass the test cases if the code returns 11-digit numbers starting with 1 as valid without further checking the string.

**Comment by rpottsoh** [comment]
@LyleCharlesScott would you be willing to open a PR that would add test cases to the [testdata](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json) to cover this issue?

**Comment by LyleCharlesScott** [comment]
I updated the javascript track; I can send a pull request for the canonical data also :-)

**Comment by sshine** [comment]
@LyleCharlesScott Let me know if you still plan to move your improvements from [ac0ec013...](https://github.com/exercism/javascript/commit/ac0ec01300b6a4079814b030647ea75caf1cbfa6) into canonical data. :1st_place_medal:
