### ISSUE TITLE
protein-translation: Codons/Acids table not rendering properly

### ISSUE THREAD

**Issue by Mavelous** [exercism/problem-specifications#1326]
See https://github.com/exercism/java/issues/1508

Problem might exist in the file https://github.com/exercism/problem-specifications/blob/master/exercises/protein-translation/description.md

However, I'm not sure how to fix it, because I'm not sure how the README's are generated (per https://github.com/exercism/website-copy/issues/429).

**Comment by sdublish** [comment]
Can confirm the table doesn't render properly on Chrome and Edge (OS Windows 10).

Would it be better to just have an embedded image of the codon table in the README? There are a lot of those available online. The issue would be that there would be more codons listed than what are currently used, so definitely would understand if writing in the table manually makes more sense.

**Comment by rpottsoh** [comment]
The READMEs are just markdown.  Each track may use `configlet` to generate a README that is specific to that track; `configlet` pulls from the exercise's description.md from this repo.  If the site is not rendering the resulting mark down properly then this needs to be investigated further at the site level.  

If the site, for whatever reason, is incapable of rendering the mark down correctly, then, it may be necessary to rethink how the information is laid out in this exercise's description.md.  I suspect the problem will be found and corrected so it will not become necessary to make any changes here.

**Comment by rpottsoh** [comment]
cc: @iHiD

**Comment by cmccandless** [comment]
This is a [known issue](https://github.com/exercism/exercism/issues/4294)
