### ISSUE TITLE
Twelve-Days: Puncutation error

### ISSUE THREAD

**Issue by PatrickMcSweeny** [exercism/problem-specifications#1328]
In the Twelve Days of Christmas, there should be a colon, not a comma, after 'gave to me.' A colon more accurately reflects the rhythm of the song as well as grammatically indicates that the first part of the sentence is meant to set up the second part.

**Comment by rpottsoh** [comment]
@PatrickMcSweeny, if you are willing, you may submit a PR to correct this.
