### ISSUE TITLE
rest-api: Inconsistent decimal format in canonical data

### ISSUE THREAD

**Issue by yvincent** [exercism/problem-specifications#1353]
The problem specifications for REST Api ([https://github.com/exercism/problem-specifications/blob/master/exercises/rest-api/canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/rest-api/canonical-data.json)) have all numbers represented with 1 decimal, 3.0 for instance.

However in test case "borrower has negative balance", it contains a simple integer: "balance": -6.
This value should probably be replaced by -6.0 in order to be consistent.

**Comment by Insti** [comment]
https://github.com/exercism/problem-specifications/blob/master/exercises/rest-api/canonical-data.json#L193

**Comment by Insti** [comment]
Thanks @yvincent :heart:
