### ISSUE TITLE
Meta: crowdsource topics?

### ISSUE THREAD

**Issue by nicolemon** [exercism/problem-specifications#1354]
The mentoring guide is great, but one thing it doesn't mention is how the test cases themselves are labelled (tagged, topic'd - unsure if we have a specific nomenclature for it) - I always assumed those labels are meant to indicate what the primary learning objectives of the exercise are, which I took as an "initial check list" of things to make sure the mentee demonstrates understanding of. Is that accurate?

To that end, do we think it'd be beneficial to allow everyone (maybe just mentors at first) to label exercises as they see fit and float the most popular ones to the top and feature them on the actual exercise page? Like crowdsourcing what the learning objectives are. It'd also be useful to allow
the mentees to label the exercises after they complete them with what concepts they learned or worked with.

(Apologies if this has already been discussed - I just figure it takes less time to ask and be told it's already addressed than it does to search through discussion backlogs.)

**Comment by iHiD** [comment]
Hello. Great points.

So a few quick thoughts:
1) The mentoring guides aim to address this by giving mentors points to look for (e.g. https://github.com/exercism/mentors/tree/master/tracks/ruby/exercises/two-fer)
2) Those guides will be getting properly bedded into the website in the coming weeks.
3) We're currently considering how we can add a better "curriculum" to Exercism tracks to work out specifically what different exercises focus on. @F3PiX is heading that up.

Those things should make it clearer what mentors should be looking for, however having a bit of "Things to look for when solving this exercise" might be another good addition for the students.

**Comment by petertseng** [comment]
The documented purpose of topics can be found at https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md#topics - does the current usage match the documented purpose? If not, should the documented purpose be updated to match current usage? (Versus the alternative of attempting to make usage match documentation)

If the crowdsourcing is to be done via GitHub, then the proper thing to do is to educate about the existence of the config files such as https://github.com/exercism/c/blob/master/config.json and encourage contributions to the topics sending PRs which edit the config.json files. 

If crowdsourcing needs to be doable via the website, then the issue should be opened in the https://github.com/exercism/exercism repo.

**Comment by petertseng** [comment]
EBWODP:

> the proper thing to do

It was improper of me to say that, since I didn't define the standards of properness. Instead, I'll reword to say that it is one possible alternative.

**Comment by ErikSchierboom** [comment]
With Exercism v3, topics have been deprecated. Therefore, I'm closing this issue.
