### ISSUE TITLE
bracket-push: add test case with too many closing brackets

### ISSUE THREAD

**Issue by omer-g** [exercism/problem-specifications#1386]
I would like to suggest an additional test case, where there are more closing brackets than opening brackets. 

For example: `"[]]"` should return `False`

 I came across a stack based solution that passed all current tests, but would fail this test. In general, students could fail this test with a stack based solution if they do not treat an empty stack as a failure, when a bracket is expected to be there. I think it would make sense to add this test case. I would be happy to hear what others think.

**Comment by coriolinus** [comment]
Makes sense to me. Want to open a PR adding it?

**Comment by omer-g** [comment]
I'd be happy to create a PR for this. I think I should be available to work on it only next week.
