### ISSUE TITLE
isogram: Add test case for duplicate following non-letter

### ISSUE THREAD

**Issue by bitfield** [exercism/problem-specifications#1390]
I had a Go student submit a solution like this:

```go
	for _, char := range word {
		if !unicode.IsLetter(char) {
			break
		}
```

I'm sure they meant `continue` rather than `break`, but the test cases don't catch this, because there is no case where a non-letter character is followed by a duplicated character. 

An example test case which would catch this problem:

```json
        {
          "description": "hypothetical word with duplicated character after hyphen",
          "property": "isIsogram",
          "input": {
            "phrase": "thumbscrew-jappingly"
          },
          "expected": false
        },
```

**Comment by rpottsoh** [comment]
@bitfield would you be willing to open a PR that makes the necessary changes to the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/isogram/canonical-data.json) file?  Along with the new case you are proposing the `"version":` would also need to be bumped.  Refer to the README for this repo for direction on how to bump the version.  The PR should close/fix this issue.

**Comment by bitfield** [comment]
Done! Thanks for the help.
