### ISSUE TITLE
luhn: Add test case for valid number with even length

### ISSUE THREAD

**Issue by bitfield** [exercism/problem-specifications#1391]
I had a Go student submit a solution like this:

```go
		if i == 1 || i%2 == 0 {
			y *= 2
```

The logic for picking 'every second digit from the right' is not correct, but it works with the existing tests, because all the valid numbers have an odd number of digits.

This is a test case which would fail this incorrect solution, but pass for correct solutions:

```json
      {
        "description": "valid number with an even number of digits",
        "property": "valid",
        "input": {
          "value": "095 245 88"
        },
        "expected": true
      },
```

**Comment by rpottsoh** [comment]
@bitfield would you be willing to open a PR to implement this new case?  This [comment](https://github.com/exercism/problem-specifications/issues/1390#issuecomment-437704471) applies....
