### ISSUE TITLE
hamming: reduce number of test cases

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/problem-specifications#1403]
If one examines the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/hamming/canonical-data.json) of the `hamming` exercise, one finds that it has many different test cases. However, I would argue that many test cases don't add any value and go against our unwritten rule that new tests cases should require changes to the code to make them pass. In other words, at some point, the implementation will  pass the first number of tests, and then most likely also automatically pass all the subsequent tests (except for the error handling ones).

IMHO the fix to this is to remove (most of) the unneeded test cases. What exactly the test cases are that should be removed is up for discussion.

**Comment by F3PiX** [comment]
I agree that there're too many test cases. 

I also think that the order of the cases matter. I'd like the tests to handle the happy path first, before handling the edge cases.

I'll take a look at the Ruby implementation to see what cases can be removed from a Ruby point of view. Or rather: which cases should stay.

**Comment by bitfield** [comment]
There's also the point that specific test cases can catch common mistakes. There may be 50 different common mistakes for a given exercise, of which any individual student might only make a few. Nonetheless, the cases are valuable for the population of students as a whole. (I'm not saying this is the case for Hamming necessarily; just a general observation.)

**Comment by ErikSchierboom** [comment]
> I'm not saying this is the case for Hamming necessarily; just a general observation.

Well, I'm saying this is _not_ the case for Hamming, hence the issue :)

**Comment by bitfield** [comment]
Quite. I should have made it clearer that I wasn’t disagreeing with you, just pointing out that there is sometimes value in extra test cases beyond just ‘valid output’.

**Comment by rpottsoh** [comment]
Thanks @ErikSchierboom this is an excellent rundown and is clear to me now.
