### ISSUE TITLE
list of tracks with test generators

### ISSUE THREAD

**Issue by petertseng** [exercism/problem-specifications#1411]
Well, since the repo of https://github.com/exercism/discussions/issues/155 got closed, it's not possible to edit the issue text there anymore. It's not clear that there's a better home for this issue. I don't want to put it in https://github.com/orgs/exercism/teams/track-maintainers because then people not in the org can't see it, and I don't think this information should be withheld from people outside the org.

---

These are anything that use the canonical-data.json file from problem-specification and generate a test suite to be delivered to students of a given track.

If your track has these, I would be interested to hear about it.

I hope this can help tracks that don't have generators evaluate whether to have them, and allow tracks that already have generators to learn from each other.

Questions I would like to ask:

- How much additional code must you write to generate tests for each new exercise?
    - On one extreme, **zero additional code** is needed: A single generator can generate code for every single exercise.
    - On the other extreme, **maximal additional code** is needed: No code at all is shared between generators of any two exercises.
    - Where on this spectrum is your track currently?
    - Where on this spectrum would you like your track to be, ideally?
- Although all the inputs to an exercise are guaranteed to be under the `input` key, for exercises with more than one input, it's not certain what order they should go in. How do you deal with this?
    - Require a small bit of configuration per exercise that has multiple inputs, saying what order the inputs are in.
    - Accept the order that the inputs are defined in the textual representation of the JSON file (keeping in mind that https://www.json.org/ specifies they are unordered, but hoping that when they were written down in the JSON file, they have a consistent order?)
    - Your idea here
- Statically typed languages: How do you deal with the fact that you cannot determine what types the keys/values of a test case will have until you read the value at the `property` key? (In some JSON parsers in statically-typed languages, you must declare the types of all key/value pairs in a JSON object before you can parse it, but sometimes the key/value pairs present depend on `property`)
    - C# and Scala: Parse into a map/dictionary of string -> any type.
    - Go: Delay full parsing until `property` is read, then parse into different structs depending on what `property` is (https://github.com/exercism/go/pull/677).
- Are there any possible changes to the canonical JSON schema that would make generation easier?

This issue will be closed immediately, because there's no need to have it take up space in the list of open issues (there's no call to action). Of course, even after it is closed, please feel free to comment with any additional answers.

If as a result there are any proposed changes to the schema, an appropriate issue can be created for that.

To give us a head start, here is what I know of some languages' generators.
Please forgive me for being greedy and filling in information for tracks that I am unfamiliar with.
Please correct these or add any additional tracks I missed.
In alphabetical order:

# Bash

- https://github.com/guygastineau/bash-track-test-generator

# C#

- https://github.com/exercism/csharp/tree/master/generators
- per-exercise data at https://github.com/exercism/csharp/tree/master/generators/Exercises
    - simple example: leap https://github.com/exercism/csharp/blob/master/generators/Exercises/Generators/Leap.cs
    - allergies deals with multiple `property`: https://github.com/exercism/csharp/blob/master/generators/Exercises/Generators/Allergies.cs
- https://github.com/exercism/csharp/blob/master/generators/Input/CanonicalDataCase.cs#L7 is `IDictionary<string, dynamic>`, supporting values of any type.

# ColdFusion

- https://github.com/exercism/cfml/blob/master/tasks/GenerateTests.cfc ; see `generateInput` for handling of `input`.

# Common Lisp

- https://github.com/exercism/common-lisp/blob/master/src/generate-tests.lisp

# Factor

- https://github.com/catb0t/exercism.factor/blob/master/exercism/autogen-exercises/autogen-exercises.factor

# Go

- An `.meta/gen.go` in each exercise directory defines the structure that the file is expected to have.
    - https://github.com/exercism/go/blob/master/exercises/leap/.meta/gen.go is a simple example for tests that have one property.
    - https://github.com/exercism/go/blob/master/exercises/clock/.meta/gen.go and https://github.com/exercism/go/blob/master/exercises/custom-set/.meta/gen.go examples for tests that have more than one property.
    - Parses `property` first in order to know how to parse the other key/value pairs.
- Common code at https://github.com/exercism/xgo/blob/master/gen/gen.go

# JavaScript

- As I understand it, the deprecated track had a single generator: https://github.com/exercism/DEPRECATED.javascript/blob/master/exercises/custom-set/example-gen.js
- I am not aware of a generator in the new track (formerly the ecmascript track)

# OCaml

- Common code in https://github.com/exercism/ocaml/tree/master/tools/test-generator/src
- a little additional for each exercise in https://github.com/exercism/ocaml/blob/master/tools/test-generator/src/ocaml_special_cases.ml
- templates for each exercise in https://github.com/exercism/ocaml/tree/master/tools/test-generator/templates/ocaml
    - leap is simple, only one property: https://github.com/exercism/ocaml/blob/master/tools/test-generator/templates/ocaml/leap/test.ml
    - run-length-encoding with multiple properties: https://github.com/exercism/ocaml/blob/master/tools/test-generator/templates/ocaml/run-length-encoding/test.ml

# Perl 6

- Template in https://github.com/exercism/perl6/blob/master/templates/test.mustache
- Explanations in https://github.com/exercism/perl6/tree/master/bin
- YAML file for each exercise, then JSON file from x-common simply gets embedded into the test file
    - leap: https://github.com/exercism/perl6/blob/master/exercises/leap/.meta/exercise-data.yaml and https://github.com/exercism/perl6/blob/master/exercises/leap/leap.t
    - clock (multiple property): https://github.com/exercism/perl6/blob/master/exercises/clock/.meta/exercise-data.yaml and https://github.com/exercism/xperl6/blob/master/exercises/clock/clock.t

# Ruby

- A small script in the `bin` directory: https://github.com/exercism/ruby/blob/master/bin/generate
- A library in `lib/generator` providing common-case parsing: https://github.com/exercism/ruby/tree/master/lib/generator
- A `.meta/generator` in each exercise directory containing a `*_case.rb` file. If necessary a custom `test_template.erb` can be provided. Most tests use a common default template
    - Simple example with a custom template: https://github.com/exercism/ruby/blob/master/exercises/leap/.meta/generator/leap_case.rb and https://github.com/exercism/ruby/blob/master/exercises/leap/.meta/generator/test_template.erb
    - Example with more in generator: https://github.com/exercism/ruby/blob/master/exercises/bowling/.meta/generator/bowling_case.rb
    - But note that it does not need a custom template: https://github.com/exercism/ruby/tree/master/exercises/bowling/.meta/generator/test_template.erb is a 404. Most exercises do not need a custom template.

# Rust

- https://github.com/exercism/rust/blob/master/util/exercise/src/cmd/generate.rs

# Scala

- Common code in https://github.com/exercism/scala/tree/master/testgen/src/main/scala/testgen
- https://github.com/exercism/scala/blob/master/testgen/src/main/scala/testgen/CanonicalDataParser.scala#L12 allows any type in the parse result.
- Per-exercise portion in https://github.com/exercism/scala/tree/master/testgen/src/main/scala
    - Simple example: https://github.com/exercism/scala/blob/master/testgen/src/main/scala/BookStoreTestGenerator.scala
    - https://github.com/exercism/scala/blob/master/testgen/src/main/scala/AllergiesTestGenerator.scala deals with multiple properties. The list of inputs is defined per-property.

# Vimscript

- https://github.com/exercism/vimscript/blob/master/lib/generate.vim

**Comment by NobbZ** [comment]
I was pushed to this list today and wanted to add erlang to the list.

> How much additional code must you write to generate tests for each new exercise?

In the good case, there is not much to add, mostly mapping the named arguments from the JSON to an idiomatic order of positional arguments in the function call and spraying syntax generating functions around.

This is at least for the simpler exercises which do not require state keeping.

Of course we have to generate additional boilerplating code, if the test cases actually involve a sequence of calls of which we need to prepare state before and compare state after that.

Also sometimes when the test deals with complex data, we need to map that to more idiomatic ways of data keeping. Erlang doesn't have objects, and the use of maps is not idiomatic for most of those types, such that we have to translate them into something that is called a "record" in erlang speak, basically a tuple with syntactic sugar such that we can use some syntax to refer to fields by names.

> Although all the inputs to an exercise are guaranteed to be under the `input` key, for exercises with more than one input, it's not certain what order they should go in. How do you deal with this?

We manually map them into an idiomatic positional argument schema, as outlined above.

> Are there any possible changes to the canonical JSON schema that would make generation easier?

I have not yet seen those.

**Comment by Stargator** [comment]
Following up on @NobbZ's comment, Dart also has a test generator. It's in the [bin/create_exercise.dart file](https://github.com/exercism/dart/blob/master/bin/create_exercise.dart).

> How much additional code must you write to generate tests for each new exercise?

The test generator does not meet all of our needs. So sometimes it may not accurately define what the expected value's type should be. In those cases it just sees an empty list and doesn't know if that's suppose to be a List of objects, strings, or anything. But that's just changing the type in a handful of cases.

> Although all the inputs to an exercise are guaranteed to be under the input key, for exercises with more than one input, it's not certain what order they should go in. How do you deal with this?

We generally take the first input and make it the first parameter.

> Are there any possible changes to the canonical JSON schema that would make generation easier?

Unsure, as mentioned above specifying the type when the value is an empty collection (list, map, set, etc) could be useful, but types differ from one language to the other and I think that could make it more confusing for the maintainers of the test generators.

**Comment by petertseng** [comment]
Very good. I'll add links, as follows:

# Dart

https://github.com/exercism/dart/blob/master/bin/create_exercise.dart

# Erlang

https://github.com/exercism/erlang/tree/master/testgen - see https://github.com/exercism/erlang/tree/master/testgen/src for per-exercise configuration.

Additionally, I'm changing ColdFusion to CFML because https://github.com/exercism/exercism/issues/3634 . I must have written the original issue back when it was called ColdFusion and not processed the rename when transferring it over to this repo.

**Comment by petertseng** [comment]
Need to add https://github.com/exercism/python/blob/master/bin/generate_tests.py to this list

The discussions repo got reopened so now there are two editable versions of this issue, but I'll decide that this one will be the canonical one going forward since I already spent time on i after discussions repo was closed.

**Comment by yawpitch** [comment]
> Need to add https://github.com/exercism/python/blob/master/bin/generate_tests.py to this list
> 
> The discussions repo got reopened so now there are two editable versions of this issue, but I'll decide that this one will be the canonical one going forward since I already spent time on it after discussions repo was closed.

Added the Python generator + details.
