### ISSUE TITLE
difference-of-squares: hint at formulas

### ISSUE THREAD

**Issue by bitfield** [exercism/problem-specifications#1421]
The 'Difference of Squares' exercise basically involves computing the sum of the first N integers, and the sum of the first N squares. Although there are standard formulas for both of these, I've noticed that students almost never use them. Virtually without exception, every solution I see uses loops.

Clearly, it's not difficult to find the information you need to solve this problem efficiently; as soon as I hint "Might there be a quicker way to calculate this?", the students almost immediately resubmits the solution using the formulas.

It's not that I'd reasonably expect anyone to remember the formulas from high school; we're learning programming here, not math. My point is that no one seems to think of _looking_ for a formula in the first place. Maybe they think it would be cheating?

Perhaps a hint in the README along these lines would help:

> You are not expected to discover an efficient solution to this yourself from first principles; research is allowed, indeed, encouraged. Finding the best algorithm for the problem is a key skill in software engineering.

**Comment by rpottsoh** [comment]
Hints are generated at the track level, in a separate hints.md file and are added to the track's README via the `configlet` app.

**Comment by bitfield** [comment]
It seems rather tiresome to have to open a PR on _every_ language track to add exactly the same hint. Is this not something which applies to the exercise regardless of language?

**Comment by rpottsoh** [comment]
I think you are suggesting a change to [description.md](https://github.com/exercism/problem-specifications/blob/master/exercises/difference-of-squares/description.md).  This is the portion of the README that is typically (doesn't have to be) common between tracks.

**Comment by bitfield** [comment]
That's correct.

**Comment by rpottsoh** [comment]
This sounds like a reasonable change to make to the [description](https://github.com/exercism/problem-specifications/blob/master/exercises/difference-of-squares/description.md) of the exercise.
