### ISSUE TITLE
bracket-push: why does Bracket() return an error?

### ISSUE THREAD

**Issue by bitfield** [exercism/problem-specifications#1422]
The canonical data for this exercise doesn't include any test cases where an error is expected. The tests don't check for one. It's not easy to see where it might be appropriate to return one.

The test case generator on the Go track requires the signature of Bracket to be `func Bracket(input string) (bool, error)`. If there's no sensible error return for this function, I'll change the signature of Bracket() to:

```go
func Bracket(input string) bool
```

**Comment by bitfield** [comment]
Yes, I appreciate that. I'm asking here in case there's a language-agnostic reason why it might be appropriate to return error. If not, then I'll put in a PR against the Go generator.

**Comment by sshine** [comment]
I'm not sure what the language agnostic suggested change to problem specifications is?

Different tracks may handle errors with different type signatures / error handling techniques.

**Comment by bitfield** [comment]
Thanks for the info (or, rather, for confirming that there isn't any). Opened https://github.com/exercism/go/issues/1214 to address this at the track level.
