### ISSUE TITLE
scale-generator: test data inconsistency

### ISSUE THREAD

**Issue by aivanov-oneinc** [exercism/problem-specifications#1425]
I think scale-generator test data has error in part of expected result specification and input interval specification.
In many cases input interval contains 7 chars, that means 7 intervals between 2 notes. SO that means that expected result should contain 8 notes in it. But currently expected result contains only 7 notes.

Example:
```
"intervals": "MMmMMMm"
"expected": [ "G", "A", "B", "C", "D", "E", "F#" ]
```
If we replace each comma with interval char then we get following
```
"intervals": "MMmMMMm"
"expected": [ "G" -M- "A" -M- "B" -m- "C" -M- "D" -M- "E" -M- "F#" ]
```

The last 'm' is not for any note from expected result. Or we need to add G into expected result.

So I think there are 2 options only:
1) add one more note to the expected result list
2) remove last interval char from input interval description

**Comment by bitfield** [comment]
In one sense this is correct as written: a musician would say the scale of C major is C-D-E-F-G-A-B. But the _interval_ pattern MMmMMMm, starting on C, gives you D-E-F-G-A-B-C. 

If you are testing the application of an interval pattern, then the second sequence would seem to be the logical one to look for.

**Comment by aivanov-oneinc** [comment]
That's correct.
But doesn't it mean that expected result should contain the following sequence instead:

> C-D-E-F-G-A-B-C
?

**Comment by bitfield** [comment]
> If you are testing the application of an interval pattern, then the second sequence would seem to be the logical one to look for.

This would be D-C, not C-C.

**Comment by aivanov-oneinc** [comment]
> This would be D-C, not C-C.
In that case, should not be expected result contain a tonic at the end? My concern that the expected result and interval specifications are not consistent.

**Comment by abeger** [comment]
To clarify, I'm not so much a problem author as a "problem formalizer". I just took the disparate test suites from the various tracks and created a consolidated set of tests. All test suites used the format listed in the JSON--the 8th note was not included.

**Comment by aivanov-oneinc** [comment]
Okay, if it is not a problem the best solution I see is to close this ticket.
