### ISSUE TITLE
connect: description is not accurate wrt spaces

### ISSUE THREAD

**Issue by macintux** [exercism/problem-specifications#1435]
> with spaces added for readability, which won't be in the representation passed to your code

In each language I've checked (Erlang, Python, Ruby) that is not accurate: the spaces are included in the test strings.

**Comment by rpottsoh** [comment]
Looks like `(with spaces added for readability, which won't be in the representation passed to your code)` could be stricken from the description.

**Comment by rpottsoh** [comment]
@macintux it looks like there is some interest in seeing an adjustment made to `Connect`'s [description.md](https://github.com/exercism/problem-specifications/blob/master/exercises/connect/description.md) file.  Would you be willing to open a PR to make the prescribed change?  If so, please include a blurb in the first comment that will cause this issue to close when the PR is merged.
