### ISSUE TITLE
space-age: size of numbers

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/problem-specifications#1437]
When working on restructuring the C# track, I found that `space-age` was an ideal candidate for a core exercise that introduces floating-point arithmetic (note: "mathy" exercises are not allowed as core exercises, so `darts` was ruled out). However, I then found out that some of the input values were so large that they didn't fit in C#'s basic `int` type (which max size is `2147483647` (`2^231-1`), which is four bytes). This means that in C#, we will have to introduce not only the floating-point `double` type to the student, but also to bigger numeric types (`long` or `ulong`). For the C# track, this is a problem, as a core exercise should preferrably only introduce a single new concept. By the way, I assume that there will be more tracks for which the default number type has a constrained range similar to the C# one's.

Now I know that is of course very specific to C#, but I was wondering if maybe this exercise is actually teaching two things: working with floating point numbers and working with very large numbers. If people feel there is nothing wrong with the current canonical data, feel free to let me know. I just wanted to put it out there to see if one would be up for modifying `space-age` to use smaller inputs.

Note that these are four input values which value exceeds this maximum value:

`8210123456`
`3210123456`
`3000000000`
`2329871239`

**Comment by rpottsoh** [comment]
I recall when I implemented this exercise on Delphi; grumbling about these large integers for input, and needing to jump up to a larger integer type.  I didn't give it any more thought than that when I implemented it a year ago his month..  Having read your comment @ErikSchierboom I feel like either the inputs should change or config.json needs to be updated.

**Comment by ErikSchierboom** [comment]
> I feel like either the inputs should change or config.json needs to be updated.

I agree. My preference would be to update the inputs, but I was wondering what everyone else's preference would be.

**Comment by sshine** [comment]
I hadn't thought about it. No objection here.
