### ISSUE TITLE
Luhn test cases have mistakes

### ISSUE THREAD

**Issue by bjarnemagnussen** [exercism/problem-specifications#1454]
I think there may be two mistakes in the current Luhn test specifications.

Specifically here:
https://github.com/exercism/problem-specifications/blob/17d157a30f9df4d6e750b90a581ebab4d0c0676f/exercises/luhn/canonical-data.json#L30

and here:
https://github.com/exercism/problem-specifications/blob/17d157a30f9df4d6e750b90a581ebab4d0c0676f/exercises/luhn/canonical-data.json#L62

Both should be invalid and therefore the expected value should be false, or am I mistaken?

**Comment by bjarnemagnussen** [comment]
Right. 

For the test _a simple valid SIN that becomes invalid if reversed_ the value is `59`. By the rule of Luhn the checksum is `5 + (9*2 - 9) = 5 + 9 = 14`. As the name of the test itself suggests, this checksum is not divisible by `10` and therefore invalid, but the `expected` value from the test is set to `true`. Further, a test exists with the same name above but where the value and expected value correspond to each other.

For the test _valid number with an even number of digits_ the value is `095 245 88`. By the rule of Luhn the checksum is `0 + (9*2 - 9) + 5 + (2*2) + 4 + (5*2 - 9) + 8 + (8*2 - 9) = 38`. Even though the name of the test suggests that the checksum should be valid and its `expected` value is also set to `true`, since the checksum of value `38` is not divisible by `10` it should be expected to be invalid.

**Comment by petertseng** [comment]
> 5 + (9*2 - 9) = 5 + 9 = 14

https://github.com/exercism/problem-specifications/blob/master/exercises/luhn/description.md says we double every second digit starting from the right. Therefore we must double 5, not 9. The sum is (5 * 2 - 9) + 9 = 10.

> 0 + (9*2 - 9) + 5 + (2*2) + 4 + (5*2 - 9) + 8 + (8*2 - 9) = 38

The sum is (0 * 2) + 9 + (5 * 2 - 9) + 2 + (4 * 2) + 5 + (8 * 2 - 9) + 8 = 40

**Comment by petertseng** [comment]
> `5 + (9*2 - 9) = 5 + 9 = 14`

https://github.com/exercism/problem-specifications/blob/master/exercises/luhn/description.md says we double every second digit starting from the right. Therefore we must double 5, not 9. The sum is `(5 * 2 - 9) + 9 = 10`.

> `0 + (9*2 - 9) + 5 + (2*2) + 4 + (5*2 - 9) + 8 + (8*2 - 9) = 38`

The sum is `(0 * 2) + 9 + (5 * 2 - 9) + 2 + (4 * 2) + 5 + (8 * 2 - 9) + 8 = 40`

**Comment by bitfield** [comment]
I get students making the same mistake all the time. Maybe we need to emphasise the 'every second digit _from the right_' part, because that's what they seem to be missing.

**Comment by F3PiX** [comment]
I mentored a lot of Ruby Luhns lately, and none of them missed this. If there are tracks where this happens a lot, they could add an extra hint in the hint.md? That's a perfect place for adding track specific instructions. Especially because the mistake made could depend on the position in the track; in Ruby people have already done the majority of the track before they get Luhn, but I know of other tracks that has it way earlier. 
I'm a big fan of extra instructions in hint.md, and keep the Readme (and the canonical data for that matter) as generic and neutral as possible.

**Comment by bitfield** [comment]
I agree with you, but there's nothing track-specific about this. Some people just misread the instructions and assume you double every second digit from the left.

**Comment by sbromberger** [comment]
Having just been bitten by this, I confess it was entirely my mistake: I had overlooked the "from the right". Bolding or otherwise emphasizing that requirement might make things clearer.
