### ISSUE TITLE
Simplifying HighScores 

### ISSUE THREAD

**Issue by F3PiX** [exercism/problem-specifications#1456]
In the Ruby track, High Scores works great as an easy exercise for students, but the `report` method makes it a pain to mentor. We want to simplify it such that it doesn't need the giant if/else statement/extracted method/unreadable interpolation anymore. 

Is this interesting for more tracks? In that case, we can change the canonical data.  If it's only an issue in Ruby, we'll change it only there. 

It's in ~@exercism/dart~ , @exercism/csharp @exercism/python @exercism/scala @exercism/delphi @exercism/javascript @exercism/fsharp ?
(cc @pgaspar)

**Comment by SleeplessByte** [comment]
Not core (yet) for us (js/the), but makes sense. I really like the simplicity of space-age and I think it'll helpt this as well so you can focus on the data structure instead of the formatting.

**Comment by ErikSchierboom** [comment]
I'm also in favor of removing the report cases, for the same reasons as @SleeplessByte: it allows focusing on the data structure. It will also make reviewing/auto-approving easier.

**Comment by pgaspar** [comment]
This sounds great to me :+1: I'm ok with either removing the method entirely or finding a simpler replacement.

**Comment by F3PiX** [comment]
Thanks all! @pgaspar we're going to tackle this, yes?

**Comment by F3PiX** [comment]
Heads up: there's a PR up to remove the method, meaning the exercise focusses on array query methods. https://github.com/exercism/problem-specifications/pull/1459
