### ISSUE TITLE
Make word-count example more explicit to student

### ISSUE THREAD

**Issue by gabriel376** [exercism/problem-specifications#1461]
According to issue exercism/rust#788 by @atil, the exercise [word-count](https://github.com/exercism/problem-specifications/tree/master/exercises/word-count) could have more explicit examples (see also #869).

The only example available to student is: `"olly olly in come free"`

```text
olly: 2
in: 1
come: 1
free: 1
```
which may cause the impression that the only delimiter is whitespace character.

However, the [canonical-data](https://github.com/exercism/problem-specifications/blob/master/exercises/word-count/canonical-data.json) has cases like line-break delimiters (`one,\ntwo,\nthree`) and exclusion of special characters (`car: carpet as java: javascript!!&@$%^&`).

The idea is to show more examples (or to show a not so obvious one) to student in problem statement about what is the expected output of the problem. We don't have to put all examples (which should be in the test cases itself) and I agree that README is just a high-level description (see #66), but we can make it more explicit.

**Comment by yawpitch** [comment]
I've modified the example in #1542 such that a single example should handle most -- if not all -- of the edge cases. Along with the improved definition of a _word_ that may be sufficient to close this one once merged.

**Comment by yawpitch** [comment]
Closed by merge of #1542.

**Comment by gabriel376** [comment]
Thank you!
