### ISSUE TITLE
list-ops: division operator is ambiguous

### ISSUE THREAD

**Issue by juhlig** [exercism/problem-specifications#1467]
https://github.com/exercism/problem-specifications/blob/69395c45cde06c3e0206d4d1e17958a8577dc1bd/exercises/list-ops/canonical-data.json#L161-L170
https://github.com/exercism/problem-specifications/blob/69395c45cde06c3e0206d4d1e17958a8577dc1bd/exercises/list-ops/canonical-data.json#L196-L205

The two cases instruct the test implementation to apply the division operator `/` to the two arguments of the function used for folding.

This operator is ambiguous, depending on language and circumstances. There are languages which always do floating-point division with `/` and have a separate operator for integer division (eg `div` in `Erlang`), others do integer division if both operands are integers and float division only if at least one operand is a float, etc.

The current test cases in question assume integer division, but this is not obvious, only if you (as a human) read the test arguments and expected outcome carefully. For a test generator on the other hand, it is quite difficult.

As finding a language-agnostic way to explicitly specify _integer_ division would pose rather difficult, I suggest to alter the test cases to use another direction-dependent but unambiguous operation instead,  like `-`.

**Comment by NobbZ** [comment]
I've always read this pretty much in the C-sense…

We get 2 integers in, so we get an integer out.

I never thought of reading it the erlang or elixir way… As long as we get numbers in, we get a float out.

If though we try it the erlang (`x div y`), elixir (`div(x, y)`) or haskell (``x `div` y``) way, I fear it would not be understood by other maintainers on the first glance, as its not what they are used to.

We also might meet some esotherical language, that does not even allow for division directly.

In my opinion we should make the tests self contained:

```json
 { 
   "description": "direction dependent function applied to non-empty list", 
   "property": "foldl", 
   "input": { 
     "list": [2, 5], 
     "initial": [], 
     "function": "(x, y) -> cons(x, y)" 
   }, 
   "expected": [5, 2]
 },
 { 
   "description": "direction dependent function applied to non-empty list", 
   "property": "foldr", 
   "input": { 
     "list": [2, 5], 
     "initial": [], 
     "function": "(x, y) -> cons(x, y)" 
   }, 
   "expected": [2, 5] 
 }
```

Where `cons/2` is the list constructor. Haskell knows it as `(:)`, erlang/elixir as `[_|_]`, other languages will probably just call a function. And the nice thing is, the function stays in the actual domain of the testsuite.

**Comment by juhlig** [comment]
> I never thought of reading it the erlang or elixir way… As long as we get numbers in, we get a float out.

Python appears to have an explicit integer-division operator as well, `//`, and the `/` operator seems to work differently among python versions and even among same versions in different environments (I'm not a python person, so can only go from what I have read).

> If though we try it the erlang (`x div y`), elixir (`div(x, y)`) or haskell (`` x `div` y ``) way, I fear it would not be understood by other maintainers on the first glance, as its not what they are used to.

That's basically what I said, finding a way to express _integer division_ that is understood easily among all languages is probably impossible. Subtraction would be a better choice, since it is also direction-dependent in the sense that `2-5` is different from `5-2` (which is what the test cases in question are pretty much all about), but not type-dependent (at least not in any language I know of).

> In my opinion we should make the tests self contained:
> [...]
> Where `cons/2` is the list constructor. Haskell knows it as `(:)`, erlang/elixir as `[_|_]`, other languages will probably just call a function. And the nice thing is, the function stays in the actual domain of the testsuite.

I'm not sure if `cons` would be better understood than `div` by languages that don't employ lists as heavily as Haskell/Erlang/Elixir etc do. But other than with `div` or `/`, comparing the input and expected output pretty much explains what it does.

**Comment by NobbZ** [comment]
> [`-` is ] not type-dependent (at least not in any language I know of).

The first that comes to my mind is C… If one argument is float-y, the result is as well.

**Comment by juhlig** [comment]
> > [`-` is ] not type-dependent (at least not in any language I know of).
> 
> The first that comes to my mind is C… If one argument is float-y, the result is as well.

As concerns the result _type_ yes. The result _value_ is the same:
```
5 - 2 -> 3
5 - 2.0 -> 3.0
```
not so with division:
```
5 / 2 -> 2
5 / 2.0 -> 2.5
```

**Comment by juhlig** [comment]
Yes, but that's not the point. The test cases provide only integers, never floats. The result, however, is determined by how a language uses the division operator, ie if it does an integer or float division and under which circumstances. So this is a rather language dependent part. With `-`, the outcome is always the same _value_ no matter what the language (_type_ may differ), but with `/` the outcome depends on the implementing language. And the result the test expects is bound to how a language handles the `/` operator, you know what I mean?

**Comment by NobbZ** [comment]
Yes, I think I do.

**Comment by juhlig** [comment]
:)

Anyway, I think making the tests self-contained the way you suggested is a good (better) way, too. What `cons` is supposed to do could be explained in comments. I'm just not sure what it'd mean for existing test generators. Those that already do a translation of `(x, y) -> x / y` to the respective tracks language can reasonably be assumed to do just the same with `-` instead of `/` without changes, but with an artificial construct like `cons` it is probably a different story that needs some interaction.

**Comment by petertseng** [comment]
https://github.com/exercism/problem-specifications/pull/1746 makes unambiguous:

* What sort of division is expected (integer or rational)
* which argument is the accumulated value and which is an element from the list
