### ISSUE TITLE
hamming: Empty strand errors don't make sense

### ISSUE THREAD

**Issue by mienaikage** [exercism/problem-specifications#1521]
canonical-data requires an error message stating `left/right strand must not be empty`, however this doesn't make sense due to the following:
1. There is an existing test case with both strands being empty as valid.
2. There is an existing test case for returning an error if the strands differ in length.

The error only applies if your input is already erroneous.

**Comment by sshine** [comment]
I've responded to this discussion in #1522.

**Comment by SleeplessByte** [comment]
In other words: they do make sense in some languages, https://github.com/exercism/haskell/pull/796 including.
