### ISSUE TITLE
resistor-color-duo description leads implementation

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/problem-specifications#1524]
https://github.com/exercism/website-copy/pull/1040#issuecomment-497247889, originally by @kotp:

> It is unfortunate perhaps that the instructions show the listing in a form that is extremely hinting at a key: value pair complete with the colon. It may drive thinking that we want to work with hashes on that alone. (__Edit__ ) __Even though__ I think it works better as a Hash, visually, and even to work with.

I agree with @kotp. This may be solved by changing the description in problem specifications. A list of values would be far better, methinks.

**Comment by F3PiX** [comment]
Here's the description: 
https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color-duo/description.md

**Comment by SleeplessByte** [comment]
We probably want the same change made to `resistor-color`

**Comment by F3PiX** [comment]
Do you mind if I close this? I added it to #1471.
