### ISSUE TITLE
anagram: improve description to define what is an anagram

### ISSUE THREAD

**Issue by joaomarcosgris** [exercism/problem-specifications#1528]
Similar exercises provide the definition, like the Pangram and Isogram one. But in Anagram, there's no definition at all. If you want to see a more in-depth discussion, please see [https://github.com/exercism/ruby/issues/965](https://github.com/exercism/ruby/issues/965)

**Comment by SleeplessByte** [comment]
Yes, this seems like a very reasonable change. 

Would you like to submit a PR to add this in the style of Pangram and Isogram exercises?

**Comment by joaomarcosgris** [comment]
Thanks. Submitted :)
