### ISSUE TITLE
Proposal: Add canonical data "nothingness" field

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/problem-specifications#1545]
I don't know _how_ to call this exactly.

`JSON` does not distinguish between `nothing` and `empty` (`undefined` and `null` in JavaScript). I propose a new field that is a string value which describes how `null` may be interpreted. This would for example apply to `twoFer`'s test which doesn't pass a value.

```
'empty' | 'absent'
```

- `'empty'`: interpret `null` as if the input is given but empty. Use whatever idiomatic value in the language represents empty. For example, even though `Kotlin` as `null`, it might be better, in the context of the exercise, to use a sealed data type with a `Data(val name: string)` and `NoData` implementation. In JavaScript this would be `''` or `null`.

- `'absent'`: interpret `null` as if there is no input. Use whatever idiomatic value in the language represents optional values or something that deals with absent data. For example, in C# there are optional parameters, same as in JavaScript and Kotlin. In JavaScript this could also interpret the value as `undefined`.

What I'm really trying to solve for is the fact that `null` doesn't describe the _intent_.

**Comment by bencoman** [comment]
My knee-jerk reaction is "now we've cracked the seal on adding knew keys, lets **not** get carried away and quickly accumulate a large amount of them" - but that said, I'm willing to take the discussion on its merits.  

I wanted to understand the background better and the "JSON1" & "JSON2" cases were interesting here...
https://stackoverflow.com/questions/21120999/representing-null-in-json

So we might have...??
```
    {
      "description": "no name given",
      "property": "twoFer",
      "input": {
        "name": {}
      },
      "expected": "One for you, one for me."
    },
```

**Comment by SleeplessByte** [comment]
> let's not get carried away and quickly accumulate a large amount of them

I agree, which is why this is a discussion 👍 

```
"input": {
  "name": {}
},
```

This, in my generator and understand would be to pass:

```javascript
twoFer({})
```

A valid solution, perhaps, could be:

```json
 {
    "description": "no name given",
    "property": "twoFer",
    "input": {},
    "expected": "One for you, one for me."
},
``` 

This, in my generator and understand would be to pass:

```javascript
twoFer()
```

I think in every way, this is much better than adding a new key, or using `null` to denote "absence".

**Comment by cmccandless** [comment]
What about languages that support neither optional parameters nor overloads (I mention this without a specific example of such a language to offer)?

**Comment by NobbZ** [comment]
Those languages are free to not implement `two-fer` at all.

Haskell did use a `Maybe` in `two-fer`s predecessor. It was a very clumsy interface and absolutely not idiomatic.

**Comment by sshine** [comment]
Perl 5 has `''`, `0` and `undef` that are falsy, and either one is applicable in different contexts (`!$x` gives `1` and `!!$x` gives `''` when `$x` is falsy, `return;` gives `undef` in scalar context, etc.). I would rather have that test generators for individual exercises choose a meaningful way to deserialize JSON `null` in whatever way that is most applicable. Hopefully the same function we ask a student to implement does not sometimes return `undefined` and sometimes `null`?

**Comment by ErikSchierboom** [comment]
> I think in every way, this is much better than adding a new key, or using null to denote "absence".

I like this option, just not have the `name` parameter at all in the input data for the case where it should not be supplied.

Personally, I don't think adding this field provides much benefit. For these edge cases, I think a little customization of the test generator makes more sense than adding a new field that is rarely used.

**Comment by SaschaMann** [comment]
> For these edge cases, I think a little customization of the test generator makes more sense than adding a new field that is rarely used.

It might not even need exercises-specific customization if not having the parameter in the input if it shouldn't be supplied is the standard way to handle this across all exercises. Perhaps it should be documented somewhere, though.

Since this is already a way to represent the difference between "empty" and "absent", I don't think a new field is needed.

**Comment by SleeplessByte** [comment]
I'm happy that we seem to have multiple people liking the idea of _removing the key_ in case of absence (@NobbZ this should make you happy). I will open a PR that takes care of this, across exercises if there are more than one, and we can discuss it further there.

If that PR is rejected in the end, we can re-open this!

Thank you everyone for your time :heart:
