### ISSUE TITLE
Resistor color: no task description

### ISSUE THREAD

**Issue by okeegan** [exercism/problem-specifications#1546]
The explanation for how resistor colors (#1466) work is fine, but in terms of what the task actually is – there's not much there.

```Resistors have color coded bands, where each color maps to a number. The first 2 bands of a resistor have a simple encoding scheme: each color maps to a single number.

These colors are encoded as follows:

Black: 0
Brown: 1
Red: 2
Orange: 3
Yellow: 4
Green: 5
Blue: 6
Violet: 7
Grey: 8
White: 9
Mnemonics map the colors to the numbers, that, when stored as an array, happen to map to their index in the array: Better Be Right Or Your Great Big Values Go Wrong.

More information on the color encoding of resistors can be found in the Electronic color code Wikipedia article

```

 I propose the addition of a line that describes the expected input and output for this exercise. Maybe something like: 

`"Write a function that takes a band color as input and outputs the associated number."`

**Comment by yawpitch** [comment]
Hi @okeegan, that's a sensible addition and I'd be happy to accept a pull request, though to make it language/paradigm agnostic and reflect the fact that the canonical data requires more than one function maybe something like `"Create the means to list the different band colors and to look up the numerical value associated with a particular band color."`?

**Comment by rpottsoh** [comment]
Color band instead of band color.  Otherwise I think that is good.

**Comment by okeegan** [comment]
In my opinion as a mere noob,  "Create the means to _list the different band colors_..." is implicit in the second half, but otherwise your suggestion rocks @yawpitch.

Also, noted @rpottsoh! 

PR is #1548.
