### ISSUE TITLE
anagram problem description needs more detail

### ISSUE THREAD

**Issue by BartMassey** [exercism/problem-specifications#1556]
The description of `anagram` should be revised to make clear that (1) anagrams are case-insensitive, and (2) a word is never its own anagram. See issue #1528 for the initial expansion of the `anagram` description, and issues exercism/rust#86 and exercism/rust#690 for discussion of this problem.

**Comment by ErikSchierboom** [comment]
@BartMassey Good suggestion! Are you interested in submitting a PR to update [the description](https://github.com/exercism/problem-specifications/blob/main/exercises/anagram/description.md)?

**Comment by BartMassey** [comment]
Here's what I have so far. I would prefer to just say "lowercase Unicode characters (scalars)" and forget the ASCII and case-equivalence, but this is what is currently tested I think. The reading level is too high, but it's hard to be short and clear otherwise. Suggestions welcome.

> An anagram is a rearrangement of letters to form a new word.
> Given a target word and a set of candidate words, the
> anagram set is the subset of the candidates that can be
> produced by rearranging the letters of the target. A word is
> not its own anagram.
> 
> For this exercise, the target and candidates are words in
> ASCII alphabetic characters (`A`-`Z` and `a`-`z`). Lowercase
> and uppercase characters are considered equivalent: for
> example, "PoTS" is considered an anagram of "sTOp". The
> candidate set is represented as an unordered list. The
> anagram set must be the sublist of all anagrams in the
> candidate set (in the same order).
> 
> Given the target `"stone"` and candidates `"stone"`,
> `"tones"`, `"banana"`, `"tons"`, `"notes"`, `"Eston"`, the
> program should return `"tones"`, `"notes"`, `"Eston"`.

**Comment by BartMassey** [comment]
I'll be happy to put in a PR if this looks good to people, of course.

**Comment by ErikSchierboom** [comment]
That looks good to me! A PR would be much appreciated.
