### ISSUE TITLE
inadequate tests for python darts 

### ISSUE THREAD

**Issue by grwkremilek** [exercism/problem-specifications#1592]
I came up with this solution which passed all the tests:

```
def score(x, y):

    if abs(x) + abs(y) <= 1:

        return 10

    elif 1 < abs(x) + abs(y) <= 5:

        return 5

    elif 5 < abs(x) + abs(y) <= 10:

       return 1

    return 0
```

nevertheless as someone commented, it does not work for x=0.8, y=0.5

"0.8 + 0.5 = 1.3, which is greater than 1 (so you return 5). But sqrt(0.8^2 + 0.5^2) = 0.94, a radius within the innermost circle (so you should return 10)."

**Comment by sshine** [comment]
@yawpitch: You have a point. I've moved this to problem-specifications and put it on hold cf. #1560.

**Comment by petertseng** [comment]
Already done in https://github.com/exercism/problem-specifications/pull/1488. 

I understand that the tests were changed in https://github.com/exercism/problem-specifications/pull/1530, but that's fine because there still are cases that absolute addition will get the wrong answer on:

```
== anti-verify abs score ==
6. Just within the inner circle: Got 5 instead of 10
8. Just within the middle circle: Got 1 instead of 5
10. Just within the outer circle: Got 0 instead of 1
```

**Comment by petertseng** [comment]
Where `abs` is the implementation: `['abs', ->(x, y, _) { CIRCLES.find { |c| x.abs + y.abs <= c[:radius] } }],`
