### ISSUE TITLE
connect: sample data contains boards with different length and height

### ISSUE THREAD

**Issue by tr808axm** [exercism/problem-specifications#1597]
In the [description of the connect exercise](https://github.com/exercism/problem-specifications/blob/master/exercises/connect/description.md) the text says that the game board is a rhombus, meaning that it has the same amount of lines and columns. However, the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/connect/canonical-data.json) contains examples that have a width of 4 and a height of 5. This is present in the following cases:
- [`illegal diagonal does not make a winner`](https://github.com/exercism/problem-specifications/blob/master/exercises/connect/canonical-data.json#L53)
- [`nobody wins crossing adjacent angles`](https://github.com/exercism/problem-specifications/blob/master/exercises/connect/canonical-data.json#L67)
- [`X wins crossing from left to right`](https://github.com/exercism/problem-specifications/blob/master/exercises/connect/canonical-data.json#L81)
- [`O wins crossing from top to bottom`](https://github.com/exercism/problem-specifications/blob/master/exercises/connect/canonical-data.json#L95)

I think it is either necessary to remove the rhombus wording from the readme and clarify that the amount of lines and columns can be different (games would not be fair in that case) **or** to change the sample data to a square board.

If this change is approved, I would like to work on it.

**Comment by tr808axm** [comment]
By the way, I would like to work on this issue if the change is approved.

**Comment by petertseng** [comment]
I reviewed what I thought about this in https://github.com/exercism/problem-specifications/issues/212 . My thought will remain the same - I find either suggestion acceptable, so would leave it to the choice of the person who will work on it.

It may in fact be useful to keep some games unfair so as to ensure that the code doesn't make any assumptions that it shouldn't. On the other hand, some would argue that the code is justified in making assumptions (height = width) if its scope is explicitly limited to only fair games. So this is why I will find either acceptable.

**Comment by yawpitch** [comment]
We'd be happy to see a PR that replaces "rhombus" with "parallelogram" in the `description.md` file; we've already modified that file to indicate that the game need not necessarily be fair, so I do not believe we need to specifically clarify that the dimensions can vary from a rhombus.

**Comment by tr808axm** [comment]
Alright, I will create a PR that replaces rhombus with parallelogram. I also think that this is the right solution because it forces you to think about the differences between the different dimensions.
