### ISSUE TITLE
satellite: question on purpose of inputs

### ISSUE THREAD

**Issue by wolf99** [exercism/problem-specifications#1606]
In the exercise `satellite`, I do not understand what the intended purpose of having two inputs of the same data is.

Maybe I'm missing something; if the client (the satellite) knows the order the input will be delivered in, and the tree structure obeys the alphabetical rules for the tree construction shown in the example in the readme, then why does the client need a second differently ordered input of the same information?

Is there some implication I have not seen?

**Comment by petertseng** [comment]
But I wasn't able to see any such alphabetical ordering. I look at the inputs in the https://github.com/exercism/problem-specifications/blob/master/exercises/satellite/description.md

```
For example the pre-order traversal of this tree is [a, i, x, f, r]. 
The in-order traversal of this tree is [i, a, f, x, r]
```

Neither of them `[a, i, x, f, r]` nor `[i, a, f, x, r]` were in alphabetical order. I am sure I simply misunderstood what you means, so please do correct me on that.

The reason there are two inputs is that if there were only one input, it would not specify a unique tree.

For example, if I were asked to give a tree with pre-order traversal `[a, i, x, f, r]`, here are two possible trees with this pre-order traversal:

```
  a
 / \ 
i   x   
   / \ 
  f   r   
```

```
    a
   / \
  i   f
 /   /
x   r
```

What about if I were asked to give a tree with in-order traversal `[i, a, f, x, r]` ? Here are two such trees.

```
  a
 / \ 
i   x   
   / \ 
  f   r   
```

```
    x
   / \
  a   r
 / \
i   f
```

Therefore, to be able to designate just a single tree, I must give *both* the pre-order and in-order traversals. Just giving one of the two is not enough.

**Comment by wolf99** [comment]
Thanks @petertseng !
