### ISSUE TITLE
Ceterum censeo TOPICS.txt esse delendam

### ISSUE THREAD

**Issue by workingjubilee** [exercism/problem-specifications#1618]
After the creation of TOPICS.txt and an ongoing effort to standardize the rest of Exercism around it, whether or not that was part of the intent of the list, creating considerable rancor and prompting the state of affairs in #1560 to arise, it has become obvious that it is... problematic.

I have offered #1617 as a possible solution. Nonetheless, I only did so because I believe that offering such as a PR would be a mere extrapolation from the project's original tendencies. That should not be viewed as an endorsement of those tendencies per se. I would respectfully differ, and propose that the actual problem is visible inter-track standards that are present for non-technical reasons.

In essence, it is far more practical, and easier, to agree on some common tooling, but things that move in the more aesthetic or philosophical directions inspire... conflict. Thus, I propose the utter and total removal of a primary source of the conflict:

**Destroy TOPICS.txt**

**Comment by yawpitch** [comment]
I'm not sure Cato would agree that TOPICS.txt rises to the threat of Carthage, but I'm open to being badgered into compliance.

**Comment by petertseng** [comment]
(I didn't understand the title. It must be some reference that I did not get exposed to when growing up. But it is okay, I will just comment on the body of the proposal.)

When evaluating this proposal, it would be useful to consider the question "What benefits does TOPICS.txt currently provide us?" Then, armed with such a list of benefits, it would then be useful to further consider "For each benefit B, is benefit B best provided by TOPICS.txt, or is there a better way to gain benefit B?

For example, one might say that the words written in https://github.com/exercism/problem-specifications/pull/1617/files#diff-6f5ed6019361c535ef34180c89c2417bR19-R21 are one such benefit:

> between tracks it is desirable to provide associative context, so
> that someone from another programming language can use concepts they
> already have learned, where applicable, to understand the language

To try to promote this sort of context, a track maintainer might ask, "for a given exercise E, let's take a look at what topics other tracks have assigned to exercise E?"

This comment must not be interpreted as support or opposition of the proposal of removing TOPICS.txt.

**Comment by yawpitch** [comment]
The title is a re-purposed quote from Cato the Elder, who in the run up to the Third Punic War consistently ended a speech on any topic with some variant of “I am resolved that Carthage must be destroyed”.

We can table this and further discussion of destruction / modification of TOPICS.txt, as that all falls within the purview of work already underway that follows from exercism/exercism#5088.

**Comment by iHiD** [comment]
@workingjubilee Thanks for your (albeit slightly esotoric 😄) post! There is a working group currently looking at this and we expect to open the whole thing up for wider discussion in the next couple of weeks. We've appreciate your thoughts on our working-conclusions then :)
