### ISSUE TITLE
new exercise prime-factors Julia

### ISSUE THREAD

**Issue by NandVinchhi** [exercism/problem-specifications#1621]
This is the Solution to the prime-factors exercise of the Julia Track. This code is for the purpose of Google Code In. 
[prime-factors.zip](https://github.com/exercism/problem-specifications/files/3927782/prime-factors.zip)

**Comment by yawpitch** [comment]
This is not the correct location for Julia track specific files, you'd want to fork the [Julia repository](https://github.com/exercism/julia) and open a pull request there from your fork, rather than attach a .zip file to an issue.

Closing this Issue as it's in the wrong repository.
