### ISSUE TITLE
`grade-school` canonical data does not correspond to the exercise description

### ISSUE THREAD

**Issue by eparovyshnaya** [exercism/problem-specifications#1623]
There is a discrepancy between test cases described in  the canonical data and the exercise description. 

Explaining the general roster query, [description](https://github.com/exercism/problem-specifications/blob/master/exercises/grade-school/description.md) mentions a *map* structure to be returned as a result:

> "Who all is enrolled in school right now?"
> "Grade 1: Anna, Barb, and Charlie. 
> Grade 2: Alex, Peter, and Zoe. 
> Grade 3…"

But [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/grade-school/canonical-data.json) prescribes to only return names, like here: 
```json
{
  "description": "Student names with grades are displayed in the same sorted roster",
  "property": "roster",
  "input": {
    "students": [["Peter", 2], ["Anna", 1], ["Barb", 1], ["Zoe", 2], ["Alex", 2], ["Jim", 3], ["Charlie", 1]]
  },
  "expected": ["Anna", "Barb", "Charlie", "Alex", "Peter", "Zoe", "Jim"]
}
```

According to the exercise description it could be more appropriate to require *map* here as well: 
```json
"expected": [[1, ["Anna", "Barb", "Charlie"]], [2, ["Alex", "Peter", "Zoe"]], [3, ["Jim"]]]
```

**Comment by yawpitch** [comment]
The expectation is given a couple lines above in the description:

> Get a sorted list of all students in all grades. 

It then goes on to explain the — non-trivial — sort order of that list, but the expectation is still a flat list. The canonical data then is correct as is.

The “human readable” answer described on the line you quoted isn’t meant to imply how the program would respond but how a human would respond, so no map structure is actually implied... that said we could update the description to better reflect the expectation of the canonical data.

**Comment by eparovyshnaya** [comment]
@yawpitch, thank ou for explanation. It is not obvious, indeed. It appears that Kotlin track implementors got the description literally as requirements specification. I'm reworking it at the moment. 

Can you please have a look at the descrition alternation proposal in #1624?
