### ISSUE TITLE
unimplemented tasks "bank-account" solution

### ISSUE THREAD

**Issue by python-admin** [exercism/problem-specifications#1625]
[banc.txt](https://github.com/exercism/problem-specifications/files/3938541/banc.txt)

**Comment by yawpitch** [comment]
At a quick glance this appears to be Julia code (your username is confusing)... I believe you’re trying to commit to the [Julia repository](https://github.com/exercism/julia) and not here... this is only the repo for language-agnostic data for each exercise.

I’d suggest starting by reading the Julia [Contributing Guide](https://github.com/exercism/julia/blob/master/CONTRIBUTING.md) for how to proceed over there.

Closing this here as it’s not the appropriate repo.
