### ISSUE TITLE
Inappropriate language. Use neutral & child friendly test copy.

### ISSUE THREAD

**Issue by jesserwright** [exercism/problem-specifications#1630]
https://github.com/exercism/rust/blob/da24f9af56e1d52196562dedcf021f781e9d873e/exercises/bob/tests/bob.rs#L58

"Let's go make out behind the gym!" and the use of the word "HELL" I consider to be inappropriate for audiences of all ages. Let's keep it family friendly.

Please use friendly and neutral tests. Thanks :)

[canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json)

**Comment by SaschaMann** [comment]
I'm not sure how a forceful question can be friendly and neutral?

**Comment by rpottsoh** [comment]
Old:
```json
    {
      "description": "talking forcefully",
      "property": "response",
      "input": {
        "heyBob": "Let's go make out behind the gym!"
      },
      "expected": "Whatever."
    },
```
Proposed New:
```
    {
      "description": "talking forcefully",
      "property": "response",
      "input": {
        "heyBob": "You're about to miss your chance for free ice cream!"
      },
      "expected": "Whatever."
    },
```
Old:
```
    {
      "description": "forceful question",
      "property": "response",
      "input": {
        "heyBob": "WHAT THE HELL WERE YOU THINKING?"
      },
      "expected": "Calm down, I know what I'm doing!"
    },
```
Proposed New:
```
    {
      "description": "forceful question",
      "property": "response",
      "input": {
        "heyBob": "WHAT IN THE WIDE WORLD OF SPORTS IS GOING ON AROUND HERE?"
      },
      "expected": "Calm down, I know what I'm doing!"
    },
```

**Comment by SaschaMann** [comment]
I have no idea what "what in the wide world of sports" is meant to mean, nor have I ever heard of it before. If we're gonna make the language friendlier, could we perhaps stick to globally understood expressions rather than what I assume is an american saying or some kind of in-joke? "What the hell"  works great for this and doesn't contain swear words (unlike "what the fuck") but if that's inappropriate for whatever reason, perhaps there are other alternatives to it that aren't only understood by a certain group of english speakers.

**Comment by iHiD** [comment]
@jesserwright Thanks for bringing this up. We'll get it changed.

@rpottsoh. Thanks. Let's go with the first as you suggested, and for the second something shorter, maybe this?
```
`"heyBob": "WHAT IS GOING ON AROUND HERE?"`
```

**Comment by iHiD** [comment]
Sidenote: @SaschaMann Agree entirely with keeping things simple and globally friendly. Also, "Hell" would be considered swearing in some cultures (there is zero chance I'd say that around my parents for example).

**Comment by SaschaMann** [comment]
That doesn't sound forceful to me. "What is going on around here?" is used in many contexts where it's not forceful, the caps just makes it seem loud, but not necessarily forceful. Maybe "WHAT ON EARTH...?"?

**Comment by iHiD** [comment]
@SaschaMann Thanks. Updated it again.

**Comment by iHiD** [comment]
@rpottsoh You want to execute this? I'll ping the #maintainers channel on Slack and ask people to update when it's on master.

**Comment by SaschaMann** [comment]
> Sidenote: @SaschaMann Agree entirely with keeping things simple and globally friendly. 

On that note, perhaps change the DMV cases, too, while we're at it?

**Comment by iHiD** [comment]
Yes. Can we change DMV to Dentist (I have no idea what DMV is but it sounds like "Dentist" fits to replace it)?

**Comment by yawpitch** [comment]
Department of Motor Vehicles... common name in the various States for the automotive licensing authority, known outside the States, if at all, largely from the fact that it’s the name Hollywood uses for a hellishly Draconian beuracracy staffed entirely by people who want to do the least possible with any movement.

So kind of like dentists.

**Comment by iHiD** [comment]
Thanks @yawpitch! I found that as the first acronym online but had no idea why that would be a bad thing! :)

**Comment by sshine** [comment]
> `"You're about to miss your chance for free ice cream!"`
>
> `"WHAT IN THE WIDE WORLD OF SPORTS IS GOING ON AROUND HERE?"`

I'm intolerant to lactose and attempts to excuse profanity, so these suggestions offend me.

Why not `"Hi there!"` and `"WHAT'S GOING ON?"`

**Comment by yawpitch** [comment]
> Thanks @yawpitch! I found that as the first acronym online but had no idea why that would be a bad thing! :)

Watch the sloth scene in Zootopia at half speed, you’re looking at the California DMV in action.

**Comment by iHiD** [comment]
@sshine Even better. I've updated my post again :)

**Comment by iHiD** [comment]
If anyone else wants to PR this before @rpottsoh gets to it, then feel free. I don't understand this repo so I'm not going to though :)

**Comment by SaschaMann** [comment]
Neither of those sound forceful, they're just greetings (the latter in a louder environment).

**Comment by rpottsoh** [comment]
Just reading through the latest posts....    Is there a consensus?  Obviously my ideas are not liked (I am not offended in the slightest, just spit balling).

**Comment by rpottsoh** [comment]
`"Hi there!"` and `"WHAT'S GOING ON?` seem to be the favored replacements.

**Comment by rpottsoh** [comment]
> I have no idea what "what in the wide world of sports" is meant to mean, nor have I ever heard it before. 

Actor Slim Pickens from the movie Blazing Saddles.  But that doesn't really matter I understand your point.

**Comment by coriolinus** [comment]
> Neither of those sound forceful

@SaschaMann Forcefulness is largely a cultural artifact. What would be forceful, but polite, speech in the context of, say, the Army, can come across as offensively impolite in another context which we might call California. I've gotten in trouble for that in the past. 

Luckily, we don't expect students to perform sentiment analysis on the text, just pick up on the punctuation and capitalization. I think we can safely discard the question of whether the proposed text sounds forceful in all contexts. 

@rpottsoh It appears to me that there is general consensus in favor of the options you've identified.

**Comment by SaschaMann** [comment]
The DMV change is still missing.

**Comment by rpottsoh** [comment]
You are correct!  I was fixated on the two primary cases.  I'll open another PR.
