### ISSUE TITLE
Protein Translation: task description, "codon to amino acid" table improvement

### ISSUE THREAD

**Issue by b10s** [exercism/problem-specifications#1639]
I'm not sure but seems in the "codon to amino acid" table the amino acid column should have title "amino acid" instead of "Protein":

![Selection_159](https://user-images.githubusercontent.com/4618288/74581933-e030ce00-4ff8-11ea-81c8-13d174881675.png)

prove:
![Selection_160](https://user-images.githubusercontent.com/4618288/74581925-bc6d8800-4ff8-11ea-86d5-1b8c863ee8cc.png)

**Comment by kytrinyx** [comment]
I agree! Thank you ❤️

**Comment by 0xNeshi** [comment]
Technically speaking, this exercise should be renamed to `polypeptide-translation` and the [corresponding function](https://github.com/exercism/problem-specifications/blob/main/exercises/protein-translation/canonical-data.json#L11) renamed from `proteins` to `polypeptide`. Even `aminoAcids` would be more correct.
