### ISSUE TITLE
Scale generator: s/augmented first/augmented second/

### ISSUE THREAD

**Issue by r4f4** [exercism/problem-specifications#1642]
See https://en.wikipedia.org/wiki/Augmented_second

**Comment by yawpitch** [comment]
Sorry, what is this issue about?

**Comment by r4f4** [comment]
A typo in the problem description. It describes an "augmented first" interval when in fact it means an "augmented second". It confused me at first because the former is just a half-step while the latter is a whole step and a half.

**Comment by yawpitch** [comment]
Ahh, right ... well, no problem, I haven't got time to get to it right now, but please feel free to open a PR that corrects [exercises/scale-generator/description.md](https://github.com/exercism/problem-specifications/blob/master/exercises/scale-generator/description.md).
