### ISSUE TITLE
Tests don't catch bug in submission to pangram exercise

### ISSUE THREAD

**Issue by chivalry** [exercism/problem-specifications#1646]
This was my initial submission for the pangram in the Python track:

```
def is_pangram(sentence):
    sentence = sentence.lower()
    for c in range(ord('a'), ord('z')):
        if chr(c) not in sentence:
            return False
    return True
```

It passed all the tests, but has a bug. It's not actually checking for the letter z, but since that letter isn't in all of the test sentences, the submission passed the tests.

Not understanding how problem specifications work, I actually submitted an edit to `pangram_test.py` with the following addition:

```
import string
...
def test_all_letters_checked(self):
    alphabet = ''
    for c in string.ascii_lowercase:
        alphabet += c
    for c in string.ascii_lowercase:
        s = alphabet.replace(c, '')
        self.assertIs(is_pangram(s), False)
```

The checks failed, I investigated it a bit more, and see that this test file is autogenerated and to fully add the test would require editing the `canonical-data.json` file and the Jinja templates for all the tracks. Given that it's not a simple test against a sentence, I'm not even sure that's the right route.

Any advice?

**Comment by cmccandless** [comment]
The premise here is that solutions that use the incorrect bounds with a range-based approach might still pass the tests, yes? Can we just add tests that verify both the upper and lower bounds are tested?

```
def test_lower_bound(self):
    self.assertIs(
        is_pangram("bcdefghijklmnopqrstuvwxyz"),
        False
    )

def test_upper_bound(self):
    self.assertIs(
        is_pangram("abcdefghijklmnopqrstuvwxy"),
        False
    )
```

**Comment by ErikSchierboom** [comment]
I think this issue can be closed now that we have [this test case](https://github.com/exercism/problem-specifications/blob/main/exercises/pangram/canonical-data.json#L22). Let me know if that is incorrect, and I'll reopen.
