### ISSUE TITLE
Should rikki- submit all the hello worlds?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/problem-specifications#165]
Right now, if you submit a solution to a hello-world problem, rikki- automatically gives a little bit of feedback.

I think this is really useful, in that it's potential documentation, but it's in the right place at the right time.

If rikki- submit's all of the reference solutions to hello world, then rikki-'s comment will have the little `</>` icon (used to be the rocket ship).

![their-solution](https://cloud.githubusercontent.com/assets/276834/12075676/b3b6fed2-b144-11e5-89d6-be76bb60a77c.png)

This would be an opportunity to say "hey, when someone comments, you can go see their solution by clicking the </>".

Tangentially, maybe we should add the hello-world to the "exercises" list, even though people aren't expected to comment on them. This would make it so that rikki- also could say: "go look at other people's solutions by clicking on 'Exercises' in the top menu".

**Comment by ryanplusplus** [comment]
Not really related to rikki-, but I like the idea of adding `hello-world` to the exercises list because it makes it easier to say hello and welcome newcomers to a track.

**Comment by kytrinyx** [comment]
That's a good point. We can still have rikki say that technically don't expect nitpicks so that we manage expectations a little, but I really like the idea of welcoming new users.

**Comment by petertseng** [comment]
no longer relevant because rikki doesn't comment on hello worlds anymore
