### ISSUE TITLE
Isogram vs heterogram

### ISSUE THREAD

**Issue by qudongfang** [exercism/problem-specifications#1654]
It would be a little bit more interesting if we follow the second definition of it in Wikipedia.

Wikipedia:
> An isogram (also known as a "nonpattern word") is a term in recreational linguistics. It has been used with two different definitions:
> 
> - Equivalent to heterogram; or
> - A word or phrase where every letter appears the same number of times.
> 

https://en.wikipedia.org/wiki/Heterogram_(literature)

**Comment by yawpitch** [comment]
Effectively we already do, since a heterogram is a first-order isogram. I'd be happy with any language track expanding the exercise to higher-order isograms, but any modification of the canonical data to do so would be blocked by #1560 for now.

**Comment by qudongfang** [comment]
I found it on the Python track.

**Comment by yawpitch** [comment]
> I found it on the Python track.

Feel free to start an Issue in https://github.com/exercism/python and we'll discuss the merits of widening the definition there.. This repo is for the canonical data shared by _all_ the languages, and currently we're not accepting non bug-fix changes here.

**Comment by qudongfang** [comment]
Thanks, I will close this issue.
