### ISSUE TITLE
Track configuration documentation not clear enough

### ISSUE THREAD

**Issue by cmcaine** [exercism/problem-specifications#1675]
https://github.com/exercism/problem-specifications/blob/master/CONTRIBUTING.md#track-configuration-file

>Each language track has a configuration file called `config.json`.
>
> Important keys are:
>
>  - problems - actively served via exercism fetch
>  - deprecated - implemented, but aren't served anymore
>  - foregone - will not be implemented in the track

This sounds like these are three keys containing lists of exercises, but that's not the case, at least in the Julia track config.json.

Instead we have a key `exercises` that maps to an array of exercises and to deprecate one, you add `deprecated: true` to the relevant exercise. We don't have a `problems` key at all.

I think this section should be rewritten by someone who knows how it works or should be updated to point at more up to date documentation if that exists.

**Comment by iHiD** [comment]
@ErikSchierboom Can you fix this when adding the other changes from #1674 pls :)

**Comment by ErikSchierboom** [comment]
Yep, will do.

**Comment by ErikSchierboom** [comment]
The documentation has been updated and now refers to right document.
