### ISSUE TITLE
Schema: use uuid format instead of regex pattern.

### ISSUE THREAD

**Issue by SaschaMann** [exercism/problem-specifications#1701]
Later versions of json-schema support UUIDs natively: https://stackoverflow.com/questions/50204588/how-to-define-uuid-property-in-json-schema-and-open-api-oas/61839372#61839372.

**Comment by ErikSchierboom** [comment]
Ooh, that's nice!

**Comment by ErikSchierboom** [comment]
As was verified in #1924, the uuid format supported in JSON schema does not differentiate between v1 and v4 uuids.
