### ISSUE TITLE
Lint tests.toml ?

### ISSUE THREAD

**Issue by wolf99** [exercism/problem-specifications#1714]
Is it worth introducing a CI task to lint the `tests.toml` files in each track?

Neither TOML nor GitHub Actions are something I know much about so not aware of the effort-to-benefit ratio.
It may make life easier for newer contributors when creating new exercise implementations though (and for those that review them).

**Comment by ErikSchierboom** [comment]
> It may make life easier for newer contributors when creating new exercise implementations though (and for those that review them

Well, the tests.toml are supposed to only be modified using the `canonical-data-syncer` tool, so they should all have consistent formatting. We could of course do linting to prevent mistakes and such. I think this is something that we would want to build into configlet, so it might be good to open an issue there.

**Comment by coriolinus** [comment]
> Well, the tests.toml are supposed to only be modified using the canonical-data-syncer tool

Wait, really? I've _already_ written some [minor scripts](https://github.com/exercism/rust/pull/978/commits/f3bae5c7477fc28144c982cb7090746c4aaa4fa5) messing with the file. I'd expect that when things settle and we start updating exercise generators, they'll also want to automatically manage that file as they add and replace the tests implemented for an exercise.

**Comment by ErikSchierboom** [comment]
> Wait, really? I've already written some minor scripts messing with the file. I'd expect that when things settle and we start updating exercise generators, they'll also want to automatically manage that file as they add and replace the tests implemented for an exercise.

Oh that is totally fine. I should have worded that a bit differently. It came out wrong. I think _most_ tracks will be using the canonical-data-syncer primarily to interact with the tests.toml file, but it is perfectly fine to edit it manually.

**Comment by wolf99** [comment]
Have raised https://github.com/exercism/configlet/issues/185 as suggested, so closing here.
