### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by OMEGA-Y** [exercism/problem-specifications#1724]
![image](https://user-images.githubusercontent.com/67114268/96993293-10584580-1566-11eb-87f9-0a58c299f6a7.png)

When I checked the 'zipper' folder, there was a canonical-data.json file.
So, could I update the list about that part in the README.md?

**Comment by SleeplessByte** [comment]
I think it was meant to illustrate `canonical-data` is _optional_.

**Comment by ErikSchierboom** [comment]
It is. For _most_ exercises it is present, but not for all. Hence the `(optional)` after the file name.

**Comment by OMEGA-Y** [comment]
Ah, Okay. Thanks for answer.
