### ISSUE TITLE
Colors are in lowercase, but in explanation first letter is uppercase

### ISSUE THREAD

**Issue by sergarb1** [exercism/problem-specifications#1732]
Hi! I want to make a request. In this provle, provided test have lowercase color names, but in explanation, first letter is upper case. In my opinion it confuses students.

Can we change problema explanation and show only lowercase color names?

Regards!

**Comment by SleeplessByte** [comment]
I understand the frustration that can arise, but the goal here is to _force_ the students to decide _for themselves_ how to approach this. It's usually a topic for debate.
