### ISSUE TITLE
grade-school test for student in multiple grades does not make sense

### ISSUE THREAD

**Issue by wolf99** [exercism/problem-specifications#1763]
https://github.com/exercism/problem-specifications/blob/eb6c32b421ad3e4da9623fa504543e69d9323f57/exercises/grade-school/canonical-data.json#L19

Firstly this test has `desiredGrade` as an input, but is a test of the `roster` property, this input is otherwise only used with the `grade` property. This does not make sense in terms of the functionality required for the properties

```c
students_t roster(input); // this case, and only this case, implies adding desired_grade argument here also, which does not make sense
students_t grade(input, desired_grade);
```

This seems like possibly just a mistake of copy-pasta `roster` when `grade` was intended. Thus the solution would be simply  to change the property under test from `roster` to `grade`. I can add a PR to resolve this if I have understood correctly?

A second issue is that the `students` input is intended, per the `README.md`, one by one. This implies some order of addition. The order used does not matter, just that there must be one.
However, the `desiredGrade` is then queried later.
So a function used to add students (e.g. `add_student(student_t student)` ) could check inputs for duplicate names, but it can only prevent second and third additions. It cannot know in advance of adding the first name that a second name will be added that will conflict with it.

Thus the input of the following cannot make sense given that the `desiredGrade`, that should return an empty roster, is the _first_ student to be added:
```json
            "students": [
              ["Aimee", 2],
              ["Aimee", 1]
            ],
            "desiredGrade": 2
```

If instead, we say that addition of students should not be filtered, but instead the `grade()` function should filter what gets output from the data that has been added; then yes, this can work, but it is ugly and requires poor implementation in just about any language I know (true, I don't know a lot of languages 😄 ).

A solution to this problem can be that the `README.md` is added to remove suggestions about what implementation should be - just describe the problem and let languages implement a solution in an idiomatic manner. Is this correct understanding, maybe I have missed something?

**Comment by SleeplessByte** [comment]
The _property_ should probably be _neither_ `grade` nor `roster`, but a _new_ property that's basically: student is only in grade n, where n = 2.

I don't really understand the rest of the issue (I mean the second point). The end goals is that Aimee can only be added once. The person who came up with the test wanted the "first one" to win. Does that help?

**Comment by petertseng** [comment]
Oh ha... missed this when updating my verifier for that new case... my verifier simply **ignores** the `desiredGrade` property and thereby passes all tests by declaring that a students that's added twice is in **none** of the grades... that's a mistake on my part. I'll update the verifier to show me cases with inconsistent input keys per property.

**Comment by ErikSchierboom** [comment]
> The property should probably be neither grade nor roster, but a new property that's basically: student is only in grade n, where n = 2.

To me it sounds like this is an error case, in which case using the existing `grade` or `roster` property is fine, but we should remove the `desiredGrade` property and convert the expected value to an error case.

**Comment by wolf99** [comment]
In terms of trying to build a JSON that makes sense, either of the following seems more logical than current spec:

```json
        {
          "uuid": "dece43c8-3ba5-11eb-8fdf-7f8daeaeb5f2",
          "description": "A student can't be in two different grades",
          "property": "roster",
          "input": {
            "students": [
              ["Aimee", 2],
              ["Aimee", 1]
            ]
          },
          "expected": [ "Aimee" ]
        },
```

```json
        {
          "uuid": "dece43c8-3ba5-11eb-8fdf-7f8daeaeb5f2",
          "description": "A student can't be in two different grades",
          "property": "grade",
          "input": {
            "students": [
              ["Aimee", 2],
              ["Aimee", 1]
            ],
            "desiredGrade": 1
          },
          "expected": []
        },
```

But it shouldn't be the mix of both that it seems to be currently.

**Comment by wolf99** [comment]
OK, here's my logic using examples from the existing `description.md`.

If, as @SleeplessByte has mentioned, the first addition of a student "wins", then Aimee is added to the roster in grade 2

Taking a literal transposition of the rules in the `description.md`:

- Get a sorted list of all students in all grades.  Grades should sort
  as 1, 2, 3, etc., and students within a grade should be sorted
  alphabetically by name.
  - "Who all is enrolled in school right now?"
  - --- "Oh and just this time especially, lets throw a grade = 2 requirement in the mix, i.e. forget what I just said in the first step about all grades."
  - "Let me think. We have
  Aimee

This is the only test case that uses the `desiredGrade` input with the roster `property` which, as you can see from the example, it does not make sense to do. And the result does not indicate anything about the grade of Aimee.

Thus there are two other ways of interpreting this, firstly, keep the property as `roster`, and remove the `desiredGrade`.
I think this option makes more logical sense than the current test case, but still does not tell us anything about Aimee's grade.

- Get a sorted list of all students in all grades.  Grades should sort
  as 1, 2, 3, etc., and students within a grade should be sorted
  alphabetically by name.
  - "Who all is enrolled in school right now?"
  - "Let me think. We have
  Anna

Alternatively, change the property to `grade` and the `desiredGrade` to `1`:

- Get a list of all students enrolled in a grade
    - "Which students are in grade 1?" (== property: grade, desiredGrade: 1)
   - "No-one in that grade"

This last option makes logical sense *and* the output tells us that Aimee is not in grade 1 as the input may otherwise imply.

- In code terms it is the difference between a collection of grade sets (where there can be one Aimee in multiple sets), and a single set of multiple grades, where there can be only one Aimee in the school.
