### ISSUE TITLE
two fer's README.md examples improperly formatted

### ISSUE THREAD

**Issue by bubo-py** [exercism/problem-specifications#1768]
![image](https://user-images.githubusercontent.com/57272901/105087088-45f3c880-5a9a-11eb-92dc-80c152109ce2.png)

Just as in the picture, something is wrong with markup formatting. I believe adding break line or deleting Zaphod example(which is too long) will help.

**Comment by SleeplessByte** [comment]
There's no formatting issue, unfortunately. In v3 we have to make sure to pad the table cells to fix this. Removing `Zaphod` will cause `String to return` to be flush with `Name` (same issue).

**Comment by bubo-py** [comment]
Oh, alright. @SleeplessByte Should I close the issue then?

**Comment by SleeplessByte** [comment]
Let's leave it so we can track it. @ihid one for April.

**Comment by ErikSchierboom** [comment]
It looks like the [current description](https://github.com/exercism/problem-specifications/blob/main/exercises/two-fer/description.md) has fixed this, therefore I'm closing this issue. If you feel like this issue has been wrongly closed, feel free to re-open.
