### ISSUE TITLE
roman-numerals: [bug] canonical-data descriptions do not match data

### ISSUE THREAD

**Issue by wolf99** [exercism/problem-specifications#1769]
The `canoncial-data.json` for the `roman-numerals` exercise is all kinds of wrong
For a lot of the latter tests, the data does not match the description

```json
    {
      "uuid": "46b46e5b-24da-4180-bfe2-2ef30b39d0d0",
      "description": "90, being 100 - 10, is XC",
      "property": "roman",
      "input": {
        "number": 93
      },
      "expected": "XCIII"
    },
```

For almost all of the tests, the descriptions are too wordy to be able to make "nice" matching test-case function names,

```json
    {
      "uuid": "b374a79c-3bea-43e6-8db8-1286f79c7106",
      "description": "3 is three I's",             // A more simple "3 is III" ?
      "property": "roman",
      "input": {
        "number": 3
      },
      "expected": "III"
    },
```

For some of the latter tests, the descriptions include maths and explanations rather than just what the test is.

```json
    {
      "uuid": "607ead62-23d6-4c11-a396-ef821e2e5f75",
      "description": "49 is not 40 + 5 + 4 but rather 50 - 10 + 10 - 1",     // Better to be "49 is XLIX" ? Describe test rather than explain how maths works
      "property": "roman",
      "input": {
        "number": 49
      },
      "expected": "XLIX"
    },
```

Once I get done with my current work on the C track I may make a PR for this myself, but if someone wants to take it up in the mean time please be my guest 😄

**Comment by SleeplessByte** [comment]
I also hated these test names so I am on board with changing them.

```json
"description": "90, being 100 - 10, is XC",
"property": "roman",
"input": {
  "number": 93
},
"expected": "XCIII"
```

In context, this test does test that `90` is `XC`.
