### ISSUE TITLE
ISBN number verifier - wrong specification

### ISSUE THREAD

**Issue by gkucmierz** [exercism/problem-specifications#1771]
https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/description.md

This example is not correct.
 - it uses 10 digits but it should only 9
 - weights are in not correct order (it should be ascending)

**Comment by gkucmierz** [comment]
It looks like here is correct implementation:

https://exercism.io/tracks/javascript/exercises/isbn-verifier/solutions/bfb1ce33a7f449a0b5c74daad9bf141b

https://github.com/gkucmierz/Exercism/blob/master/javascript/isbn-verifier/isbn-verifier.js#L10-L12

Weights from 1 to 9 (9 digits, 9 weights)

**Comment by SleeplessByte** [comment]
The 10-digit ISBN really has _descending_ weights, as explained [here](https://web.archive.org/web/20130522043458/http://www.isbn.org/standards/home/isbn/international/html/usm4.htm) on the [ISBN Standards page](https://web.archive.org/web/20130522043458/http://www.isbn.org/standards/home/isbn/international/html/usm4.htm).

Can you explain why you think it's incorrect?

**Comment by gkucmierz** [comment]
In this example last digit which is checksum number is used to calculate checksum.

There are 9 digits + 1 checksum so only 9 weights should be applied not 10.

**Comment by gkucmierz** [comment]
It is my mistake, sorry.
