### ISSUE TITLE
The master branch has been renamed to main

### ISSUE THREAD

**Issue by iHiD** [exercism/problem-specifications#1772]
In line with our new org-wide policy, the `master` branch of this repo has been renamed to `main`. All open PRs have been automatically repointed.

GitHub should show you a notification about this when you look at this repo:

<img width="534" alt="Screenshot 2021-01-27 at 15 31 45" src="https://user-images.githubusercontent.com/286476/106013980-e9556680-60b4-11eb-992c-606b9f84a0b5.png">

In case it doesn't, this is the command it suggests:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

You may like to update the primary branch on your forks too, which you can do under Settings->Branches and clicking the pencil icon on the right-hand-side under Default Branch:

<img width="933" alt="Screenshot 2021-01-27 at 18 50 08" src="https://user-images.githubusercontent.com/286476/106039011-84a80500-60d0-11eb-87d2-8c3ab3524523.png">

**Comment by BethanyG** [comment]
Just went through the rename process, and dare I say....on my end, it was painless!  🎉   **_Thank you._**

**Comment by wolf99** [comment]
I followed the instructions per above.
Git spat out the following after a `git pull --prune` :

```cli
~/git/problem-specifications[main]❯ git pull --prune
All keys already loaded
From github.com:exercism/problem-specifications
 - [deleted]         (none)     -> origin/master
   (refs/remotes/origin/HEAD has become dangling)
Already up to date.
```
Seems like this might be safe to ingore?

**Comment by iHiD** [comment]
I would think it would safe to ignore, yes.

**Comment by ErikSchierboom** [comment]
I had a similar message and fixed it by `git remote set-head origin main`.

**Comment by BryanJBryce** [comment]
wow

**Comment by projektorius96** [comment]
> I followed the instructions per above. Git spat out the following after a `git pull --prune` :
> 
> ```
> ~/git/problem-specifications[main]❯ git pull --prune
> All keys already loaded
> From github.com:exercism/problem-specifications
>  - [deleted]         (none)     -> origin/master
>    (refs/remotes/origin/HEAD has become dangling)
> Already up to date.
> ```
> 
> Seems like this dangling HEAD might be safe to ignore?

Whoever is still reading this (2024 and onwards), the "dangling" essentially means that you're still locally tracking the remote upstream (branch), in this case origin/master", that perhaps has been recently deleted ; running the following commands should solve the issue

```diff
# Ignoring the specificity of issue, you can try the following:
git branch -m master main # renames your local "master" to "main"
git branch -d master # use -D instead of -d if you get an error saying that "the branch is not fully merged"
git remote set-head origin -a # let your "local" main be aware of remote default branch "origin/main", essentially this command works in tandem with "$ git fetch" and is same as pressing "Fetch origin" on GitHub Desktop
# BEWARE : $ git remote set-head does not change your default remote branch as if done via GitHub UI on your browser.. 
# ..to do so see the DOCS@https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch
```
