### ISSUE TITLE
meetup, what does "-teenth" mean?

### ISSUE THREAD

**Issue by NobbZ** [exercism/problem-specifications#1786]
Hi there!

I can't make any sense from the "-teenth" stuff mentioned in the exercise… Perhaps someone could clarify what it means?

Sidenote: Also various translators did not know the term "monteenth" or similar…

**Comment by petertseng** [comment]
Fair. Then we should discuss what should be added to https://github.com/exercism/problem-specifications/blob/main/exercises/meetup/description.md. As we can see, the current text reads:

> Note that "monteenth", "tuesteenth", etc are all made up words. There was a meetup whose members realized that there are exactly 7 numbered days in a month that end in '-teenth'. Therefore, one is guaranteed that each day of the week (Monday, Tuesday, ...) will have exactly one date that is named with '-teenth' in every month.

So perhaps we'd have to add something like the following:

> Therefore, to find the -teenth of a given day of the week, find the single date that both falls on that day of the week and ends in "teenth"

Your feedback on whether that would suffice, and/or a proposed improvement.

**Comment by cprieto** [comment]
while that feedback will help, we are still trapped in the definition of "-teenth". What is wrong with using an example? in the same way you are using "the first Monday of October", just use an example like "The Monteenth of October will be the day X because it represents the Y Monday of that month".

**Comment by SleeplessByte** [comment]
There's nothing wrong with using an example @cprieto. It's actually a great suggestion.

**Comment by gustavo7lagoas** [comment]
Hello. I know that it has been a while but I'd like to suggest an example for this:
13th to 19th are the ordinal numbers that ends with "teenth", right? So a good way to say this is to explain this context and add a link for it. I was struggling with it until I searched by "ordinal numbers". I am not a native speaker and I believe this is the main issue regarding understanding this concept.

**Comment by SleeplessByte** [comment]
Reopening for visibility
