### ISSUE TITLE
Word Search: new test case idea

### ISSUE THREAD

**Issue by mariohuq** [exercism/problem-specifications#1791]
Inspired by [this solution](https://exercism.io/tracks/fsharp/exercises/word-search/solutions/99fd8042a31a4adbb2fb2d1cd4ee12e4).

```json
    {
      "description": "Should fail to locate words that are not on horizontal, vertical, or diagonal lines",
      "property": "search",
      "input": {
        "grid": [
          "abc",
          "def"
        ],
        "wordsToSearchFor": [
          "aef",
          "ced",
          "abf",
          "cbd"
        ]
      },
      "expected": {
        "aef": null,
        "ced": null,
        "abf": null,
        "cbd": null
      }
    }
```

**Comment by ErikSchierboom** [comment]
Is the proposed test case any different than [this existing test case](https://github.com/exercism/problem-specifications/blob/main/exercises/word-search/canonical-data.json#L896)?

**Comment by mariohuq** [comment]
@ErikSchierboom , yes. This test case filters out solutions, those are give false positive results, that are likely to achieve by considering straight paths other than horizontal, vertical or diagonal, like 

```
[a][ ][ ]
[ ][e][f]
```

or

```
[a][b][ ]
[ ][ ][f]
```

Existing test case that checks false-positives, doesn't cover this.

**Comment by ErikSchierboom** [comment]
Ah, okay! Would you be interested in submitting a PR to add a test case to the [canonical data](https://github.com/exercism/problem-specifications/blob/main/exercises/word-search/canonical-data.json)?

**Comment by mariohuq** [comment]
@ErikSchierboom yes😀
