### ISSUE TITLE
Add topics: Closures, Unicode, Iterators

### ISSUE THREAD

**Issue by joshiraez** [exercism/problem-specifications#1794]
Hi,

I'd like to ask for permission to add the topics Closures and Unicode. Both are advanced topics that different languages handle differently, and they are used as topics in the TS track.

I'd also like to add the Iterators topic to Data Structures

**Comment by SleeplessByte** [comment]
I think we _might_ get rid of TOPICS (cc @iHiD @ErikSchierboom), but until then, I think these topics are fine. If they sign off, I think this can be PRed in.

**Comment by joshiraez** [comment]
I'll be creating the PR then

**Comment by iHiD** [comment]
We're getting rid of them at the track-level but they might remain helpful in problem-specs to give maintainers an idea of how the exercises are/can be solved? I've not thought about this at all.

**Comment by iHiD** [comment]
(Happy to have this added though @joshiraez - thanks!)

**Comment by loziniak** [comment]
I think *topics* have value as a list of ideas – for exercise solutions, for concepts...

**Comment by joshiraez** [comment]
I also think topics are useful to have a sort of overview of what to expect from a problem, and to be able to sort out problems of specific areas when you want to do targeted training about one thing

**Comment by SleeplessByte** [comment]
@iHiD yeah, I think they would probably be good to keep for now for that reason. Removing/changing can always be done later.

**Comment by ErikSchierboom** [comment]
We've gotten rid of topics in Exercism v3, so I think this issue can safely be closed. https://github.com/exercism/problem-specifications/issues/1894 tracks the removal of the TOPICS.txt file.
