### ISSUE TITLE
gradle testCompile() fails

### ISSUE THREAD

**Issue by gutsHellsing** [exercism/problem-specifications#1806]
first this is what i have on my machine

gradle:
------------------------------------------------------------
Gradle 7.0
------------------------------------------------------------

Build time:   2021-04-09 22:27:31 UTC
Revision:     d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (Oracle Corporation 11.0.11+9)
OS:           Windows 10 10.0 amd64

java:

openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode)

now for the problem, everytime i try to run gradle test i get this:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\user\Dropbox\Studies\Projects\Exercism\java\Easy\pangram\build.gradle' line: 14

* What went wrong:
A problem occurred evaluating root project 'pangram'.
> Could not find method testCompile() for arguments [junit:junit:4.13] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

i did a bit of research and google and it's usually either a missing plugin or the maven repo but those should be fine in your provided file, i really need some help.

**Comment by gutsHellsing** [comment]
> 
> 
> first this is what i have on my machine
> ## gradle:
> `
> ## Gradle 7.0
> 
> Build time: 2021-04-09 22:27:31 UTC
> Revision: d5661e3f0e07a8caff705f1badf79fb5df8022c4
> 
> Kotlin: 1.4.31
> Groovy: 3.0.7
> Ant: Apache Ant(TM) version 1.10.9 compiled on September 27 2020
> JVM: 11.0.11 (Oracle Corporation 11.0.11+9)
> OS: Windows 10 10.0 amd64`java:`openjdk 11.0.11 2021-04-20
> OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
> OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode)`
> 
> now for the problem, everytime i try to run gradle test i get this:
> `FAILURE: Build failed with an exception.
> 
>     * Where:
>       Build file 'C:\Users\user\Dropbox\Studies\Projects\Exercism\java\Easy\pangram\build.gradle' line: 14
> 
>     * What went wrong:
>       A problem occurred evaluating root project 'pangram'.
> 
> 
> > Could not find method testCompile() for arguments [junit:junit:4.13] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
>     * Try:
>       Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
>     * Get more help at https://help.gradle.org
> 
> 
> BUILD FAILED in 1s`
> 
> i did a bit of research and google and it's usually either a missing plugin or the maven repo but those should be fine in your provided file, i really need some help.

**Comment by coriolinus** [comment]
This seems more relevant to https://github.com/exercism/java than here, so I'm going to transfer the issue.

**Comment by gutsHellsing** [comment]
> 
> 
> This seems more relevant to https://github.com/exercism/java than here, so I'm going to ~transfer~ recommend transferring the issue.
> 
> [edit] Apparently I don't have sufficient permissions to transfer it there. Nevertheless, that's where I believe this issue belongs.

oh didn't notice there was a branch for it. i'll transfer it now.
