### ISSUE TITLE
markdown h7 test: missing paragraph tags

### ISSUE THREAD

**Issue by glennj** [exercism/problem-specifications#1822]
This was added in PR #1817 

Concerning the line https://github.com/exercism/problem-specifications/blob/main/exercises/markdown/canonical-data.json#L104
```none
"expected": "####### This will not be an h7"
```
shouldn't that be
```none
"expected": "<p>####### This will not be an h7</p>"
```

**Comment by angelikatyborska** [comment]
You're right, I didn't notice that during the review of that PR 🤔

**Comment by glennj** [comment]
I can't just edit the expected value for that test, can I? Do I need to create a new test that supercedes?

**Comment by angelikatyborska** [comment]
Exactly, it needs to be a new case with a "reimplements" key that refers to the old one.
