### ISSUE TITLE
Grade school: new test raises a question

### ISSUE THREAD

**Issue by glennj** [exercism/problem-specifications#1824]
Regarding PR #1819 
```json
        {
          "uuid": "6a03b61e-1211-4783-a3cc-fc7f773fba3f",
          "reimplements": "c125dab7-2a53-492f-a99a-56ad511940d8",
          "comments": [
            "Reimplemented to be logically consistent"
          ],
          "description": "A student cannot be added to more than one grade in the sorted roster",
          "property": "roster",
          "input": {
            "students": [["Aimee", 2], ["Aimee", 1]]
          },
          "expected": ["Aimee"]
        },
```
All well and good, but what grade is Aimee in? 
1. grade 2 because that's what came first, or
2. grade 1 because that's what came last?

I think we're missing the property:grade test for this scenario.

**Comment by glennj** [comment]
IMO either interpretation is valid, but we need to make a decision. Maybe a vote by reaction: 
1. Heart for grade 1
2. Eyes for grade 2

**Comment by wolf99** [comment]
Intention after the mentioned PR was to rewrite the spec completely such that it covers the operation of adding students, as this clears up this and a lot of other issues.

**Comment by glennj** [comment]
I see. I'll wait patiently then.  

(taps foot, checks watch)
