### ISSUE TITLE
Two-Buckets ambiguous wording in problem statement

### ISSUE THREAD

**Issue by neenjaw** [exercism/problem-specifications#1832]
In [the problem statement](https://github.com/exercism/problem-specifications/blob/main/exercises/two-bucket/description.md) there is a paragraph that reads:

>To help, the tests provide you with which bucket to fill first. That means, when starting with the larger bucket full, you are NOT allowed at any point to have the smaller bucket full and the larger bucket empty (aka, the opposite starting point); that would defeat the purpose of comparing both approaches!

This assumption holds until the test cases added ~ 10 mos ago in this ~commit: https://github.com/exercism/problem-specifications/commit/14131a0ad4f4d0ebfe6b348828a4dac1b7645a00~ Pr: #1580 

Now it requires you to forbid any traversal through a state where the starting bucket is 0 and the other bucket is max capacity.

Thoughts? I think the problem statement could be clarified with clearer rules about the intended solution.

Happy to PR if people agree.

**Comment by jiegillet** [comment]
I think you shared the wrong commit link, that one only adds headers.

**Comment by petertseng** [comment]
I suppose it's fair to say that it can be improved for this reason: there are some cases where we don't compare both starting points, and the problem statement says "comparing both approaches".

> Now it requires you to forbid any traversal through a state where the starting bucket is 0 and the other bucket is max capacity.

I'm not sure I understand how the quoted statement is different from the existing description, but I agree that the quoted statement is correct, so it doesn't seem like there'd be a problem with making such a change if that would be clearer.

> This assumption holds until the test cases added ~ 10 mos ago in this commit: 14131a0

For me, that commit is entitled "Add h1 heading to exercise description (#1782) " and only changes descriptions and adds no cases. Have I misunderstood, or are we supposed to be talking about a different commit?

**Comment by neenjaw** [comment]
> I think you shared the wrong commit link, that one only adds headers.

Yes, sorry, copied the wrong commit to this issue, link changed to PR #1580

**Comment by jiegillet** [comment]
> > To help, the tests provide you with which bucket to fill first. That means, when starting with the larger bucket full, you are NOT allowed at any point to have the smaller bucket full and the larger bucket empty (aka, the opposite starting point); that would defeat the purpose of comparing both approaches!

> Now it requires you to forbid any traversal through a state where the starting bucket is 0 and the other bucket is max capacity.

Aren't those 2 the same thing?  
 
I suppose the description only mentions starting with the large bucket, not starting with a small bucket. I guess we could rephrase as

> That means, you are NOT allowed at any point to be in the opposite starting point, for example when starting with the larger bucket full, you cannot reach a state where the smaller bucket full and the larger bucket empty; that would defeat the purpose of comparing both approaches!

**Comment by neenjaw** [comment]
I would argue that they same when reading it plainly and at the very least they are ambiguous.

I think we should just state more plainly the limitations/bounds of the solution:

> - For each step, you may only do one of the following actions:
>   - ...yadda yadda yadda...
> - After each step, you may not arrive at a state where the starting bucket is empty and the other bucket is full.
