### ISSUE TITLE
In Connect exercise; wrong tests

### ISSUE THREAD

**Issue by henebb** [exercism/problem-specifications#1840]
Hi! Either I'm not understanding the exercise, or there's an error in the tests :)

Check the "X wins crossing from left to right" test. The board is 4 columns but 5 rows. There shouldn't be a winner, but the test says Black should win.
Same with the "O wins crossing from top to bottom" test. It should be None, but the test expects White to win.
Also check the "Nobody wins crossing adjacent angles" test. It says None. Which is correct. But not because of the test description, but because the board is 4 columns and 5 rows :)

**Comment by glennj** [comment]
> because the board is 4 columns and 5 rows 

The description does say:

> Note that all games need not be "fair". (For example, players may have mismatched piece counts or the game's **_board might have a different width and height_**.)

**Comment by henebb** [comment]
Ah! Missed a "not" there 😆
