### ISSUE TITLE
How to handle missing source_url?

### ISSUE THREAD

**Issue by wolf99** [exercism/problem-specifications#1849]
Configlet is now failing for missing `source_url` in an exercise's `config.json`.
However, there exists >1 problem specifications which do not have a `source_url` specified in the problem's `metadata.yml`.
How should language tracks handle this such that missing `source_urls` don't constantly fail CI?

Example: https://github.com/exercism/c/pull/683/checks?check_run_id=3591594512

**Comment by petertseng** [comment]
in such a case, shouldn't source_url be **removed** from config.json? As was done in https://github.com/exercism/c/pull/688

**Comment by wolf99** [comment]
Good catch!
Thanks @petertseng
