### ISSUE TITLE
hello-world: description forces implementation

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/problem-specifications#1850]
The [description.md file](https://github.com/exercism/problem-specifications/blob/main/exercises/hello-world/description.md) of the `hello-world` exercise contains the following text:

> Write a function that returns the string "Hello, World!"

While this may seem innocuous, not all tracks are using a function to return the string "Hello, World!". 

Case in point: [F#](https://github.com/exercism/fsharp/blob/main/exercises/practice/hello-world/HelloWorld.fs)

While we _could_ make F# use a function, I'd rather not to as it adds unnecessary overhead. 

Apart from that, some tracks only have methods (which are a special type of functions), so the terminology seems wrong there too. 

Maybe we could come up with an alternative description?

**Comment by petertseng** [comment]
When we removed the language of "Write a program to do X" in https://github.com/exercism/problem-specifications/issues/321 we considered alternatives:

* Write a function to do X
* Write code to do X
* Do X

It seems that in most cases, "Do X" was used in https://github.com/exercism/problem-specifications/pull/528

If we were to take that approach here, then perhaps we're looking at something like...

> Produce the string "Hello, World!"

It's not easy to come up with a lowest common denominator wording, that's for sure.

**Comment by petertseng** [comment]
EBWODP:

> Do X

 (to clarify, the verb differs based on what the exercise is; it's not literally the word "do"; often it will be "implement X", etc.)

**Comment by petertseng** [comment]
EBWODP: 

Here's another idea, based on the fact that (to my knowledge) we've generally agreed that stubs should be provided:

> Modify the provided code so that it produces the string "Hello, World!"

**Comment by ErikSchierboom** [comment]
> Here's another idea, based on the fact that (to my knowledge) we've generally agreed that stubs should be provided:

> > Modify the provided code so that it produces the string "Hello, World!"

I really like this suggestion. We have indeed mandated stubs, so this fits with that nicely.

**Comment by peterloane** [comment]
Would the following wording be clearer?

Change
> Modify the provided code so that it produces the string "Hello, World!"
to
Modify the provided code so that it displays the string "Hello, World!"

**Comment by glennj** [comment]
If the language wants the string _returned_, that's not really "displaying". "Producing" is more apropos.

**Comment by peterloane** [comment]
Yes, displaying is not an improvement.

Producing just seems a bit opaque to me here.
Would "output" be better? 

Modify the provided code so that it outputs the string "Hello, World!"

**Comment by siebenschlaefer** [comment]
Or "returns"?

**Comment by SleeplessByte** [comment]
@siebenschlaefer the point is that there are languages where it's _not_ a function and thus there is no _return_ (neither implicit or explicit).

**Comment by ErikSchierboom** [comment]
"Producing" might be a bit opaque, but that is also a benefit here :)

**Comment by peterloane** [comment]
What is wanted should be as clear as possible though

'The classical introductory exercise. Just say "Hello, World!".' 
but what is wanted is
'The classical introductory exercise. Just output "Hello, World!".'

**Comment by ErikSchierboom** [comment]
> but what is wanted is
> 'The classical introductory exercise. Just output "Hello, World!".'

I don't think this is the straightforward answer, as outputting can very easily be interpreted as: print to the console, which is not what we want.

**Comment by SleeplessByte** [comment]
Perhaps: `The result should be "Hello, World!"`, leaving it in the middle what "result" means?

**Comment by peterloane** [comment]
> I don't think this is the straightforward answer, as outputting can very easily be interpreted as: print to the console, which is not what we want.

Yes, it could be interpreted as print to the console, or write to a file, or any other form of output. To avoid unwanted interpretation, the specification of what is wanted would need to be more precise though

If print to the console is not wanted for example then what is it that is wanted?

**Comment by iago-lito** [comment]
Yeah, why not be explicit with something like *"Return the chain 'Hello World!' or display it to the console, or write it to a file, depending on the language track."* ?

**Comment by junedev** [comment]
It might not be perfect but I think this suggestion made above is substantially better than what we have currently so I would vote for using it for now.

> Modify the provided code so that it produces the string "Hello, World!"

**Comment by ErikSchierboom** [comment]
Anyone interested in doing a PR? 👼

**Comment by SaschaMann** [comment]
Is this exercise still relevant? I thought it had been replaced by the Goodbye, Mars -> Hello, World exercise?

**Comment by ErikSchierboom** [comment]
@SaschaMann That is the very same exercise :)

**Comment by ErikSchierboom** [comment]
With https://github.com/exercism/problem-specifications/pull/1926/files merged, this can now be closed.
