### ISSUE TITLE
Copying external texts: Is it allowed, and under what circumstances?

### ISSUE THREAD

**Issue by petertseng** [exercism/problem-specifications#1870]
I received a PR to update documentation of a track I maintain, and one proposal was to add a sentence that I see is straight from the Wikipedia page of the language in question, unedited. I am not sure if we are allowed to use that. I see that Wikipedia states:

> Text is available under the Creative Commons Attribution-ShareAlike License

So, it's possible we'd be allowed (if we attribute it), but I just want to be sure. Who can speak authoritatively on this subject?

It may also be useful to get an answer for not just Wikipedia but instead general rules that can help us understand what kinds of external texts could be used (something like "if it's under X license, yes, if it's under Y license, no")

I am asking here rather than in, say, a team discussion in our GitHub organisation, because I think it may be useful to have the answer in a public place so I can link to it if necessary.

**Comment by SaschaMann** [comment]
> It's also worth noting that I am happy for us to use things with non-commercial licences, e.g. https://creativecommons.org/licenses/by-nc-sa/3.0/. 

A Share-Alike license is **NOT** compatible with Exercism's current set of licenses (mainly MIT). I've pointed out before that a few of the Project Euler-based exercises in prob-specs violate this.

**Comment by iHiD** [comment]
I was referencing the NC bit of it, not the rest. The SA bit is compatible with AGPL3 for example (so any of the tooling). As we've discussed elsewhere, we'll soon be allowing individual exercises to have their own their licences, and changing to sublicence the existing track repos to by under CC, so in general I'm thinking with that in mind.

**Comment by petertseng** [comment]
The question is answered. Thank you.

Making it easier for me is the fact that the contributor has not decided to go forward with the Wikipedia-sourced text contribution, but it will be good to have this to refer to later on if it comes up again.
