### ISSUE TITLE
Zipper needs a test to go deep and return to the top

### ISSUE THREAD

**Issue by moveson** [exercism/problem-specifications#1872]
As currently written, the Zipper problem specification doesn't require testing a key feature of the zipper structure, which is the ability to navigate all the way back to the top of the tree from any depth. I recently completed this exercise on the Ruby track, and my first iteration passed all tests even though it did not properly implement this feature.

Operations for this new case would be `left`, `right`, `up`, `up`, `value`.

I've opened a PR on the Ruby track that would implement this case: https://github.com/exercism/ruby/pull/1261 to address the issue in that track: https://github.com/exercism/ruby/issues/1260

**Comment by wolf99** [comment]
Hi @moveson 
Thanks for identifying this and raising it up in problem specs!
Do you intend to raise a PR for the change in the specification in this repo?

**Comment by moveson** [comment]
@wolf99 Yes, I'm happy to put up a PR. Just wanted to make sure the maintainers were agreed that this spec should change as suggested.
