### ISSUE TITLE
[Grep] Discrepancy between instructions and tests about output format

### ISSUE THREAD

**Issue by vjau** [exercism/problem-specifications#1873]
The instructions says ```Your task is to implement the `grep` function, which should read the contents
of the specified files, find the lines that match the specified pattern
and then output those lines as a single string.```
By single string, i understand that if there are multiple lines matching the pattern, those lines should be concatenated to a single string. 
However, at least in Rust, a test for multiple matches is written like this : 
```rust
test_one_file_several_matches_no_flags(
        pattern = "may",
        flags = [],
        files = ["midsummer_night.txt"],
        expected = [
            "Nor how it may concern my modesty,",
            "But I beseech your grace that I may know",
            "The worst that may befall me in this case,"
        ]
    )
```
Where matching lines are not concatenated.
I don't know if this discrepancy is only found in Rust or in all languages that includes the Grep exercise.

**Comment by wolf99** [comment]
I am not very familiar with this exercise. However IIRC, grep (the tool) operates per the description you have quoted. Thus I would imagine that that was the intended result. I.E. that the output strings are concatenated.

**Comment by glennj** [comment]
I'm guessing some tracks split the output into a list of lines mostly to make the test suite is easier to read.

**Comment by vjau** [comment]
> I'm guessing some tracks split the output into a list of lines mostly to make the test suite is easier to read.

The problem with the Rust track is that the test fails because it's really expecting to get a vector of strings. 
I guess this is more a problem with the rust track than with the meta specification.

**Comment by vjau** [comment]
Another problem i see it that the specs never describe how the output should be formatted when greping through multiple files.
However the tests (at least in Rust and Javascript), seems to imply that the name of the file where the pattern was found should be a prefix of the result.

**Comment by wolf99** [comment]
Possibly the original implementer on the rust track is quite familiar with the grep tool and implemented the exercise to closely match the tool.
Having read the exercise `description.md`, it seems that the expected output is fairly well specified.

Maybe someone more familiar with either, or both, the tool and the exercise could suggest some addition to the description text that would indicate if the exercise is intended to fully mimic the tool or not?

**Comment by petertseng** [comment]
I don't see a reason to force tracks to pick one or the other (one string of multiple lines, or list of lines).

**Comment by vjau** [comment]
> I don't see a reason to force tracks to pick one or the other (one string of multiple lines, or list of lines).

It's not about forcing tracks. But the tests should follow the specification.

**Comment by glennj** [comment]
This feels like the same discussion that was had about "Hello World" (#1850), where "output" is the wrong word. Most tracks will implement this as a function that _returns_ a list or a string, but not require anything to be _output_ to the user, let alone as a single string or any other structure.

**Comment by ErikSchierboom** [comment]
We should indeed probably remove the part about what specific output is expected, as single strings or a collection. of strings are both completely valid.
