### ISSUE TITLE
[POV] Graph vs. Tree confusion

### ISSUE THREAD

**Issue by junedev** [exercism/problem-specifications#1874]
The exercise [description](https://github.com/exercism/problem-specifications/blob/main/exercises/pov/description.md) consistently uses the term `graph` and only mentions `family tree` as an example. However, the [canonical test data](https://github.com/exercism/problem-specifications/blob/main/exercises/pov/canonical-data.json#L5) uses the term `tree` and the test cases only contain trees. Most languages that implemented this exercise also already call the data structure `Tree` not `Graph` from what I could see.

A graph is defined as an arbitrary set of nodes and edges that connect two nodes: https://en.wikipedia.org/wiki/Graph_(discrete_mathematics)
A tree is a special case of graph where any two nodes are connected by exactly one path (no cycles, no "loose" nodes, [etc](https://en.wikipedia.org/wiki/Tree_(graph_theory)#Tree)): https://en.wikipedia.org/wiki/Tree_(graph_theory)

I think the exercise of re-rooting/re-parenting does make the most sense in the context of trees, not in the context of generic graphs (even though the concept of e [rooted graph](https://en.wikipedia.org/wiki/Rooted_graph) exists apparently).

Sidenote: There was already confusion about something similar before (https://github.com/exercism/problem-specifications/issues/377).

My suggestion how to address this issue would be to change the description to use the term `tree` with short explanation what a tree is and a like to the Wikipedia page.

**Comment by wolf99** [comment]
You made a good case @junedev !
Would you like to submit a PR to correct the description?

**Comment by junedev** [comment]
Thanks for the feedback @wolf99. I would like to leave some time in case someone else wants to comment but then I can create the PR.
