### ISSUE TITLE
Anagram: 2 tests for with the same name

### ISSUE THREAD

**Issue by xle263** [exercism/problem-specifications#1883]
There are 2 tests with same name and only one of them will execute, so one of these tests should be removed or renamed and refactored because it uses similar test data:

```json
{
      "uuid": "b3cca662-f50a-489e-ae10-ab8290a09bdc",
      "description": "detects two anagrams",
      "property": "findAnagrams",
      "input": {
        "subject": "master",
        "candidates": ["stream", "pigeon", "maters"]
      },
      "expected": ["stream", "maters"]
    },
    {
      "uuid": "03eb9bbe-8906-4ea0-84fa-ffe711b52c8b",
      "reimplements": "b3cca662-f50a-489e-ae10-ab8290a09bdc",
      "comments": [
        "Reimplemented to be consistent about removing references to 'master'"
      ],
      "description": "detects two anagrams",
      "property": "findAnagrams",
      "input": {
        "subject": "solemn",
        "candidates": ["lemons", "cherry", "melons"]
      },
      "expected": ["lemons", "melons"]
    },
```

**Comment by wolf99** [comment]
See the `"reimpliments"` field in the second one?
This means that the second one is intended to replace the first one.
The reason for the reimplimentation is shown in the `"comments"` field.
This is correct per the schema.

IIRC language tracks are free to implement whichever case they like, but the intention is that they would only implement one or the other, not both; and that they would implement the most recent (the second one).

**Comment by ErikSchierboom** [comment]
> IIRC language tracks are free to implement whichever case they like, but the intention is that they would only implement one or the other, not both; and that they would implement the most recent (the second one).

☝️ This is exactly correct. Sometimes we find that a test case has a mistake or that it could be improved upon. As we want test cases to be immutable, we thus came up with a mechanism (the reimplements field) to indicate that the test has a reimplementation. 

Sorry for the confusion!
