### ISSUE TITLE
Remove TOPICS.txt

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/problem-specifications#1894]
This repository contains a [TOPICS.txt file](https://github.com/exercism/problem-specifications/blob/main/TOPICS.txt) which was useful for Exercism v2, as exercises could have a list of topics. However, with Exercism v3 being released, topics are no longer used and the purpose of the TOPICS.txt as a central point of reference seems to be nil. I suggest to remove the file. Are there any objections to that?

One side note: we _could_ consider having a list of concepts on a docs page that is inspired by this list. For inspiration for tracks when working out concepts.

**Comment by SleeplessByte** [comment]
You also want to update the track dashboard when you do ;)

**Comment by ErikSchierboom** [comment]
@SleeplessByte PR created: https://github.com/exercism/tracks-maintenance-dashboard/pull/81
