### ISSUE TITLE
Rework/hide exercises that require domain specific expertise/knowledge

### ISSUE THREAD

**Issue by mohmad-null** [exercism/problem-specifications#1903]
There are a considerable number of exercises that appear to require some degree of domain knowledge / expertise to solve, and don't do anything to fill in the gaps. Often tracks have labelled these as "easy"!

The Exercism About page states:
> "Exercism exists to help as many people as possible attain fluency in any programming language they want. Programming skills can be source of great fun and a route to social mobility and we want to help people regardless of their backgrounds or their motivations. "

Exercises with problem descriptions that require domain expertise/knowledge do the exact opposite of that, creating frustration for those who lack a background in that area.

Examples:
* https://github.com/exercism/problem-specifications/issues/1902 - how do you generate them effectively?
* https://github.com/exercism/problem-specifications/blob/main/exercises/react/description.md - What's a "Reactive system"?
* https://github.com/exercism/problem-specifications/tree/main/exercises/complex-numbers - I don't even understand the first line of the description!
* https://exercism.org/tracks/python/exercises/scale-generator - tries to explain it but is still no idea what it really wants
* https://github.com/exercism/problem-specifications/blob/main/exercises/nucleotide-codons/description.md

I can see why these exercises may be appealing to those with that knowledge, but to those of us whose expertise lies elsewhere, they shouldn't be mixed in with the general pool of exercises where folks may stumble upon them, see they're "easy" and then start doubting their competence when they don't even understand the question (it will feed [imposter syndrome](https://en.wikipedia.org/wiki/Imposter_syndrome) and related issues).
I'd instead suggest putting them in some other pool where folks who want to do this sort of thing can hunt them out. Or simplify them to the level that domain expertise is not required.

**Comment by SaschaMann** [comment]
Some more examples:

- https://github.com/exercism/problem-specifications/blob/main/exercises/acronym/description.md - What's an acronym? I'm not a linguist, why do I need to know this?
- https://github.com/exercism/problem-specifications/blob/main/exercises/bob/description.md - This requires obscure knowledge about strings and sentence punctuation, perhaps even regex or something called "cases"?
- https://github.com/exercism/problem-specifications/blob/main/exercises/dominoes/description.md - What does a pizza chain and their stores' facades have to do with dots? I don't get it.
- There are at least three exercises about generating lyrics for songs. I'm not even sure what domain this is but what does it have to do with programming? https://github.com/exercism/problem-specifications/blob/main/exercises/food-chain/description.md https://github.com/exercism/problem-specifications/blob/main/exercises/beer-song/description.md https://github.com/exercism/problem-specifications/blob/main/exercises/house/description.md
- https://github.com/exercism/problem-specifications/blob/main/exercises/micro-blog/description.md requires knowledge about something called ASCII which based on a quick search is an outdated subset of letters used by Americans? Still not sure though

**Comment by mohmad-null** [comment]
@SaschaMann - I would like to suggest that sarcasm is not a constructive response.

**Comment by SaschaMann** [comment]
My explanations were sarcastic but my point doesn't change: If 7th/8th grade maths knowledge is considered advanced domain-specific knowledge, we need to apply that standard across the board. And in that case, all of the examples I've given fail to explain domain-specific prerequisite knowledge.

**Comment by mohmad-null** [comment]
Would that I indulge my loquacity and engage with those other entities who even now are partaking of this most verbose assemblage. Perchance I am not facilitating comprehension courtesy of a surfeit of sesquipedalia? While I am cognizant that many would floccinaucinihilipilificate this, it is a prime exemplar of the fallacious nature of your stance.

So, why don't we write all of the descriptions like that? It's English; anyone who has access to this has a dictionary. (I appreciate English is unlikely to be your first language; rest assured most native speakers would struggle with that too; that's the point!)

**Comment by junedev** [comment]
@SaschaMann @mohmad-null Let's use https://github.com/exercism/problem-specifications/issues/1902 for the discussion instead of discussing in two issues at once. As said there, it would be best to close this one and only use the other one so we don't have the same discussion in two places.

**Comment by mohmad-null** [comment]
@junedev - I'd prefer this one be the one kept open as it's overarching and covers the point. The other one is specific just to Pythagorus

**Comment by junedev** [comment]
@mohmad-null I understand but most of the discussion is in the other one already. What @siebenschlaefer and I wrote there applies to most other examples as well so you could copy the title and content over there and then use the pythagorean triplet as one concrete example to make it more tangible in the issue description.

**Comment by mohmad-null** [comment]
@junedev - I missed your post in that one before commenting here; apologies. I've edited that one. Feel free to close this. Thanks!
