### ISSUE TITLE
`rational-numbers` missing test case for negative rational exponent

### ISSUE THREAD

**Issue by neduard** [exercism/problem-specifications#1909]
The problem description states:
> Exponentiation of a rational number `r = a/b` to a negative integer power `n` is `r^n = (b^m)/(a^m)`, where `m = |n|`.

However this is not checked for in the [tests](https://github.com/exercism/problem-specifications/blob/main/exercises/rational-numbers/canonical-data.json#L268).

As such, the tests pass even if the implementation does something like
```
def rational_exponentiation(r, n):
  return Fraction(r.a ** n, r.b ** n)
```

Would my understanding be correct?  I'm happy to raise PR and add a test, just that I don't know how to generate UUID for it :sweat_smile:

(thanks @angelikatyborska for suggesting raising an issue)

**Comment by ericbalawejder** [comment]
It appears that there are only two tests for this case and they both use a positive integer power. No negative integer power as you mentioned. It would seem valuable to create a test implementation for it.

Even though it is not stated in the problem description, there is also no test for taking a negative real number and raising it to a rational power. 
```
Exponentiation of a real number x to a rational number r = a/b is x^(a/b) = root(x^a, b), where root(p, q) is the qth root of p.
```
If x were to be less than zero (negative), and r = a/b, where b is even, this would result in complex roots. If b is odd, it is ok to take the odd roots of negative numbers, as it preserves the sign. It may be a valuable lesson when implementing this particular method/function. Thoughts?

**Comment by petertseng** [comment]
Correct understanding. Adding a test for negative integer power would be good.

A UUID may be generated with any tool of your choice that generates version 4 UUIDs, even those that are available as a webpage on the internet.

For consideration of negative real numbers raised to rational powers, I suggest a separate issue.

**Comment by neduard** [comment]
Thanks @ericbalawejder and @petertseng ! I've created PR #1914 just for the negative integer tests.
