### ISSUE TITLE
ISBN Verifier instructions could use more clarity

### ISSUE THREAD

**Issue by blakeashleyjr** [exercism/problem-specifications#1975]
Hi,

I just completed the ISBN Verifier exercise and had some trouble deciphering [the instructions](https://github.com/exercism/go/blob/main/exercises/practice/isbn-verifier/.docs/instructions.md). I think a couple more clarifying sentences could go a long way.

I think the confusion comes from the example and instructions described in this section:

> ## ISBN
> 
> The ISBN-10 format is 9 digits (0 to 9) plus one check character (either a digit or an X only). In the case the check character is an X, this represents the value '10'. These may be communicated with or without hyphens, and can be checked for their validity by the following formula:
> 
> ```text
> (x1 * 10 + x2 * 9 + x3 * 8 + x4 * 7 + x5 * 6 + x6 * 5 + x7 * 4 + x8 * 3 + x9 * 2 + x10 * 1) mod 11 == 0
> ```
>
> If the result is 0, then it is a valid ISBN-10, otherwise it is invalid.

What purpose do the "x"s serve in the above example? It appears as if they would serve as a multiple for the number they are beside, though I cannot find any evidence for that in an outside source (it would also fail the tests.) Am I misreading it?

This [web page](http://www-math.ucdenver.edu/~wcherowi/jcorner/isbn.html) from the University of Colorado at Denver served as my primary guide during the exercise.

I would be happy to take a swing at a PR if others agree it could use some additional clarification!

**Comment by andrerfcsantos** [comment]
Hi @blakeashleyjr 👋

Thanks for opening an issue about this. I moved the issue to the problem specification repo as it is the right place to discuss changes to the practice exercises descriptions/tests. This common repository allows all tracks to benefit from changes to an exercise. If after some discussion you decide to create a PR, do it also in this repository.

**Comment by ErikSchierboom** [comment]
> What purpose do the "x"s serve in the above example?

They refer to the individual digits in the ISBN string. x1 is the leftmost digit, x2 the second digit, etc.

**Comment by kotp** [comment]
On Wed, Mar 02, 2022 at 11:02:31PM -0800, Erik Schierboom wrote:
> > What purpose do the "x"s serve in the above example?
> 
> They refer to the individual digits in the ISBN string. x1 is the
> leftmost digit, x2 the second digit, etc.

It could probably be d1, d2, etc. instead.  Because of the use of "x" to
indicate multiplication on paper, it is kind of confusing.

**Comment by ErikSchierboom** [comment]
That could be an improvement, maybe paired with an explanation that `d1` refers to the first digit, etc.

**Comment by SaschaMann** [comment]
> Because of the use of "x" to indicate multiplication on paper, it is kind of confusing.

The use of `×` rather than `·` for multiplication of numbers is the problem here. Wikipedia says `×` is mostly still being used in angloamerican cultures and France with sources going back to 1698 why it's more confusing than `·`. `x` is probably the most common name for a variable. That said, changing it to `d` for `digits` seems reasonable.

Perhaps this should use subscripts, in line with the PRs that changed `x^2` to `x²` etc.

**Comment by kotp** [comment]
That looks like superscripts to me.

d<sub>1</sub>, d<sub>2</sub> instead.

**Comment by blakeashleyjr** [comment]
The problem with a subscript is that it does not appear to be natively supported by all [markdown applications](https://www.markdownguide.org/extended-syntax/#subscript) (including VSCode by default), though I agree that this would be the ideal solution.

Is the d1...d9 + explanation solution the next best option?

**Comment by kotp** [comment]
Then use the real characters?  ₁₂₃₄₅₆₇₈₉₀
