### ISSUE TITLE
word-count: contains test case that doesn't match "word separator" on instruction

### ISSUE THREAD

**Issue by bupjae** [exercism/problem-specifications#1985]
The instruction says
> The words can be separated by any form of whitespace (ie "\t", "\n", " ")

One of test case says
>		"handles cramped lists",
>		"one,two,three",
>		Frequency{"one": 1, "three": 1, "two": 1},

This requires separating words by comma, not whitespace.

**Comment by andrerfcsantos** [comment]
@bupjae Thanks for opening this issue.

For practice exercises, changes to the instructions/test cases must be discussed in the problem specifications repository, so I transferred the issue to this repo. This allows all tracks to benefit from improvements to the instructions/tests. If later you want to open a PR about this, also do it in this repository and we'll also make the changes back in the Go track after they are approved and merged here.

I do agree that the instructions don't mention this case specifically. We do have this line explaining what to do with punctuation:

https://github.com/exercism/problem-specifications/blob/d05f467d19f4940a1670adadfa5ec5621551f492/exercises/word-count/description.md?plain=1#L15

However, I can see how asking to ignore punctuation might not clearly tell what is expected when words are separated by punctuation.

**Comment by bupjae** [comment]
How about merging 3 and 4 by following sentence?

> Other than the apostrophe in a _contraction_, words are separated by all forms of _punctuation_ and _whitespace_.

I think this might be more clear description than 'ignored'.

**Comment by kotp** [comment]
The statement in the instruction is clear when it says "can be separated by … whitespace", since it is not stating that it _must_ be.  The tests reinforce what is written, and sets the expectation clearly when it fails if you include the punctuation instead of excluding it (which may be done by ignoring, but that is an implementation detail, one may, instead of ignore, explicitly exclude them.)   And we do not want to drive, I think, the writing of the solution too specifically.

**Comment by bupjae** [comment]
It seems that I misunderstood the word 'ignore'; I thought ignoring comma from "one,two,three" becomes "onetwothree".

After seeing red result, my first impression was that exercise instruction was somewhat vague; it should have described what could be word boundary. Moreover, I feel somewhat uncomfortable because modifying code to just pass that particular test case feels "cheating".

However, after practicing more exercises on Exercism, I understand that this process is called Test-driven Development, and it is nothing wrong to modify code based on test case.

**Comment by kotp** [comment]
Right on.  So the written description is kind of like the "BOSS" description, where they know what they need to have done, but it is less technical, while the tests that are there are the technical "enforcement", and together they should not contradict each other, and in general, (unless it is a concept exercise) the tests should not force a specific way to solve, so should not enforce the "how", but should enforce a result.

**Comment by bupjae** [comment]
Thanks for comments. Let me close this issue as "Working as Intended".
