### ISSUE TITLE
Resistor Color Trio: add test case >1000 but not divisible by 1000

### ISSUE THREAD

**Issue by qsharoly** [exercism/problem-specifications#1989]
Currently some solutions check if resistance value is >= 1000 and use integer division to switch to kilo-ohms, which causes loss of precision for values that are larger than 1000, but are not divisible by 1000.

This testcase will ensure divisibility by 1000 before transitioning to kilo-ohms.
```
{
  "description": "Red and red and red",
  "property": "label",
  "input": {
    "colors": ["red", "red", "red"]
  },
  "expected": {
    "value": 2200,
    "unit": "ohms"
  }
},
```

**Comment by SaschaMann** [comment]
This is effectively a duplicate of #1651 / #1652

**Comment by qsharoly** [comment]
Oops
