### ISSUE TITLE
New case for secret-handshake

### ISSUE THREAD

**Issue by glennj** [exercism/problem-specifications#2000]
I think we could use a new test for secret handshake: the code is > 31 but code & 16 == 0 -- the instructions read that reversing should only occur if bit 5 is set, but I've seen submissions where reversing happens if the given code is simply more than 31

For example, if the code is 35 (0b100011), then the result should be the non-reversed ["wink", "double blink"]

**Comment by ErikSchierboom** [comment]
Sounds like a good addition. Would you be interested in submitting a PR?

**Comment by glennj** [comment]
I see from the comments in the [canonical-data](https://github.com/exercism/problem-specifications/blob/main/exercises/secret-handshake/canonical-data.json) that this has been previously discussed.

Closing.
