### ISSUE TITLE
State of tic tac toe has a flawed test case, O has made one two many moves.

### ISSUE THREAD

**Issue by chriseyre2000** [exercism/problem-specifications#2030]
Finished game where X won via middle row victory

Given that the board is
```
O.O
XXX
.O.
```

and the X starts the game this is an invalid state.
I suggest removing one of the O's

**Comment by glennj** [comment]
This is the point of the test case: the program has to detect this is an invalid board.

**Comment by angelikatyborska** [comment]
@glennj I thought so too after reading the issue first, but after looking closer I realized that @chriseyre2000 feedback is about one of the earlier tests that are supposed to detect winning conditions of a valid board, this one: https://github.com/exercism/problem-specifications/blob/e50799aae0a39972418f2728d3fca9178b552560/exercises/state-of-tic-tac-toe/canonical-data.json#L99-L109

**Comment by chriseyre2000** [comment]
I found it because I started implementing stronger checks for invalid boards.
X goes first so there can only ever be one less O on the board if X wins (and the same number of X's as O's if O wins).

**Comment by chriseyre2000** [comment]
I have raised this PR: https://github.com/exercism/problem-specifications/pull/2031
