### ISSUE TITLE
Missing-test case for exercise Luhn

### ISSUE THREAD

**Issue by eklatzer** [exercism/problem-specifications#2054]
Hey, when mentoring [Luhn](https://exercism.org/tracks/go/exercises/luhn) and playing a bit around with my solution and when checking community solutions, I have found out that there is not test-case covering the following problem. The requirement is: If the sum is evenly divisible by 10, then the number is valid. The test-cases also pass, if for example `sum%2==0` or `sum%5==0`  (both divisors of 10) are used instead of `sum%10==0`. 

Here are some examples of test-cases that would cover this problem:
Testcase 1: `3 1 6 3 5` covers `sum%2==0` 
```
Input:
3 1 6 3 5
Find out every second digit:
_ 1 _  3 _
Doubling every second digit and subtracting 9 if greater than 9:
_ 2 _  6 _
Results in:
3 2 6 6 5
Sum: 3 + 2 + 6 + 6 + 5 = 22
```
Testcase 1: `3 1 9 3 5` covers `sum%5==0`
```
Input:
3 1 9 3 5
Find out every second digit:
_ 1 _  3 _
Doubling every second digit and subtracting 9 if greater than 9:
_ 2 _  6 _
Results in:
3 2 9 6 5
Sum: 3 + 2 + 9 + 6 + 5 = 25
```
If the test-cases should be added, reach out to me and I will directly implement the cases:
```
	{
		"invalid because sum is not evenly divisible by ten",
		"3 1 6 3 5",
		false,
	},
	{
		"invalid because sum is not evenly divisible by ten",
		"3 1 9 3 5",
		false,
	},
```

**Comment by petertseng** [comment]
It is my expectation that the existing case named already rejects solutions that use `% 2`.

https://github.com/exercism/problem-specifications/blob/05999f34ab02857c8630507c0baef797bca96672/exercises/luhn/canonical-data.json#L67-L75

If this expectation is wrong, please explain.

We don't have a case that rejects solution that use `% 5`. One should be added.

**Comment by petertseng** [comment]
It is my expectation that the existing case named "invalid long number with an even remainder" already rejects solutions that use `% 2`.

https://github.com/exercism/problem-specifications/blob/05999f34ab02857c8630507c0baef797bca96672/exercises/luhn/canonical-data.json#L67-L75

If this expectation is wrong, please explain.

We don't have a case that rejects solution that use `% 5`. One should be added.

**Comment by andrerfcsantos** [comment]
@eklatzer Some test cases that were added here for this exercise were not yet synced to the Go track. That is one of them. If this change gets merged we can take care of this then. If for your tests you need a go test file that contains the most recent tests, you can use this one: [cases_test.go.zip](https://github.com/exercism/problem-specifications/files/8879023/cases_test.go.zip).

**Comment by petertseng** [comment]
Confirmed that `1 2345 6789 1234 5678 9013` and `3 1 9 3 5` will both reject `% 5`.

To close this issue, an interested contributor should add one of those two cases (it is that contributor's choice which one to add) to https://github.com/exercism/problem-specifications/blob/main/exercises/luhn/canonical-data.json. It would be appropriate to put it immediately after "invalid long number with an even remainder", I would think. That contributor should include at minimum three things in the commit message:

* prefix the commit message with `luhn:`
* explain that the new case rejects solutions that use `% 5`
* use a word in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue to indicate that that commit closes this issue

**Comment by eklatzer** [comment]
I have added the test case now. Have I done it, how it is expected to do?

**Comment by ErikSchierboom** [comment]
@eklatzer Almost. See https://github.com/exercism/problem-specifications/pull/2056#issuecomment-1154820391
