### ISSUE TITLE
[Suggestion] Rename the Beer Song to Ten Green Bottles

### ISSUE THREAD

**Issue by habere-et-dispertire** [exercism/problem-specifications#2066]
Please consider that the normalization of excessive alcohol consumption is a widespread systemic issue. I ask for a greater awareness around alcoholism. I feel a broader sensitivity toward alcohol consumption per se is warranted (eg for learners on Exercism that are alcoholics in remission, survivors of alcoholic abuse or Muslim).

The original song is apparently [Ten Green Bottles](https://en.wikipedia.org/wiki/Ten_Green_Bottles).

**Comment by ahsf** [comment]
99 bottles has to stay.

https://www.99-bottles-of-beer.net/

**Comment by glennj** [comment]
Plus, Katrina's book: https://sandimetz.com/99bottles

**Comment by iHiD** [comment]
@habere-et-dispertire Let me know if this is something you're interested in doing, or whether I should close this issue. Thanks 🙂

**Comment by habere-et-dispertire** [comment]
A heartfelt thank you to everyone for your help in transforming cathexis into catharsis. <3
