### ISSUE TITLE
Triangle: Bug allows faulty solution to be accepted

### ISSUE THREAD

**Issue by krion7** [exercism/problem-specifications#2072]
Hello,

I have encountered a bug on the Python exercise of `Triangle`, however it seems to affect other language tracks as well, per my observation at `exercises/triangle/canonical-data.json`. The bug only pertains to the scalene part of the exercise.

This is how the bug goes. (I will be demonstrating it using Python; sidenote: I am quite new to coding and GitHub as well, so please excuse me.) Say, we've got a code like this:
```
def scalene(sides):
    a, b, c = sides
    return valid_triangle(sides) and a != b != c
```
That code is accepted as a valid solution when verified with current test cases. However, this code **shouldn't be a valid solution** because of this:
```
>>> scalene([2, 3, 2])
True
```
Of course, a triangle with lengths of 2, 3, and 2 is **not scalene**, since a scalene triangle has **all sides of different lengths**, but it is recognized as such by that faulty code.

Now, there is no such test case in the current test cases that is identical to `scalene([2, 3, 2])`. That is how faulty codes like the one shown above is incorrectly accepted as valid. So, I recommend adding a new test case akin to `scalene([2, 3, 2])`.

Thanks as always for your continuous work and contributions to Exercism!
(If needed, [this is the issue I opened at the Python Exercism repo](https://github.com/exercism/python/issues/3134#issue-1297628449))

**Comment by petertseng** [comment]
That case should be added.

When adding that case **do not remove** the existing case `c6e15a92-90d9-4fb3-90a2-eef64f8d3e1e "two sides are equal" [4, 4 ,3]`. Instead, change the description of the existing case to be "two long sides are equal". The description of this new added case should be "two short sides are equal". (Or any two descriptions that make clear the difference between these two cases).

**Comment by SleeplessByte** [comment]
@krion7 would you like to (try to) PR this in this repository? We'll help getting the PR to the right state before it's merged. Your request change is very welcome.
