### ISSUE TITLE
collatz-conjecture: test positive but invalid values

### ISSUE THREAD

**Issue by gabo-cs** [exercism/problem-specifications#2103]
The tests are missing a really cool scenario, that is, numbers less than one and any decimal number actually.

With the existing error cases (`0` and `-15`), a `raise if n  < 1` does the trick and students wouldn't even think of an `is_integer` check, but we know the Collatz Conjecture wouldn't like that.

From a mentoring discussion with @kotp :

> The tests that exist are not enforcing that we use only valid numbers, it only touches on zero and negative numbers, but it is not inclusive of the numbers that are not valid.

So how about something like this?

```
{
      "description": "positive value but less than one is an error",
      "comments": ["Collatz Conjecture holds only for positive integers"],
      "property": "steps",
      "input": {
        "number": 0.5
      },
      "expected": {
        "error": "Only positive integers are allowed"
      }
    }
```

**Comment by kotp** [comment]
Only positive natural numbers, or something to indicate the lower limit of 1 specifically, and an integer or equivalent.

**Comment by kytrinyx** [comment]
I think this is a nice addition, but we would need to add a `scenarios` field so that languages that have strict typing for input could skip this test.

**Comment by kytrinyx** [comment]
I've mulled over this a bit.

I really don't think that adding cases for floats make this exercise more interesting, since the collatz conjecture is specifically about _integers_.

I think that it's great to discuss during a mentoring session if it comes up, but I don't think that it warrants having an extra test case for something that is not an integer.

**Comment by kotp** [comment]
I agree the discussion is good.  Having the test would likely not have the opportunity for the idea to surface in mentoring.

**Comment by ErikSchierboom** [comment]
There is often a natural tendency to try and cover as many of the error cases as we can. This is totally understandable, as we have been trained to consider edge cases and such and to cover them with tests. The key thing about the problem-specifications exercises though is that they are meant to have students practice their programming skills, but not in a professional setting. This means that things like DRY or exhaustive error testing don't necessarily apply to exercises within problem-specifications, while those would be very useful in a professional environment.

Applying this to the suggestion made by OP, I think there is relatively little benefit to be gained from adding a test case for non-integer numbers. [The problem itself](https://en.wikipedia.org/wiki/Collatz_conjecture) says it only applies to positive integers, so I'm fine with us only covering the integer domain.

Thanks for taking the time to open the issue though! It is not always obvious why exercises are designed as they are.
