### ISSUE TITLE
[Question] Location of problem description PNG images

### ISSUE THREAD

**Issue by habere-et-dispertire** [exercism/problem-specifications#2142]
The markdown of the `killer-sudoku-helper` exercise references three [PNG images](https://github.com/exercism/problem-specifications/blob/main/exercises/killer-sudoku-helper/description.md) which appear to live on the `v3-files` repository under [julia](https://github.com/exercism/v3-files/tree/main/julia/killer-sudoku-helper).

It feels like these files should live closer to the markdown, perhaps here with the problem-specifications, no?

**Comment by habere-et-dispertire** [comment]
These three files are about 10% of that metric (at ~100KB each), and can be reduced further to roughly 1% (at 10KB each) with compression. The main saving comes from a reduction in the colour palette.

If this is wanted, I can patch them to `v3-files` under `julia` if that is still how we want to keep this. I was concerned about making changes which appeared specific to `julia` when it applied to the exercise in general and I also wasn't sure what the repercussion was of changing files in the `v3-files` repo.

**Comment by ErikSchierboom** [comment]
I think Sascha pushed for us to use Git LFS, but I don't think we actually use it? I'm not sure though. @iHiD might know

**Comment by iHiD** [comment]
I believe that things just link directly to the images hosted on that repo. `v3-files` uses Git LFS, so things need to be pushed via that I bleieve.

**Comment by habere-et-dispertire** [comment]
I can't get Git LFS working. I can attach the compressed files here, but then that makes more work for others and I'm aware of the "pause". Shall I attach them or just close? Happy either way. :-)

**Comment by habere-et-dispertire** [comment]
I'm leaving the reduced files here if case someone wants them. It's ~87% file size reduction from the originals, coming in at ~15KB each.

## Example 1

![example1](https://user-images.githubusercontent.com/18032974/210911117-cf743925-39b9-48f0-ab04-3cd91262ca76.png)

## Example 2

![example2](https://user-images.githubusercontent.com/18032974/210911121-ed74a554-4c33-4d86-9e98-b1509eb1b48a.png)

## Example 3

![example3](https://user-images.githubusercontent.com/18032974/210911123-dfaf5983-39cf-4783-bf01-b6aa0768bd39.png)
