### ISSUE TITLE
Add Annalyn's Infiltration exercise to Racket

### ISSUE THREAD

**Issue by chip** [exercism/problem-specifications#2184]
I'd be willing to take a stab at converting this exercise over from the Clojure track to Racket if this is approved. Thanks.

**Comment by SleeplessByte** [comment]
@chip you would want to mention this on the forum under Racket or on GitHub at https://github.com/exercism/racket

**Comment by chip** [comment]
@SleeplessByte - Thank you for pointing me in the right direction.
