### ISSUE TITLE
Matching brackets - unclear wording

### ISSUE THREAD

**Issue by michallepicki** [exercism/problem-specifications#2187]
> Given a string containing brackets [], braces {}, parentheses (), or any combination thereof, verify that any and all pairs are matched and nested correctly.

I thought this means the string will contain ONLY brackets braces or parentheses and was disappointed when my solution didn't pass the tests

**Comment by SleeplessByte** [comment]
@michallepicki do you have a better wording?

**Comment by kytrinyx** [comment]
I like the second one a lot. It feels very clear to me.
