### ISSUE TITLE
Introduction text for “Bottle Song” contains incorrect phrasing: "One green bottles"

### ISSUE THREAD

**Issue by kareila** [exercism/problem-specifications#2191]
I believe this text is located in `exercises/bottle-song/description.md` but may also be reflected elsewhere.

I just finished this exercise on the Perl 5 track, where "One green bottle” (which is correct) is actually what was needed to pass the tests. Only the introduction text was wrong.

**Comment by kareila** [comment]
Okay, here’s where I see it on the site: https://exercism.org/tracks/perl5/exercises/bottle-song - in the last few lines of the instructions.

I must have been looking at an older version of the code when I first searched your repository, because it looks like the file I mentioned was fixed here: https://github.com/exercism/problem-specifications/pull/2136/commits/5dece22ba78acc3c80d39431d9dae5fb18ed586d

But after seeing your response, I discovered that the perl5 page must be referencing this file instead: https://github.com/exercism/perl5/blob/main/exercises/practice/bottle-song/.docs/instructions.md

**Comment by glennj** [comment]
It seems that perl5 exercise was created before https://github.com/exercism/problem-specifications/pull/2136 and the perl5 exercise has not been subsequently refreshed.

**Comment by kytrinyx** [comment]
I've gone ahead and created a PR that updates all the docs here:
https://github.com/exercism/perl5/pull/520

And one for the metadata here:
https://github.com/exercism/perl5/pull/521

**Comment by kytrinyx** [comment]
@kotp the failing checks don't seem to have anything to do with the PRs they in question. Since you are familiar with the track, would you please explain what needs to be done to get them passing?

**Comment by kytrinyx** [comment]
I'm going to go ahead and close this as "resolved" since all the tracks can update their data using configlet.

Thanks everyone.

**Comment by kotp** [comment]
Thank you, @kytrinyx , I had the same thought, that yes, they have nothing to do with the failing checks, I just don't have access to force bringing it in, so had to budget time to do the same as you seem to have done. (Having some issues with the YAML package, but have been able to put it off until now.)
