### ISSUE TITLE
secret-handshake: "commands" `property` doesn't seem to fit its theme/story

### ISSUE THREAD

**Issue by petertseng** [exercism/problem-specifications#2210]
In this issue I posit:

* secret-handshake's "commands" `property` doesn't seem to fit its theme/story
* but this is not important enough to take action on
* therefore I am closing this issue immediately upon filing it

---

Secret handshake's https://github.com/exercism/problem-specifications/blob/main/exercises/secret-handshake/description.md frames the story as a cohort of people who know binary and come up with a secret handshake. Then, the https://github.com/exercism/problem-specifications/blob/main/exercises/secret-handshake/canonical-data.json tests the "commands" `property`.

I found "commands" not to fit this story because I am not a general commanding my armies. A command seems like an order I give to my inferiors. But, since this is a cohort of people and we worked together to come up with this secret handshake, I think I would be in the mindset of treating them as equals, not inferiors to be ordered around.

But, even though I think "commands" is a poor fit, since we are not allowed to change the `property`, I think this is not worth taking action on. It would need `reimplement`ing all the cases. It's unimportant because nothing enforces that the `property` appears in any way in individual tracks. If you're like me and you think "commands" doesn't fit the story, fine, you have a clear option: to change it to be a more appropriate word in an individual track's tests. For example, you might choose to use "actions" instead.

Since I think this is not important enough to take action on or even to discuss, to respect everyone's time I am going to close this issue as soon as I open it.

**Comment by kytrinyx** [comment]
@petertseng Thanks for adding this, so we have it in the history.

I agree on both accounts: `commands` isn't a good description ("action", I think, would be better). But also I agree that reimplementing all the test cases to replace the property name is a bit heavy-handed and probably overkill.

I think you're right that having tracks override the name themselves is the right way to go.
