### ISSUE TITLE
Use consistent writting styles for Special blocks

### ISSUE THREAD

**Issue by meatball133** [exercism/problem-specifications#2229]
The instructions of the exercises are currently being rewritten, they have started to impliment Special blocks, which can be found here: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions . 

These updated docs have sometimes been using four tildas or three backticks. I would personally prefer if the writting style is consitent on the problem spec repo. I am not saying to do one way or the other, but just that that there is 1 style instead of 1 exercise doing it one way and another exercise doing it another way.

**Comment by kytrinyx** [comment]
@meatball133 are there exercises in main that use backticks instead of tildes for special blocks?

I submitted a PR where I thought I fixed them all. https://github.com/exercism/problem-specifications/pull/2224

**Comment by meatball133** [comment]
No your pr fixed all of them, I didnt check If there were any prs around it. Silly me
