### ISSUE TITLE
"Hello World" description: is "so that it produces the string" misleading?

### ISSUE THREAD

**Issue by hunkyjimpjorps** [exercism/problem-specifications#2339]
[Based on something that I brought up on the Racket track a while back](https://github.com/exercism/racket/pull/257), I think the hello-world objective "Modify the provided code so that it produces the string "Hello, World!" is potentially misleading -- the code isn't itself producing "Hello, World!" when it's run, it's the test runner that's checking the return value.

I suggested changing Racket's description to "so that the function returns the string" instead, but the track maintainer suggested I bump it up a tier and bring it up here instead, to see if there's some language or clarification that'd be potentially better for all tracks.

**Comment by glennj** [comment]
duplicate of #1850
