### ISSUE TITLE
Variability of expected output in errors in Hamming exercise

### ISSUE THREAD

**Issue by GroophyLifefor** [exercism/problem-specifications#2401]
A friend of mine who contributed with the Hamming exercise received errors in two places during the test phase and we actually corrected it quickly, but we talked about something and he had a complaint, he found it wrong that the expected output was different in the error case and I agreed with him

Passed fail cases:
- disallow second strand longer
  expected: left and right strands must be of equal length

Failed test cases:
 - disallow left empty strand
  expected: left strand must not be empty
 - disallow right empty strand
  expected: right strand must not be empty

The code was able to recognize the error and print an output, but we found it pointless to specify this variation of the error, because if I can give the error message, I've already made it that far, so different error outputs are meaningless. 

canonical-data: https://github.com/exercism/problem-specifications/blob/main/exercises/hamming/canonical-data.json
ref: sintrode

**Comment by IsaacG** [comment]
Please use the forum to discuss changes to the problem specs. Please be sure to read the relevant docs and directly address key points there. 

https://exercism.org/docs/community/being-a-good-community-member/suggesting-exercise-improvements
