### ISSUE TITLE
Improve the description of square root problem

### ISSUE THREAD

**Issue by Ashvith10** [exercism/problem-specifications#2415]
Continued from exercism/c#967

The test case for the square root problem indicates that it was made only for perfect squares. This is also hinted by the fact that the C track uses `uint16_t` and not `float_t` or `double_t`. However, this important detail is not mentioned in the description. I think that letting the learners know that the argument will be perfect squares would improve the quality of the question and reduce the cognitive load.

**Comment by BNAndras** [comment]
Generally, the test suite is what students should consult for what's being requested. With that out of the way, do you have some proposed text for mentioning the perfect squares in the instructions? It doesn't have to be anything polished, but it'll give us a starting point and we can fine-tune it collaboratively.

**Comment by IsaacG** [comment]
Please continue any proposals/discussions on the forum.

**Comment by Ashvith10** [comment]
@BNAndras and @IsaacG I've created a post on the [forum](https://forum.exercism.org/t/improve-the-description-of-square-root-problem/10610). The idea is that instead of natural radicand, we should let the learners know that we are looking for perfect square randicand.

**Comment by tasxatzial** [comment]
Looks like [#2495](https://github.com/exercism/problem-specifications/pull/2495) resolved this.
