### ISSUE TITLE
[binary-search]: Do not implement it for linked lists

### ISSUE THREAD

**Issue by NobbZ** [exercism/problem-specifications#244]
In exercism/xelixir#176 (and issues/discussion outside of exercism) there is an agreement on the fact that a binary-search is less efficient than a linear search, since a linked list does need to iterate over the list up to the n-th element for indexed access on n. Also in many implementations we need to iterate the full list to get it's length. Also when the searched element is in the first half of the list, it is necessary to copy it for the recursive call.

Aside from elixir, I already took a look into the tracks that have binary-search available at the moment (http://x.exercism.io/v3/problems/binary-search/todo).

As far as I can tell, most of the tracks are relying on an array-like datastructure, having all elements in a consecutive range of memory. But I haven't touched the languages in question for more than a hello world (or not at all), so I can't tell exactly. But for clojure I'm pretty sure it is using a linked list as well.

Also by filing this issue, I want to try to warn all other tracks that haven't implemented binary-search so far, but also don't have an appropriate datastructure.

**Comment by soniakeys** [comment]
Practical binary search requires constant-time indexing, which a linked list does not provide.  So a good solution would not use a linked list and the test program should not require a linked list solution.  But the fact that linked lists are available in Elixir surely does not imply the absence of any constant-time indexed data structure or the impossibility of creating one!  I've never tried Elixir but at a quick glance, tuples look like they have constant time indexing and so it might be appropriate to implement binary search on a tuple.  It also looks like Erlang arrays are available, which would also seem suitable and, I have no idea, but perhaps more idiomatic?  Looks like there are maps.  Lua for example gets by with just maps.  A map of indexes to values would seem to be a basis for a valid solution as well.  I would encourage a little more study and perhaps a rewrite of the test program before declaring that the exercise is not suitable for Elixir or any other language.

**Comment by NobbZ** [comment]
Of course there are constant time DS available in Elixir, but using a Tuple (in fact they are C-arrays at the end) for sequential data is all but idiomatic elixir, the more idiomatic way to use Tuples in elixir is as anonymous or tagged record.

Using erlangs arrays isn't idiomatic either (at least after José Valim), as he never has used them (give me two or three days and I might even give a link to the quote). Also erlang arrays aren't read in O(1), they are O(log n) (IIRC) because of their structure as beeing nested tuples, where n is the size of that array. So one could still assume indexed access beeing constant throughout a binary search, since the array probably won't change in its shape.

Also I did not say, that Elixir isn't a good language for this exercise, I just told that I have seen the problem there for the first time. The subject line does clearly state "linked lists" not elixir.

Also I did some research, If I hadn't I had just blindly implemented something that reads like a binary search on the first glance but is quite ineffective, since we all know that a linear search is one of the most efficient in a linked list.

In general this issue was created for the following reasons:

1. Make current and future track maintainers aware of the problem
2. Find out which languages do actually implement a linked list version (as I already told in the OP, im not proficient in the other languages, so I can only guess that most of the
3. Discuss the stuffm are doing it right, but can't proof it)
4. Find common sense in how to continue with this problem in tracks that have done it “wrong”. For elixir this were either to keep it as it is (bad), rewrite it beeing inidiomatic (even worse) or deprecate it (can't really evaluate this one).

**Comment by soniakeys** [comment]
Notes for people who might implement or maintain a test program might be useful, and I don't know of an established place for this.  The issue tracker probably isn't best.  Maybe the .yml file?  In this case a note might caution that the test program must not require a data structure with O(n) index time, and that ideally index time should be O(1).  It could go into more detail or it could reference issues like this where there was discussion.

A note in the .yml might also list languages that elected to not implement the problem.  Again, it might explain or it might reference other notes or discussions on why it was not implemented for a language.  Such a list probably shouldn't be considered definitive - the config.jsons in the tracks specifiy the problems implemented and skipped - but the .yml would be a useful place to leave a note for future maintainers.

**Comment by kytrinyx** [comment]
Yeah, the `.yml` file would be great for this. I think we could use it for a lot more than we do.

Maybe that is where we should put notes to developers instead of in the JSON, which has been our default up until now.

**Comment by soniakeys** [comment]
In the .json that has the common test data?  That seemed a good place for notes about why the test data is the way it is.  But this issue about a linked list data type being inappropriate for binary search is a little different.  This isn't related so much to the test data as to the test program.  Hmm, maybe I'm splitting hairs and it would simpler to collect all these notes for track maintainers in one place.  Maybe the yaml would be a little cleaner and easier to maintain, with its block strings?  (I think it was me that started putting notes in the .json.  I really don't remember if I considered using the .yml.  Probably since at the time I wanted to add notes about the test data, I simply first thought of putting the notes right in the data files.  Or possibly I was just minimizing the number of files I touched.)

**Comment by kytrinyx** [comment]
It never occurred to me to use the yaml until this conversation.

You're right that notes about tests are different from notes about the problem itself. I don't know if it would get confusing to have notes in two places, but it seems like a reasonable thing to try out.

**Comment by petertseng** [comment]
we've done all we can. it's in the https://github.com/exercism/problem-specifications/blob/caa1c6691736c1b8ddb4dd72c690825c70bd4151/exercises/binary-search/canonical-data.json#L13-L16

an interested individual could go audit all implementing tracks to see if they use the appropriate data structures, and file issues in any tracks in which it is relevant to do so.

An interesting philosophical question is whether it is anyone's *obligation* to do that. Given it's a volunteer project, it's hard to imagine on what grounds something could be an *obligation*.

I propose that this issue is only interesting to keep open if we have a remaining obligation to take some action.

By the way, here are all the implementing tracks of this exercise at the current point in time. (the number is the difficulty)

```
$ ruby implementing-tracks.rb exercises/binary-search                                      (11-30 23:32)
          c  2  https://github.com/exercism/c/tree/master/exercises/binary-search
    clojure  1  https://github.com/exercism/clojure/tree/master/exercises/binary-search
     csharp  3  https://github.com/exercism/csharp/tree/master/exercises/binary-search
     delphi  3  https://github.com/exercism/delphi/tree/master/exercises/binary-search
     elixir  3  https://github.com/exercism/elixir/tree/master/exercises/binary-search
        elm  3  https://github.com/exercism/elm/tree/master/exercises/binary-search
     fsharp  3  https://github.com/exercism/fsharp/tree/master/exercises/binary-search
         go  5  https://github.com/exercism/go/tree/master/exercises/binary-search
     groovy  4  https://github.com/exercism/groovy/tree/master/exercises/binary-search
       java  6  https://github.com/exercism/java/tree/master/exercises/binary-search
 javascript  7  https://github.com/exercism/javascript/tree/master/exercises/binary-search
     kotlin  6  https://github.com/exercism/kotlin/tree/master/exercises/binary-search
        lua  4  https://github.com/exercism/lua/tree/master/exercises/binary-search
objective-c  4  https://github.com/exercism/objective-c/tree/master/exercises/binary-search
      ocaml  4  https://github.com/exercism/ocaml/tree/master/exercises/binary-search
      perl5  1  https://github.com/exercism/perl5/tree/master/exercises/binary-search
        php  3  https://github.com/exercism/php/tree/master/exercises/binary-search
 purescript  1  https://github.com/exercism/purescript/tree/master/exercises/binary-search
     python  1  https://github.com/exercism/python/tree/master/exercises/binary-search
   reasonml  4  https://github.com/exercism/reasonml/tree/master/exercises/binary-search
       ruby  5  https://github.com/exercism/ruby/tree/master/exercises/binary-search
       rust  4  https://github.com/exercism/rust/tree/master/exercises/binary-search
      scala  3  https://github.com/exercism/scala/tree/master/exercises/binary-search
      swift  3  https://github.com/exercism/swift/tree/master/exercises/binary-search
 typescript  5  https://github.com/exercism/typescript/tree/master/exercises/binary-search
```

**Comment by sshine** [comment]
> In computer science, a binary search or half-interval search algorithm finds the position of a specified input value (the search "key") within an array sorted by key value.

I think that trees and skip lists qualify for having binary searches performed upon them, so I think it really is just the fact that you rule out the one half of your input on each step in the algorithm that characterises a binary search, not the choice of data structure.
