### ISSUE TITLE
Queen Attack Description is wrong

### ISSUE THREAD

**Issue by CameronBarnes** [exercism/problem-specifications#2443]
The Queen Attack Description says 
```white queen is at c5 (zero-indexed at column 2, row 3) and the black queen at f2 (zero-indexed at column 5, row 6)```
But c5 is column 2 row 6, not column 2 row 3. And f2 is column 5 row 3, not column 5 row 6. 
It looks like the 5 in c5 and the 2 in f2 got switched up mistakenly.

**Comment by glennj** [comment]
https://forum.exercism.org/t/queen-attack-description-appears-to-be-wrong/11255
