### ISSUE TITLE
Typescript: test-runner issue

### ISSUE THREAD

**Issue by MMartyn** [exercism/problem-specifications#2467]
I am unable to run the tests for some of the typescript exercises.

For example, on https://exercism.org/tracks/typescript/exercises/two-fer, when I run `corepack yarn test` I get an error in the test-runner.mjs file: 

```
node:child_process:190
  validateString(command, 'command');
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "command" argument must be of type string. Received an instance of URL
    at normalizeExecArgs (node:child_process:190:3)
    at execSync (node:child_process:954:16)
    at file:///Users/..../Exercism/typescript/two-fer/test-runner.mjs:41:5
```

The line in question is: `  : execSync(exercismDirectory)`

**Comment by BNAndras** [comment]
This is an upstream repository for canonical practice exercise data that all tracks use so this isn’t really the best place to troubleshoot a track-specific test runner issue. I’d recommend posting your issue in https://forum.exercism.org/c/programming/typescript/118.

**Comment by MMartyn** [comment]
Yeah the bot told me that and opened it there for me already. Thanks. On Aug 7, 2024, at 5:46 PM, András B Nagy ***@***.***> wrote:﻿
This is an upstream repository for canonical practice exercise data that all tracks use so this isn’t really the best place to troubleshoot a track-specific test runner issue. I’d recommend posting your issue in https://forum.exercism.org/c/programming/typescript/118.

**Comment by SleeplessByte** [comment]
Thank you for reporting. A [forum post was created](http://forum.exercism.org/t/typescript-stopped-working-locally/12330/14) which led to a PR that has since been merged. You should see the change on exercism.org shortly.
