### ISSUE TITLE
D&D exercise says to roll 6 times, but example show 4 throws

### ISSUE THREAD

**Issue by JuDCraide** [exercism/problem-specifications#2509]
The problem specification for the D&D Character exercise says to roll 6 times(line 7 and line 14), but examples(lines 16-21) show 4 throws for each ability: https://github.com/exercism/problem-specifications/blob/main/exercises/dnd-character/instructions.md?plain=1#L14-L21

**Comment by IsaacG** [comment]
There are six abilities, each generated by rolling 4 dice. There are six throws of four dice.
