### ISSUE TITLE
Exercise Proposal: Parsing Math expressions

### ISSUE THREAD

**Issue by jonasbb** [exercism/problem-specifications#292]
I think an exercise about parsing and evaluating mathematical expressions might be interesting.

Are there already language tracks which implement something similar? I think I have not seen something like this in the x-common repository.

The exercise would feature a grammar for expressions which would cover `+ - * /`, identifiers, and constants. The exercise would require two things: parsing the grammar and working with the expression tree.
## Parsing

Parsing of left-recursive grammars is in itself non-trivial and requires a bit of understanding of grammars. The left recursive grammars could be transformed into a right-recursive grammar or the parses uses a bottom-up approach.
It is most likely also necessary to have some simple form of lexer to parse this.

The parser should return an expression tree. Unfortunately I don't think there is a way to write language agnostic test cases for this intermediate representation. There are just too many possibilities in how this could be implemented.
## Tests

I have two distinct tests in mind.
- Implement a pretty printer. It should only use white space at well defined places (e.g. around binary operators) and should be able to print with the minimal / maximal amount of parenthesis.
- Given a mapping of identifiers to values, evaluate the expression to a number.

These tests can also be implemented with idiomatic code for different languages. In ML this can be implemented with structural induction and object oriented languages could use the visitor pattern.

**Comment by IanWhitney** [comment]
Is this similar to [Wordy](https://github.com/exercism/x-common/blob/master/wordy.json), except that instead word-based operators (plus, minus, etc.) you'd be using symbol operators (+, -)?

**Comment by jonasbb** [comment]
Quote from Wordy:
> This means that you calculate as you move forward each step. In other words, you should ignore order of operations. 3 + 2 * 3 = 15, not 9.

I do not think it is really similar. Wordy basically has no grammar. You search for the next word and apply this operator. It only needs a single variable as a state.

My proposal above concerns parsing an input like `a + 5 * 9 + b` into an abstract syntax tree (AST).
```
     +
    / \
   +   b
  / \
 a   *
    / \
   5   9
```
Given an assignment like `a ↦ 2` and `b ↦ 3` there should be a method which calculates the final value of `50`.
The exercise should be more related to programming languages like Forth. However, Forth does not require to parse an AST, similar to Wordy.

**Comment by IanWhitney** [comment]
Ah, I see. 

I think the only way you could get an AST is to make the exercise about returning a structure that is AST-like. I don't think you could write tests that dig into the actual AST (but I could be wrong).

**Comment by kytrinyx** [comment]
> I don't think you could write tests that dig into the actual AST (but I could be wrong).

You might be able to in some languages, but I think that making the exercise about returning a structure that is AST-like would be very interesting.

**Comment by ErikSchierboom** [comment]
@jonasbb Are you still interested on working on this issue?
