### ISSUE TITLE
Possible new exercise: sorting

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/problem-specifications#328]
One exercise I feel missing is one that deals with sorting, one the first, key algorithms one learns when learning to program. My suggestion is to create an exercise that would require the user to implement several sort algorithms, like:
- [Bubble sort](https://en.wikipedia.org/wiki/Bubble_sort)
- [Quicksort ](https://en.wikipedia.org/wiki/Quicksort)
- [Bucket sort](https://en.wikipedia.org/wiki/Bucket_sort)
- [Insertion sort](https://en.wikipedia.org/wiki/Insertion_sort)

Some of the algorithms lend themselves to parallellization, which can make for an additional challenge if people want to give it a try.

I'd be more than happy to show a default implementation and create the relevant exercise files if people think this is a good idea.

**Comment by NobbZ** [comment]
That Algorithms are about sorting not searching. And for searching there is
binary search exercise as well as a binary search tree.

Erik Schierboom <notifications@github.com> schrieb am Mo., 8. Aug. 2016
20:40:

**Comment by ErikSchierboom** [comment]
@NobbZ oh my, I meant sorting :flushed: There is no sorting exercise, is there?

**Comment by NobbZ** [comment]
None that I were aware off ;)

Erik Schierboom <notifications@github.com> schrieb am Di., 9. Aug. 2016 um
09:02 Uhr:

**Comment by ErikSchierboom** [comment]
I shall submit a PR with a proposol for such an exercise then :)

**Comment by ErikSchierboom** [comment]
I'll close this issue, which I'll refer to once I have a PR ready.

**Comment by masters3d** [comment]
Is there one available? If not, I'd like to reopen. Related: https://github.com/exercism/problem-specifications/issues/761
