### ISSUE TITLE
crypto-square: "n empty spaces... should be distributed evenly across the last n rows" is unclear

### ISSUE THREAD

**Issue by matthewfischer** [exercism/problem-specifications#356]
The crypto-square examples and directions do not mention that trailing spaces should be stripped. It instead requires perfect squares which should include trailing spaces. This should be fixed in the README for example, the splunk example should be:

"s-u- "
"p-n- "
"l-k- "

However the output requires no space after the lk pair. This issue is repeated in other ones as well.

Originally filed against the Golang README as https://github.com/exercism/xgo/issues/348

**Comment by kytrinyx** [comment]
@ErikSchierboom @NobbZ @IanWhitney @petertseng @kotp @Insti you're the first ones to come to mind with respect to details on curriculum. Would you mind having a look/think about this one?

**Comment by Insti** [comment]
All spaces are stripped from the input string. From the Readme:
> First, the input is normalized: the spaces and punctuation are removed ...

Then the output is generated as code blocks separated by a single space there should be no trailing space.
> ... output in r-length chunks separated by spaces.

I believe the Go example solution is correct.

**Comment by ErikSchierboom** [comment]
I agree with @Insti, this is mentioned in the README and thus the example is correct.

**Comment by matthewfischer** [comment]
If you remove the trailing spaces it's no longer a perfect square which is
also a requirement right?

**Comment by petertseng** [comment]
> perfect square which is also a requirement right?

[Readme](https://github.com/exercism/x-common/blob/master/crypto-square.md) asks for a rectangle, not necessarily a square. It says `c - r <= 1` so it doesn't have to be a square (it won't be a square if `c - r = 1`)

**Comment by NobbZ** [comment]
As far as I do understand the README, there is no way to have anything in the encoded text that is not matching `/[[:alnum:]]/`, since whitespace and punctuation has to be stripped (personally I do strip all non-printables as whitespace).

I haven't looked at the xgo issue though, I have some problems to read go and currently I do not have the time to try it ;)

**Comment by matthewfischer** [comment]
Stripping the input is not relevant here. The question is on adding back
the filler spaces at the end.

**Comment by Insti** [comment]
There are no filler spaces.
@matthewfischer can you quote the section of the readme that leads you to believe there are?

**Comment by matthewfischer** [comment]
Absolutely. There will always be spaces in the output from what I see. The text says:

> Phrases that fill perfect squares
> `(r X r)` should be output in `r`-length chunks separated by spaces.
> Imperfect squares will have `n` empty spaces.  Those spaces should be 
> distributed evenly across the last `n` rows.

However after re-reading everything I don't see anything that mentions that the output should be a perfect square. Just spaces between segments and spaces filling in to make a rectangle (not a square). So I am indeed wrong in my initial bug report.

**Comment by Insti** [comment]
That text could probably be improved to be more clear. 
Do you have any suggestions for better wording to help remove confusion?

**Comment by matthewfischer** [comment]
Let me think about it it some but to me it seems like the directions could be distilled a bit more. At the root there all you want is essentially spaces between rows and hence never at the end to "fill out" the rectangle. Whether or not they're full rows is immaterial right?

**Comment by Insti** [comment]
The 'fill out' the rectangle is part of an intermediate step.
Maybe it needs to be made more clear that it is a multi-step process?

**Comment by petertseng** [comment]
The way I read the current README at https://github.com/exercism/x-common/blob/master/exercises/crypto-square/description.md -

> Imperfect squares will have `n` empty spaces. Those spaces should be distributed evenly across the last `n` rows.

The value of "n" is unclear. It's `r * c - message_length` (in the example, 56 - 54).

"last `n` rows" is unclear because the "rows" that have one fewer character only appear if you stack up the chunks, and the example of that is only shown after. It's unclear which rectangle (the transposed one or the non-transposed one) the rows refer to.

I recommend clarifying the value of `n`, and saying instead that the last `n` chunks will have one fewer character, without referencing "rows"

**Comment by petertseng** [comment]
> I recommend clarifying the value of `n`, and saying instead that the last `n` chunks will have one fewer character, without referencing "rows"

In the linked PR, the last half of this recommendation (the last `n` chunks will have one fewer character, without referencing "rows") was done.

The first half (clarifying the value of `n`) was not done, but maybe it will be sufficiently understood that `n` is just a variable representing the number of empty spaces.

I guess the second half was more important so I can call it closed.
