### ISSUE TITLE
CryptoSquare: add a test for "perfect square" normalized cipher text

### ISSUE THREAD

**Issue by Trevoke** [exercism/problem-specifications#429]
The part of the readme that talks about how to normalize the cipher text is not very clear, an additional test would be helpful.

**Comment by robkeim** [comment]
A similar issue was discussed in more detail in #356.

**Comment by petertseng** [comment]
Alternatively, we could remove the tests entirely, as #750 suggests.

**Comment by petertseng** [comment]
> Alternatively, we could remove the tests entirely

We did so in #922.
