### ISSUE TITLE
bank-account: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/problem-specifications#554]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Bank Account exercise can be found in the [./exercises/bank-account/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/bank-account for the up-to-date list of
language tracks that have an implementation of the Bank Account exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/docs/blob/master/you-can-help/improve-exercise-metadata.md#extracting-canonical-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/bank-account

**Comment by petertseng** [comment]
I have some specific thoughts about this problem.

Most problems you will see are stateless - write a function, give it some inputs, expect a certain output. All exercises listed in the example section in fact follow that pattern (custom-set is a bit more complex, but fundamentally it still fits into that pattern, just with multiple functoins)

You may find that bank-account doesn't fall into that pattern if it is very stateful - create a bank account, do some things to that bank account, check some state of that bank account.

If it looks like the bank-account tests can't fit well with the examples listed, try looking at what happened in https://github.com/exercism/x-common/pull/488 and https://github.com/exercism/x-common/pull/358 , which were also two very stateful exercises.

(Of course, if you find that bank-account can fit well into the stateless model, then you can ignore everything I've said, no worries!)
