### ISSUE TITLE
parallel-letter-frequency: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/problem-specifications#574]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Parallel Letter Frequency exercise can be found in the [./exercises/parallel-letter-frequency/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/parallel-letter-frequency for the up-to-date list of
language tracks that have an implementation of the Parallel Letter Frequency exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/docs/blob/master/you-can-help/improve-exercise-metadata.md#extracting-canonical-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/parallel-letter-frequency

**Comment by petertseng** [comment]
> I think the real issue with this exercise is how to actually have tests for parallelism.

agreed (comment is from https://github.com/exercism/problem-specifications/issues/1132)

Maker of this file may see if there is any useful information in:

* https://github.com/exercism/haskell/issues/519
* https://github.com/exercism/rust/issues/244
