### ISSUE TITLE
protein-translation: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/problem-specifications#577]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Protein Translation exercise can be found in the [./exercises/protein-translation/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/protein-translation for the up-to-date list of
language tracks that have an implementation of the Protein Translation exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/docs/blob/master/you-can-help/improve-exercise-metadata.md#extracting-canonical-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/protein-translation

**Comment by petertseng** [comment]
Here is a thing to consider for whoever takes this on:

As you will see in #268, we deprecated an exercise called nucleotide-codons in favour of protein-translation. Both these exercises deal with converting codons into protein names.

The exercises worked in slightly different ways, which I summarise but you can see the original analysis at https://github.com/exercism/xrust/issues/267#issuecomment-286613950.

* nucleotide-codons introduced in #93 introduced the concept of compressions.
* protein-translation introduced in #37 acts on multiple codons at once.

When creating the canonical data for this exercise, you should consider which of these two concepts to include.

**Comment by ErikSchierboom** [comment]
Closed by #997.
