### ISSUE TITLE
pythagorean-triplet: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/problem-specifications#579]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Pythagorean Triplet exercise can be found in the [./exercises/pythagorean-triplet/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/pythagorean-triplet for the up-to-date list of
language tracks that have an implementation of the Pythagorean Triplet exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/docs/blob/master/you-can-help/improve-exercise-metadata.md#extracting-canonical-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/pythagorean-triplet

**Comment by TachoMex** [comment]
I will help with this :)

**Comment by cmccandless** [comment]
@TachoMex are you still interested in working on this? You have not yet submitted a pull request.
