### ISSUE TITLE
scale-generator: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/problem-specifications#583]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Scale Generator exercise can be found in the [./exercises/scale-generator/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/scale-generator for the up-to-date list of
language tracks that have an implementation of the Scale Generator exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/docs/blob/master/you-can-help/improve-exercise-metadata.md#extracting-canonical-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/scale-generator

**Comment by abeger** [comment]
I have strong opinions about this problem's tests, so I'd like to take this on.

**Comment by abeger** [comment]
Question: Should I log tickets against the five language tracks to update their implementations now?

**Comment by kytrinyx** [comment]
> Should I log tickets against the five language tracks to update their implementations now?

Sure.

You can script this using the http://github.com/github/hub tool, by the way. I did this recently with the bob exercise:
https://github.com/search?q=org%3Aexercism+%22bob%3A+Lock+problem+description+to+match+current+implementation%22&type=Issues
