### ISSUE TITLE
simple-cipher: Implement canonical-data.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/problem-specifications#586]
We want to have a standard set of test inputs and outputs for each exercise to
make it easier to port them to new languages, as well as to help keep the
exercises in sync.

The Simple Cipher exercise can be found in the [./exercises/simple-cipher/][exercise-dir] directory.

The step-by-step instructions for how to compile a canonical-data.json file is
described in [this section of the contributing guide][contributing].

See http://exercism.io/contribute/canonical-data/simple-cipher for the up-to-date list of
language tracks that have an implementation of the Simple Cipher exercise.

The [tracking issue][tracking-issue] has more context.

[contributing]: https://github.com/exercism/docs/blob/master/you-can-help/improve-exercise-metadata.md#extracting-canonical-test-data
[tracking-issue]: https://github.com/exercism/x-common/issues/552
[exercise-dir]: https://github.com/exercism/x-common/tree/master/exercises/simple-cipher

**Comment by aos** [comment]
Hey I'm working on the first test case here: 
```
it('has a key made of letters', function () {
  expect(cipher.key).toMatch(/^[a-z]+$/);
});
```
How should I define the `input` and `output` properties? I can't put regex in a json file, so I'm not sure what to put.

**Comment by Insti** [comment]
Make up a different key:
`output_regex: "^[a-z]+$"`
Or something, so that the test implementers can work out to do something different for this case.
