### ISSUE TITLE
JSON Schema considerations.

### ISSUE THREAD

**Issue by kotp** [exercism/problem-specifications#700]
As I am doing more research into using schema with JSON, I am finding that perhaps the choice of names for the schema file in the project root would be better named to match the json file being used.

This means, for us, `canonical-data.schema.json`.  This will allow tooling, I believe, to automatically find that schema file and assist in the ways that it may assist while editing and doing auto-completion.

My proposal:

* rename the `canonical-schema.json` to `canonical-data.schema.json`

This will effect work done in #658.

**Comment by tejasbubane** [comment]
The [CLI](https://github.com/jessedc/ajv-cli) that I am using in #658 complains that the source and data parameters are required also does not mention of auto detecting source/data files in the README. Are you proposing this as a general naming convention that we should follow, or am I missing something?

**Comment by rbasso** [comment]
> The CLI that I am using in #658 complains that the source and data parameters are required

Could you please give me more details about this, @tejasbubane?

**Comment by kotp** [comment]
For that tool, yes it does not take the name of the json file and look for a pattern to match against a schema.  Perhaps it should, but I am not yet sure that there is such a pattern (I have not searched for this nor read any CFP or ISO documentation on it as of yet).  But I am playing with Atom and the way some of the plugins are written suggests that there have been some work done in this area.

**Comment by ErikSchierboom** [comment]
I think this is a good plan!
