### ISSUE TITLE
queen-attack: should represent positions as array or object, not string

### ISSUE THREAD

**Issue by petertseng** [exercism/problem-specifications#721]
Currently, positions are represented as strings like `"(2, 2)"` in the [canonical data for queen-attack](https://github.com/exercism/x-common/blob/master/exercises/queen-attack/canonical-data.json).

For languages where `(2, 2)` is valid syntax, this seems fine - the test generator will simply be able to interpolate this string wherever it is necessary.

For those languages where it is not valid syntax, it seems like an unusual burden to force test generators for that language to parse the rank and file from the string `"(2, 2)"`.

Consider changing this to an array containing two integers such as `[2, 2]` or an object with explicit keys such as `{"rank": 2, "file": 2}`.

Note that we don't currently decide to use true algebraic notation for these coordinates: #446, so both the rank and file should remain as numbers.

**Comment by rbasso** [comment]
I think that using strings is definitely not a good way to represent tuples in JSON. Number should always be represented as numbers.

👍  for an array or an object.

**Comment by ErikSchierboom** [comment]
Great point! I think having an object would be best as it is the most explicit.

**Comment by jtigger** [comment]
> Note that we don't currently decide to use true algebraic notation for these coordinates: #446, so both the rank and file should remain as numbers.

Nice catch, @petertseng!  In fact, the conclusion from the PR was to specifically _not_ use AN.  Do we have a process for recording exercise-specific "policy"s?

**Comment by petertseng** [comment]
> Do we have a process for recording exercise-specific "policy"s?

Ah, (other than using the policy label, if we should so choose) we had the idea of the philosophy document in #382 - no exercise has yet had one.
