### ISSUE TITLE
Problem suggestion: find words made from a collection of letters

### ISSUE THREAD

**Issue by kotp** [exercism/problem-specifications#727]
@LegalizeAdulthood commented on [Thu Mar 10 2016](https://github.com/exercism/exercism.io/issues/2794)

This is a problem we did at our Salt Lake City Software Craftsmanship meetup:

Given:
- a collection of individual letters, such as the letter tiles in a scrabble game
- a collection of words

Write code to return all possible words that can be formed from the individual letters.

**Example:**

Given:
- the letters 'a', 'b', 'e, 'e'
- the words "a", "an", "baa", "be", "bee", "ebb"

The algorithm returns the words "a", "be", and "bee".

Things to note:
- The collection of letters can include duplicates.
- Each word selected need not consume all of the letters in the collection.
- Each word selected considers the collection of letters separately.  In other words, letters selected to form one word do not impact the letters used to form another word.
- The words selected cannot contain more letters than are in the collection of letters.

---

@kytrinyx commented on [Sat Mar 12 2016](https://github.com/exercism/exercism.io/issues/2794#issuecomment-195818144)

I like this suggestion. @roseaboveit Should we put "new problem suggestions" in the x-common repository?

---

@wobh commented on [Sat Mar 12 2016](https://github.com/exercism/exercism.io/issues/2794#issuecomment-195861894)

A related, though not combinatorial problem: http://thenoisychannel.com/2011/08/08/retiring-a-great-interview-problem.

**Comment by behrtam** [comment]
We already have `scrabble-score` so we could name it `scrabble cheater` 🙈

> To impress your friends in online scrabble you wan't to create a program that takes a scrabble rack as input and returns all valid scrabble words that can be constructed from this rack. If you already solved `scrabble-score` you could even sort them. An example input and output:
 ffiiix -> fifi, fix, if, iff, xi

An englisch word list used for scrabble tournaments ([infos](https://en.wikipedia.org/wiki/Collins_Scrabble_Words)) could be found here: https://www.wordgamedictionary.com/sowpods/download/sowpods.txt

**Comment by ErikSchierboom** [comment]
Sounds like a nice exercise. We do have to be explicit about what are valid words I feel, so some form of list (such as the one proposed by @behrtam) should be provided I feel.

**Comment by kytrinyx** [comment]
Mac has /usr/share/dict/words which contains (webster's?) word list. I wonder what the license on that is.

**Comment by kotp** [comment]
It doesn't even have to be an exhaustive list.  It should be the same list no matter the operating system, and so probably should be one that we provide.  [this article](http://www.slate.com/articles/life/gaming/2014/09/major_scrabble_brouhaha_can_you_copyright_a_list_of_words.html) is an interesting read concerning the word lists for Scrabble, and used by other programs for study and play as well.

**Comment by behrtam** [comment]
We could provide it as web resource (`http://raw.github...`) as most languages and standard libraries should make it fairly easy to perform a http get request. Definitely something that one should learn at some point.

**Comment by kotp** [comment]
But should they learn it in this exercise?

**Comment by Insti** [comment]
The tests for this exercise should contain a small hardcoded set of words, so big dictionaries would seem to be out of scope for this problem.

(But could be suggested as an optional extension?)

**Comment by ErikSchierboom** [comment]
@kotp Are you still interested in pursuing the exercise proposed in this issue?

**Comment by kotp** [comment]
Not at this time.  I already take students down "other language tile sets" in Scrabble if they want to, but do not take them down the anagrams route that this would.

But I wonder if we can close this, yet tag it as "available" as in closed but not denied, in case someone else wants to pick it up and run with it.

Closing it for now.
