### ISSUE TITLE
crypto-square: Remove test of intermediate functions

### ISSUE THREAD

**Issue by behrtam** [exercism/problem-specifications#750]
So, I was just looking at the canonical test data for `crypto-square` and I think it was the first time I saw test data for an exercise that also tested the intermediate steps of the problem like *normalization* or *concatenation of segments*.

Shouldn't those intermediate tests be removed, as it was agreed on in: https://github.com/exercism/discussions/issues/41

They originated from this PR: #250

**Comment by Insti** [comment]
Link to [canonical-data.json](https://github.com/exercism/x-common/blob/master/exercises/crypto-square/canonical-data.json)

**Comment by petertseng** [comment]
Indeed, the Haskell track discussed in https://github.com/exercism/xhaskell/issues/259 and decided not to test intermediate functions, diverging from x-common in https://github.com/exercism/xhaskell/pull/391.

Not saying that all have to take the exact approach the Haskell track took or that any other track should agree with the exact same reasons, but if this data helps make the decision, we are glad to provide it.

**Comment by petertseng** [comment]
Since crypto-square's introduction into the Go track at https://github.com/exercism/xgo/pull/68 the Go track has never tested the intermediate functions. So if x-common goes this route, xgo would become closer to x-common.

**Comment by nholden** [comment]
https://github.com/exercism/problem-specifications/pull/922 was merged, so I think we can close out this issue.
