### ISSUE TITLE
protein-translation: fact mistake readme

### ISSUE THREAD

**Issue by roberthopman** [exercism/problem-specifications#810]
Right now (incorrect):
`There are also four terminating codons (also known as 'STOP' codons);` 

Change to:
`There are also three terminating codons (also known as 'STOP' codons);` 

Facts: [(https://en.wikipedia.org/wiki/Stop_codon)](https://en.wikipedia.org/wiki/Stop_codon)

**Comment by Insti** [comment]
Great, thanks. Do you want to edit the description file and submit a pull request?

https://github.com/exercism/x-common/blob/master/exercises/protein-translation/description.md

**Comment by roberthopman** [comment]
@Insti I'll keep adding more like these while finishing the elixir track. When I'm done, I might decide to fix them all at once. Is this the right documentation to follow while submitting a pr: https://github.com/exercism/docs/blob/master/maintaining-a-track/reviewing-a-pull-request.md

**Comment by Insti** [comment]
> Is this the right documentation to follow while submitting a pr

Probably not, but I've not yet been able to find the correct documentation either :(

**Comment by Insti** [comment]
Maybe: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#pull-request-guidelines

**Comment by Insti** [comment]
Hmm github didn't auto close this after all 😕

**Comment by petertseng** [comment]
Use the presence or absence of the exclamation mark to determine ahead of time whether it would be auto closed

**Comment by petertseng** [comment]
???? I can't find the exclamation mark anymore. My suggestion is invalid...?!?!!?!?

**Comment by petertseng** [comment]
Sigh, fine. Use the presence or absence of the tooltip to determine ahead of time whether it would be auto closed

![image](https://user-images.githubusercontent.com/346181/31092540-9afe5f18-a763-11e7-9d64-2af65a3a95c4.png)
