### ISSUE TITLE
hamming: Update expected errors in canonical data

### ISSUE THREAD

**Issue by Insti** [exercism/problem-specifications#812]
From: https://github.com/exercism/x-common#test-data-format-canonical-datajson
> if an error is expected (because the input is invalid, or any other reason), the value at "expected" should be an object containing exactly one property, "error", whose value is a string.
>     The string should explain why the error would occur.

But the [hamming canonical data](https://github.com/exercism/x-common/blob/master/exercises/hamming/canonical-data.json#L113) has an expected value of  `-1`

Todo: 

Update https://github.com/exercism/x-common/blob/master/exercises/hamming/canonical-data.json to use error objects for the expected value in the error cases:  
e.g.  `"expected"   : { "error": "some helpful message" }`

**Comment by m-a-ge** [comment]
PR #875 has been created

@Insti, could you please review?

**Comment by Insti** [comment]
Hi @m-a-ge, sorry I didn't see this earlier. 
It looks like you and @ErikSchierboom got it sorted out.
Thanks :heart:
