### ISSUE TITLE
config.json: topics capitalization?

### ISSUE THREAD

**Issue by tleen** [exercism/problem-specifications#820]
Doing some config.json updates on the go track and have been taking topics off the [TOPICS.txt](https://github.com/exercism/x-common/blob/24bf2909ac07dfac31dd79f2ca40a4246df651e9/TOPICS.txt) list where they are capitalized. Looking at [the issue](https://github.com/exercism/xgo/issues/345) (common in other tracks too) that kicked off the introduction of topics the example is lowercase. It seems to have opened up an inconsistency of implementation across the tracks:

 Looking at other some repos that have topics in their config.json, its mixed between lowercase (ex. [dlang](https://github.com/exercism/xdlang/blob/master/config.json), [factor](https://github.com/exercism/xfactor/blob/master/config.json), [python](https://github.com/exercism/xpython/blob/master/config.json)) and capitalized (ex. [go](https://github.com/exercism/xgo/blob/master/config.json), [scala](https://github.com/exercism/xscala/blob/master/config.json), [swift](https://github.com/exercism/xswift/blob/master/config.json)).

My question is: does the capitalization matter? Should we pick one and stick with it? If so which one? 

I don't think capitalization matters much but I think consistency does. We should probably pick one and stick with it. If we end up going lowercase TOPICS.txt should be updated to reflect it.

**Comment by Insti** [comment]
Opinions (strength of opinion):

* Topics should be case insensitive. (strong)
* TOPICS.txt should retain current capitalization. (weak)
* Tracks can choose themselves whether to capitalize or not. (strong)
* Cross-track case consistency is not important. (medium)

**Comment by leenipper** [comment]
I favor lower case for the topics in every context.

**Comment by ErikSchierboom** [comment]
I think having one format would not bring huge benefits, but it is nice to be consistent. The actual chosen capitalization doesn't really matter much to me, but lower case seems to be a sensible approach.

**Comment by tleen** [comment]
People are leaning towards lower?

**Comment by robphoenix** [comment]
I'd lean towards lower also.

**Comment by rchavarria** [comment]
I like how @Insti exposed his opinions, so I'll copy the format:

- Topics should be case insensitive. (strong)
- `TOPICS.txt` should retain current capitalization. (weak)
- Tracks can choose themselves whether to capitalize or not. (weak)
- Cross-track case consistency is important. (strong). I'm sorry, but I disagree with @Insti and @ErikSchierboom in this point. I would like to see exactly the same topics (ignoring case) across tracks.
- Tracks should keep punctuation and whitespace (strong): For example, if `TOPICS.txt` says `Control-flow (loops)`, tracks should use: `control-flow (loops)` or `Control-Flow (Loops)` or even `ConTroL-fLow (lOOps)` but never `control_flow_loops`

**Comment by tleen** [comment]
It looks like #167 is going to make this issue moot. Will close. Discussion should continue there.
