### ISSUE TITLE
isogram: spaces and hyphens not described.

### ISSUE THREAD

**Issue by Insti** [exercism/problem-specifications#824]
The [isogram description](https://github.com/exercism/x-common/blob/master/exercises/isogram/description.md) does not mention anything about spaces or hyphens, however the [canoncial-data](https://github.com/exercism/x-common/blob/master/exercises/isogram/canonical-data.json#L51) includes tests with spaces and hyphens.

Either: 
a) Remove the tests with hyphens/spaces.
or
b) Add something to the description about ignoring spaces and hyphens.

**Comment by ErikSchierboom** [comment]
Either option is fine with me.

**Comment by tejasbubane** [comment]
Closed via #912.
