### ISSUE TITLE
hamming: "empty strands" should be first

### ISSUE THREAD

**Issue by NobbZ** [exercism/problem-specifications#827]
Currently the test asks for the distance of two equal strands of length 1. After that different ones, and gets even longer. After the third or fourth tests, most students will have realized that it is best to do a loop or use recursion (or higher order functions).

After realizing this, one gets the empty list for free and will probably not even realize that there was that one test at the end which checks for the empty strands.

Conclusion: At its current position I could remove that test as well and the student wouldn't recognize a difference in the exercise.

Proposal: As an empty list or string is the base case for every recursion over such containers and is also handled as a noop in for-each-like constructs, the most logical position for this test were the first. This would make the student initially aware of this special case and he would not implement it just "by accident". Also a student might realize to use a loop/recursion/higher-order-functions by the second or third test already (so about a test earlier).

**Comment by Insti** [comment]
https://github.com/exercism/x-common/blob/master/exercises/hamming/canonical-data.json

**Comment by ErikSchierboom** [comment]
Good idea! Would you be willing to send a PR to modify the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/hamming/canonical-data.json)?

**Comment by NobbZ** [comment]
I added the `discussion`-label hoping there will be some around this topic, but since there has no-one chimed in so far and vetoed, I think we can remove `discussion` and make it a `good first patch`.

**Comment by katrinleinweber** [comment]
Hello! I presume it doesn't _have_ to be a 1st-time-contributor ;-)
