### ISSUE TITLE
raindrops: readme might be pointing people to a non optimal solution

### ISSUE THREAD

**Issue by stevejb71** [exercism/problem-specifications#828]
Raindrops requires calculating if a given number is divisible by 3,5, or 7.

A few solutions I've seen calculate all factors of the input and then check if 3, 5, or 7 are in that set. That's more work than necessary. I think the exampkes may lead people to do that, e.g.

28's factors are 1, 2, 4, 7, 14, 28.
In raindrop-speak, this would be a simple "Plong".

**Comment by Insti** [comment]
It's helpful to link to the text you're talking about.
[Raindrops description](https://github.com/exercism/x-common/blob/master/exercises/raindrops/description.md)

This issue may have been discussed previously here: https://github.com/exercism/x-common/pull/353

**Comment by stevejb71** [comment]
The "red herring" in the description was seen as a positive feature in the discussion around exercism#353. 

I'll therefore close.
