### ISSUE TITLE
Stale link to CLI CONTRIBUTING.md

### ISSUE THREAD

**Issue by jbodah** [exercism/problem-specifications#835]
Hey, just was reading your contribution docs and noticed a broken link https://github.com/exercism/x-common/blame/8e21ddbf2ede456907d478bb7c47065cb466c83b/CONTRIBUTING.md#L19

**Comment by petertseng** [comment]
Worse, if https://github.com/exercism/cli/commits/master/CONTRIBUTING.md is to be believed, that file has never existed, so the usual approach of "update link to point to wherever the file moved to" does not serve here.

So then, https://github.com/exercism/cli/blob/master/README.md perhaps?

**Comment by kytrinyx** [comment]
Yeah, let's link to the CLI README.
