### ISSUE TITLE
Topics.txt: List of topics in use in various tracks

### ISSUE THREAD

**Issue by tleen** [exercism/problem-specifications#884]
Here is a list of all the topics [I could find](https://github.com/tleen/exercism-config-visualizations). This issue is not the thing in of itself but something I will refer to as I propose changes to the topics list. These are all the topics [normalised to lowercase](https://github.com/exercism/problem-specifications/issues/820) current as of this post.

I will be submitting commits to TOPICS.txt to try and combine/reduce the duplication and outliers in this listing.

| Topic                                       | Count | Track                                                                                                                                 |
| ------------------------------------------- | ----- | ------------------------------------------------------------------------------------------------------------------------------------- |
| strings                                     | 383   | c, cpp, csharp, ecmascript, elixir, fsharp, go, groovy, javascript, lisp, lua, objective-c, ocaml, php, python, r, ruby, scala, swift |
| transforming                                | 200   | csharp, ecmascript, elixir, fsharp, go, javascript, lisp, lua, objective-c, ocaml, php, python, r, scala, swift                       |
| algorithms                                  | 156   | cpp, csharp, dlang, ecmascript, elixir, fsharp, go, javascript, lua, objective-c, ocaml, php, python, r, ruby, scala, swift           |
| integers                                    | 141   | csharp, ecmascript, elixir, fsharp, go, javascript, lisp, objective-c, ocaml, php, python, r, ruby, scala, swift                      |
| mathematics                                 | 133   | c, cpp, csharp, ecmascript, fsharp, go, javascript, lisp, lua, objective-c, ocaml, php, python, r, ruby, scala, swift                 |
| control-flow (loops)                        | 132   | c, cpp, csharp, ecmascript, go, javascript, lisp, lua, php, python, ruby, scala                                                       |
| control flow (loops)                        | 109   | ecmascript, javascript                                                                                                                |
| control flow (conditionals)                 | 102   | ecmascript, javascript                                                                                                                |
| parsing                                     | 101   | cpp, csharp, dlang, ecmascript, fsharp, go, java, javascript, lisp, objective-c, php, r, scala, swift                                 |
| text formatting                             | 97    | c, cpp, ecmascript, fsharp, go, javascript, lisp, lua, objective-c, php, python, scala, swift                                         |
| arrays                                      | 90    | c, cpp, csharp, dlang, ecmascript, go, javascript, lisp, lua, ocaml, php, python, scala                                               |
| lists                                       | 86    | csharp, ecmascript, elixir, fsharp, go, javascript, lisp, objective-c, php, r, scala, swift                                           |
| filtering                                   | 75    | c, cpp, csharp, ecmascript, fsharp, go, javascript, lisp, lua, objective-c, php, python, r, scala, swift                              |
| control-flow (if-else statements)           | 74    | c, csharp, fsharp, go, groovy, lua, objective-c, php, python, scala, swift                                                            |
| exception handling                          | 58    | csharp, ecmascript, fsharp, go, java, javascript, lua                                                                                 |
| maps                                        | 47    | cpp, ecmascript, elixir, fsharp, go, javascript, lisp, objective-c, python, scala, swift                                              |
| recursion                                   | 46    | csharp, ecmascript, elixir, fsharp, go, javascript, lua, objective-c, r, ruby, scala, swift                                           |
| optional values                             | 43    | c, csharp, ecmascript, fsharp, javascript, lua, objective-c, php, python, scala, swift                                                |
| control-flow (conditionals)                 | 40    | cpp, csharp, ecmascript, go, javascript, lisp, ruby                                                                                   |
| searching                                   | 38    | c, csharp, ecmascript, fsharp, go, javascript, lua, objective-c, python, rust, scala, swift                                           |
| regular expressions                         | 32    | ecmascript, go, groovy, javascript                                                                                                    |
| bitwise operations                          | 32    | c, cpp, csharp, ecmascript, fsharp, go, javascript, lisp, lua, objective-c, php, scala, swift                                         |
| classes                                     | 30    | cpp, csharp, dlang, ecmascript, fsharp, java, javascript, lua, php, python, r, scala                                                  |
| logic                                       | 30    | c, cpp, csharp, ecmascript, elixir, fsharp, go, javascript, lisp, lua, python, r, ruby, scala                                         |
| games                                       | 28    | csharp, ecmascript, fsharp, go, java, javascript, lisp, scala, swift                                                                  |
| sorting                                     | 27    | csharp, ecmascript, elixir, fsharp, go, java, javascript, lisp, objective-c, rust, scala, swift                                       |
| dates                                       | 24    | bash, c, cpp, csharp, ecmascript, fsharp, go, groovy, javascript, lisp, objective-c, ocaml, php, scala, swift                         |
| sequences                                   | 24    | csharp, fsharp, go, lisp, php, python, scala, swift                                                                                   |
| maybe                                       | 22    | haskell                                                                                                                               |
| enumerations                                | 21    | csharp, elixir, fsharp, objective-c, php, scala, swift                                                                                |
| time                                        | 21    | cpp, dlang, ecmascript, fsharp, go, javascript, lisp, lua, objective-c, php, python, scala, swift                                     |
| tuples                                      | 20    | csharp, fsharp, scala, swift                                                                                                          |
| equality                                    | 20    | csharp, ecmascript, go, javascript, lisp, rust                                                                                        |
| matrices                                    | 19    | csharp, ecmascript, fsharp, go, javascript, lua, scala, swift                                                                         |
| structs                                     | 19    | c, elixir, go, rust                                                                                                                   |
| randomness                                  | 17    | cpp, csharp, ecmascript, fsharp, go, groovy, javascript, lisp, lua, objective-c, ocaml, php, rust, scala, swift                       |
| pattern recognition                         | 17    | cpp, csharp, ecmascript, fsharp, go, javascript, python, scala, swift                                                                 |
| discriminated unions                        | 14    | fsharp, objective-c, scala, swift                                                                                                     |
| trees                                       | 14    | csharp, elixir, fsharp, go, lua, scala, swift                                                                                         |
| sets                                        | 14    | csharp, ecmascript, fsharp, go, javascript, lua, python, scala, swift                                                                 |
| math                                        | 13    | elixir, groovy, rust                                                                                                                  |
| refactoring                                 | 13    | csharp, fsharp, go, haskell, php                                                                                                      |
| control-flow (if-statements)                | 13    | c, dlang, lua                                                                                                                         |
| control_flow_conditionals                   | 12    | bash, r                                                                                                                               |
| define type                                 | 12    | haskell                                                                                                                               |
| data structures                             | 11    | ecmascript, javascript                                                                                                                |
| generics                                    | 11    | dlang, rust, scala                                                                                                                    |
| struct                                      | 11    | rust                                                                                                                                  |
| floating-point numbers                      | 11    | csharp, ecmascript, fsharp, javascript, lisp, objective-c, php, swift                                                                 |
| memory management                           | 11    | c                                                                                                                                     |
| result                                      | 10    | rust                                                                                                                                  |
| booleans                                    | 10    | c, ecmascript, go, javascript, ocaml, python, r, rust                                                                                 |
| string processing                           | 10    | elixir                                                                                                                                |
| string manipulation                         | 10    | dlang, groovy                                                                                                                         |
| dictionaries                                | 9     | csharp, php, scala                                                                                                                    |
| pattern matching                            | 9     | cpp, elixir, go, python, scala                                                                                                        |
| records                                     | 9     | fsharp, go, swift                                                                                                                     |
| reactive programming                        | 8     | csharp, dlang, fsharp, go, ocaml                                                                                                      |
| looping                                     | 8     | objective-c, swift                                                                                                                    |
| interfaces                                  | 7     | cpp, go, lisp                                                                                                                         |
| structural equality                         | 6     | csharp, fsharp, objective-c, php, scala, swift                                                                                        |
| language basics                             | 6     | dlang                                                                                                                                 |
| library reimplementation                    | 6     | haskell                                                                                                                               |
| stacks                                      | 6     | cpp, csharp, fsharp, go, lua, ocaml                                                                                                   |
| concurrency                                 | 6     | csharp, fsharp, go                                                                                                                    |
| graphs                                      | 6     | csharp, fsharp, go, lua, scala                                                                                                        |
| enum                                        | 5     | rust                                                                                                                                  |
| higher-order functions                      | 5     | dlang, rust                                                                                                                           |
| conditionals                                | 5     | objective-c, rust, swift                                                                                                              |
| functions                                   | 5     | c, cpp                                                                                                                                |
| text_formatting                             | 5     | bash, r                                                                                                                               |
| iterators                                   | 5     | rust                                                                                                                                  |
| str vs string                               | 5     | rust                                                                                                                                  |
| control-flow (foreach)                      | 4     | dlang                                                                                                                                 |
| queues                                      | 4     | csharp, fsharp, go, java                                                                                                              |
| map                                         | 4     | rust                                                                                                                                  |
| control_flow_loops                          | 4     | bash                                                                                                                                  |
| variables                                   | 4     | lisp                                                                                                                                  |
| parallellism                                | 4     | csharp, fsharp, scala                                                                                                                 |
| unicode                                     | 4     | ecmascript, javascript                                                                                                                |
| chars                                       | 4     | rust                                                                                                                                  |
| globalization                               | 4     | csharp, ecmascript, fsharp, javascript                                                                                                |
| callbacks                                   | 4     | ecmascript, javascript                                                                                                                |
| mutable state                               | 4     | haskell, ocaml                                                                                                                        |
| lifetimes                                   | 4     | rust                                                                                                                                  |
| io monad                                    | 4     | haskell                                                                                                                               |
| type conversion                             | 4     | go                                                                                                                                    |
| cryptography                                | 4     | go                                                                                                                                    |
| domain-specific languages                   | 4     | csharp, fsharp, go, scala                                                                                                             |
| filter                                      | 4     | rust                                                                                                                                  |
| vec                                         | 3     | rust                                                                                                                                  |
| pointers                                    | 3     | c                                                                                                                                     |
| either                                      | 3     | haskell                                                                                                                               |
| events                                      | 3     | csharp, fsharp                                                                                                                        |
| files                                       | 3     | csharp, fsharp, python                                                                                                                |
| search                                      | 3     | ocaml                                                                                                                                 |
| functional programming                      | 3     | ocaml                                                                                                                                 |
| string concatenation                        | 3     | rust                                                                                                                                  |
| reduce                                      | 3     | elixir                                                                                                                                |
| option                                      | 3     | rust                                                                                                                                  |
| traits                                      | 3     | rust                                                                                                                                  |
| polymorfism                                 | 3     | ecmascript, javascript                                                                                                                |
| performance optimizations                   | 3     | c                                                                                                                                     |
| entry api                                   | 3     | rust                                                                                                                                  |
| match                                       | 3     | rust                                                                                                                                  |
| str to digits                               | 3     | rust                                                                                                                                  |
| string_comparison                           | 3     | bash                                                                                                                                  |
| string_transformation                       | 3     | bash                                                                                                                                  |
| loops                                       | 3     | rust                                                                                                                                  |
| vector                                      | 3     | rust                                                                                                                                  |
| input_validation                            | 3     | bash                                                                                                                                  |
| from trait                                  | 3     | rust                                                                                                                                  |
| slices                                      | 3     | rust                                                                                                                                  |
| format                                      | 2     | rust                                                                                                                                  |
| fold                                        | 2     | rust                                                                                                                                  |
| associative arrays                          | 2     | dlang                                                                                                                                 |
| algorithm                                   | 2     | rust                                                                                                                                  |
| random                                      | 2     | haskell                                                                                                                               |
| error handling                              | 2     | dlang                                                                                                                                 |
| preprocessor (x-macros in test)             | 2     | c                                                                                                                                     |
| control-flow (case statements)              | 2     | c                                                                                                                                     |
| numbers                                     | 2     | go                                                                                                                                    |
| coroutines                                  | 2     | lua                                                                                                                                   |
| performance                                 | 2     | lua                                                                                                                                   |
| control-flow                                | 2     | dlang, scala                                                                                                                          |
| overloading                                 | 2     | csharp                                                                                                                                |
| counting                                    | 2     | ocaml                                                                                                                                 |
| hashmap                                     | 2     | rust                                                                                                                                  |
| arithmetic                                  | 2     | ocaml                                                                                                                                 |
| primitive types                             | 2     | rust                                                                                                                                  |
| ascii                                       | 2     | rust                                                                                                                                  |
| lazy evaluation                             | 2     | haskell                                                                                                                               |
| functional                                  | 2     | dlang                                                                                                                                 |
| extension methods                           | 2     | csharp, php                                                                                                                           |
| stack                                       | 2     | haskell                                                                                                                               |
| generic over type                           | 2     | rust                                                                                                                                  |
| custom trait                                | 2     | rust                                                                                                                                  |
| vectors                                     | 2     | rust, scala                                                                                                                           |
| loop                                        | 2     | rust                                                                                                                                  |
| string parsing                              | 2     | rust                                                                                                                                  |
| security                                    | 2     | scala                                                                                                                                 |
| protocols                                   | 1     | elixir                                                                                                                                |
| floats                                      | 1     | ocaml                                                                                                                                 |
| boolean_logic                               | 1     | bash                                                                                                                                  |
| dynamic programming                         | 1     | ocaml                                                                                                                                 |
| errors                                      | 1     | go                                                                                                                                    |
| interpreters                                | 1     | ocaml                                                                                                                                 |
| oop                                         | 1     | php                                                                                                                                   |
| optional_values                             | 1     | r                                                                                                                                     |
| floating_point_numbers                      | 1     | r                                                                                                                                     |
| bitwise_ operations                         | 1     | r                                                                                                                                     |
| regular_expressions                         | 1     | r                                                                                                                                     |
| println!                                    | 1     | rust                                                                                                                                  |
| crates                                      | 1     | rust                                                                                                                                  |
| case (or `format`)                          | 1     | rust                                                                                                                                  |
| mutable string                              | 1     | rust                                                                                                                                  |
| nested classes                              | 1     | dlang                                                                                                                                 |
| string functions                            | 1     | rust                                                                                                                                  |
| case                                        | 1     | rust                                                                                                                                  |
| enumeration                                 | 1     | go                                                                                                                                    |
| vector (optional)                           | 1     | rust                                                                                                                                  |
| error_handling                              | 1     | bash                                                                                                                                  |
| delegates                                   | 1     | dlang                                                                                                                                 |
| networking                                  | 1     | go                                                                                                                                    |
| logical operators                           | 1     | groovy                                                                                                                                |
| metaprogramming                             | 1     | groovy                                                                                                                                |
| borrowing                                   | 1     | rust                                                                                                                                  |
| panic                                       | 1     | rust                                                                                                                                  |
| time functions                              | 1     | c                                                                                                                                     |
| modulus                                     | 1     | rust                                                                                                                                  |
| conversion between string and int           | 1     | rust                                                                                                                                  |
| use of primitive char                       | 1     | rust                                                                                                                                  |
| control-flow (loops, switch, if-statements) | 1     | c                                                                                                                                     |
| derive                                      | 1     | rust                                                                                                                                  |
| variable argument lists                     | 1     | c                                                                                                                                     |
| random numbers                              | 1     | dlang                                                                                                                                 |
| template metaprogramming                    | 1     | dlang                                                                                                                                 |
| index (optional)                            | 1     | rust                                                                                                                                  |
| chaining higher-order functions             | 1     | rust                                                                                                                                  |
| hashmap (optional)                          | 1     | rust                                                                                                                                  |
| stdout                                      | 1     | bash                                                                                                                                  |
| ascii (optional)                            | 1     | rust                                                                                                                                  |
| conversions                                 | 1     | dlang                                                                                                                                 |
| mutablity                                   | 1     | rust                                                                                                                                  |
| accumulator-strictness                      | 1     | haskell                                                                                                                               |
| instance num                                | 1     | haskell                                                                                                                               |
| class templates                             | 1     | dlang                                                                                                                                 |
| windows                                     | 1     | rust                                                                                                                                  |
| char                                        | 1     | rust                                                                                                                                  |
| enumerables                                 | 1     | elixir                                                                                                                                |
| binary representation                       | 1     | elixir                                                                                                                                |
| collections                                 | 1     | elixir                                                                                                                                |
| data-structures                             | 1     | dlang                                                                                                                                 |
| btree                                       | 1     | rust                                                                                                                                  |
| function pointer                            | 1     | rust                                                                                                                                  |
| flat_map                                    | 1     | rust                                                                                                                                  |
| date                                        | 1     | lisp                                                                                                                                  |
| control flow                                | 1     | elixir                                                                                                                                |
| while let (optional)                        | 1     | rust                                                                                                                                  |
| mutable                                     | 1     | rust                                                                                                                                  |
| results                                     | 1     | rust                                                                                                                                  |
| enumerate                                   | 1     | rust                                                                                                                                  |
| immutability                                | 1     | rust                                                                                                                                  |
| text parsing                                | 1     | lua                                                                                                                                   |
| string formatting                           | 1     | elixir                                                                                                                                |
| stack or recursion                          | 1     | rust                                                                                                                                  |
| trait (optional)                            | 1     | rust                                                                                                                                  |
| goofy bowling logic                         | 1     | rust                                                                                                                                  |
| associative_arrays                          | 1     | bash                                                                                                                                  |
| formatting                                  | 1     | elixir                                                                                                                                |
| default trait implementation                | 1     | rust                                                                                                                                  |
| bitwise (probably)                          | 1     | rust                                                                                                                                  |
| regularexpressions                          | 1     | objective-c                                                                                                                           |
| encodings                                   | 1     | rust                                                                                                                                  |
| setting up ocaml dev environment            | 1     | ocaml                                                                                                                                 |
| bitwise                                     | 1     | rust                                                                                                                                  |
| unwrap_or                                   | 1     | rust                                                                                                                                  |
| iters                                       | 1     | rust                                                                                                                                  |
| iterating over two lists at once            | 1     | ocaml                                                                                                                                 |
| operators (optional)                        | 1     | rust                                                                                                                                  |
| combinations                                | 1     | rust                                                                                                                                  |
| external crates (optional)                  | 1     | rust                                                                                                                                  |
| encryption                                  | 1     | elixir                                                                                                                                |
| iter                                        | 1     | rust                                                                                                                                  |
| hash map                                    | 1     | rust                                                                                                                                  |
| self mut                                    | 1     | rust                                                                                                                                  |
| lines                                       | 1     | rust                                                                                                                                  |
| chunks                                      | 1     | rust                                                                                                                                  |
| board state                                 | 1     | rust                                                                                                                                  |
| graph theory                                | 1     | rust                                                                                                                                  |
| multi-threading                             | 1     | rust                                                                                                                                  |
| parser reimplementation                     | 1     | rust                                                                                                                                  |
| buffer reimplementation                     | 1     | rust                                                                                                                                  |
| closures                                    | 1     | rust                                                                                                                                  |
| function overloading                        | 1     | scala                                                                                                                                 |
| lenses                                      | 1     | fsharp                                                                                                                                |

**Comment by ErikSchierboom** [comment]
With topics no longer being something we support in Exercism v3, this issue can be closed I think.
