### ISSUE TITLE
circular-buffer: Overwrite operation is not clear

### ISSUE THREAD

**Issue by shaleh** [exercism/problem-specifications#889]
The text says that `The client can opt to overwrite the oldest data with a forced write.` What it does not say is that this is only expected to happen when the buffer is full. The example shows this but the description does not make it clear. Basically overwrite is just write unless the buffer is full.

**Comment by ErikSchierboom** [comment]
@shaleh Would you be interested in creating a PR to fix this issue?

**Comment by shaleh** [comment]
I can do that.

On September 7, 2017 2:36:59 AM PDT, Erik Schierboom <notifications@github.com> wrote:
>@shaleh Would you be interested in creating a PR to fix this issue? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/exercism/problem-specifications/issues/889#issuecomment-327747888

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by shaleh** [comment]
PR uploaded
