### ISSUE TITLE
Expand word-search canonical tests

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/problem-specifications#898]
I feel the canonical test cases could and should be improved, primarily because there are large leaps between one test and the next, and this isn't really helpful for someone trying to practice a TDD approach to solving the exercise.  The existing test cases could do a better job of calling out the patterns the developer is supposed to recognize without asking him or her to mentally solve the entire problem near the beginning of the suite.  

**Most fundamentally, I feel the entry curve of these cases is way too steep and not very "TDD."**  Most of the test cases would be added near the beginning.

I'd like to propose adding the following cases as canonical.  If the maintainers don't feel this is appropriate for the canonical data, I'll simply use them in my EcmaScript implementation, but I feel they would be valuable in any track.

For the sake of brevity I'm going to add only the descriptions of the existing and proposed new test cases, indicating which ones are **new**

**should accept an initial game grid**
**should accept a target search word**
**should locate a word written left to right**
**should locate a left to right word in a different position**
**should locate a different left to right word**
**should locate that different left to right word in a different position**
**should locate a left to right word in a two line grid**
**should locate a left to right word in a different position in a two line grid**
**should locate a left to right word in a three line grid**
**should locate a left to right word in a ten line grid**
**should locate a left to right word in a different position in a ten line grid**
**should locate a different left to right word in a ten line grid**
should locate words written left to right (finds multiple input words)
**should locate a single word written right to left**
should locate words written right to left (finds both left-to-right and right-to-left words)
should locate words written top to bottom
should locate words written bottom to top
should locate words written top left to bottom right
should locate words written bottom right to top left

I appreciate your feedback.

**Comment by Insti** [comment]
Links to the description and canonical-data files would be helpful.

**Comment by Insti** [comment]
More tests is a good idea 👍 

I'd also like to see helpfully human readable tests.
```
......
......
.word.
......
```

**Comment by matthewmorgan** [comment]
@Insti thanks for the feedback.  I was mostly trying to see if expanding the suite was something that  sounded like a good idea, and it seems like that's a yes.

I can create the JSON for my proposed changes and put in a PR so we can discuss the specifics there.   Sound like a plan?

**Comment by Insti** [comment]
> I can create the JSON for my proposed changes and put in a PR so we can discuss the specifics there. Sound like a plan?

Sounds good.
Be mindful of not changing the existing tests too much. (if possible), as it makes reviewing easier.

**Comment by matthewmorgan** [comment]
Yeah, I don't think I plan to change any of the existing ones.  Just additions.

**Comment by Insti** [comment]
I think this was resolved by PR #899
