### ISSUE TITLE
pig-latin tests: 'y' as first vowel in a word (and not first letter).

### ISSUE THREAD

**Issue by pnie** [exercism/problem-specifications#900]
Ther are two rules for letter 'y':
1. when 'y' is first letter of a word (eg. "yellow") - test case exists.
2. when 'y' is first vowel but not first letter of a word (eg. "tyrell") - test case doesn't exists.

**Comment by rpottsoh** [comment]
@pnie interesting find.  Also, interesting that this is Pig Latin month and yesterday (the 15th) was Pig Latin day according to [Wikipedia](https://en.wikipedia.org/wiki/Pig_Latin).

Wikipedia doesn't address `Y` as being a vowel.  I decided to try an online English to Pig Latin translator.  [Fun Translations](http://funtranslations.com/pig-latin) translates "tyrell" to "yrelltay".

@pnie Said:
> Eg. "tyrell" should be "yrelltay" not "elltyay".

I don't consider Wikipedia to be a reliable source, it often is missing details....  The translator I tried agrees with your assesment.  Is there a source you can site that is more thorough than wikipedia that illustrates your find?

I reviewed the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/pig-latin/canonical-data.json) for this exercise and it appears to me that an instance of the `input` starting with `Y` is correctly following the rule you are suggesting.

```
        {
          "description": "word beginning with yt",
          "property": "translate",
          "input": "yttria",
          "expected": "yttriaay"
        }
```

If you are interested in adding a test case to this exercise I encourage you to do so.  However, it might be necessary to site a source that illustrates the rule you are siting.  The canonical-data.json and description.md would need to be updated.  Presently the exercise is following the definition of Pig Latin as it is defined by Wikipedia.

If you decide to open a PR please associate it to this issue.

**Comment by pnie** [comment]
@rpottsoh said:
> I don't consider Wikipedia to be a reliable source, it often is missing details....

I agree, but fortunately article about Pig Latin reference a website with more precise [rules](https://en.wikipedia.org/wiki/Pig_Latin#cite_note-11).

@rpottsoh said:
> Wikipedia doesn't address Y as being a vowel.

Not directly in Pig Latin article, Y has its own page ;-) It is very confusing letter, because it can be a vowel or consonant.
