### ISSUE TITLE
Can I use exercises listed on the website in my own software?

### ISSUE THREAD

**Issue by kmlxn** [exercism/problem-specifications#908]
Hi.
Can I use exercises listed on the website in my own software? I want to translate them to my native language and use them in my software, so that guys can practice and learn programming.

There are not many resources dedicated to programming in my native language, so these exercises can be helpful.

**Comment by Average-user** [comment]
The exercises have sources, i think that maybe depends of that sources.

**Comment by Average-user** [comment]
@kmlxn You could see what you find in here: [http://rosettacode.org/wiki/Rosetta_Code](http://rosettacode.org/wiki/Rosetta_Code), there are many tasks implemented in a lot of programming  languages.

**Comment by kmlxn** [comment]
@Average-user thanks.
