### ISSUE TITLE
two-bucket: incorrect test case in canonical data?

### ISSUE THREAD

**Issue by cmccandless** [exercism/problem-specifications#911]
According to the [README] for the exercise, valid moves include:
>pouring from one bucket to another
>emptying one bucket and doing nothing to the other
>filling one bucket and doing nothing to the other

The only other restriction stated is
>That means, when starting with the larger bucket full, you are NOT allowed at any point to have the smaller bucket full and the larger bucket empty (aka, the opposite starting point)

In other words, if one bucket is full, and the other empty, the full bucket must be the starting bucket.

The last test case description says ["Measure using bucket one of size 2 and bucket two of size 3 - start with bucket one and end with bucket two"](https://github.com/exercism/problem-specifications/blob/df076b2bd75e06e42a2ad0cb7eb0d5a8bdccd9f6/exercises/two-bucket/canonical-data.json#L70-L84) 

With the above rules, what disqualifies the following from being a valid solution for the above test case?
(2 moves): `(fill first bucket, as directed) [2, 0] -> (fill second bucket) [2, 3]`

**Comment by petertseng** [comment]
I see nothing that disqualifies the proposed two-move solution.

I didn't see any rule that requires that you can only pour water into the start bucket, which is a possible reason one would expect a four-move solution.

**Comment by Insti** [comment]
The goal is 3 litres.

> what disqualifies the following from being a valid solution
> (2 moves): (fill first bucket, as directed) [2, 0] -> (fill second bucket) [2, 3]

Don't you have 5 litres at this point?
By emptying the first bucket do you violate the "opposite starting point" constraint.

**Comment by cmccandless** [comment]
There is no requirement for the other bucket to be empty. In fact, if you look at the other test cases, you'll find it is almost never so. The 3L goal only applies to one bucket.
