### ISSUE TITLE
contributing.md: broken link

### ISSUE THREAD

**Issue by rpottsoh** [exercism/problem-specifications#914]
This link, located on line 350 is broken: `[anatomy of an exercise](https://github.com/exercism/docs/tree/master/maintaining-a-track/anatomy-of-an-exercise.md)`.  I'd like to open a PR to fix this, but I am not sure where the doc is that needs to be pointed to.  I've looked around in this repo and in exercism/docs without success.

If some one can point me to the missing doc I'll take care of correcting the broken link within a new PR.

**Comment by Insti** [comment]
https://github.com/exercism/docs/tree/master/language-tracks/exercises/anatomy (incomplete though.)

There is some more information here:

https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md
