### ISSUE TITLE
isogram: Update tests to match examples in description.

### ISSUE THREAD

**Issue by Insti** [exercism/problem-specifications#919]
In #912 the [isogram description](https://github.com/exercism/problem-specifications/blob/master/exercises/isogram/description.md) was updated to include the example of a valid isogram with multiple hyphens.

It would be good to add a matching test to the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/isogram/canonical-data.json).

Suggestion: Replace ["Hjelmqvist-Gryb-Zock-Pfund-Wax"](https://github.com/exercism/problem-specifications/blob/master/exercises/isogram/canonical-data.json#L53) with "six-year-old" and update the description to more accurately describe what is being tested.

Another question to consider: Are hyphens and mixed case words necessary to test at the same time?

**Comment by rpottsoh** [comment]
ugh.  #920 didn't close this...

**Comment by NobbZ** [comment]
> ugh. #920 didn't close this...

Yeah, AFAIK autoclose does only work if the magic word is part of the initial PR description or part of a commit message, and not if it is in an arbitrary comment…

**Comment by rpottsoh** [comment]
Ah, will keep that in mind.  Thanks @NobbZ
