### ISSUE TITLE
bob: Precedence of the four rules

### ISSUE THREAD

**Issue by petertseng** [exercism/problem-specifications#943]
The https://github.com/exercism/problem-specifications/blob/master/exercises/bob/description.md lists the rules in the order:

* Question -> sure
* Yell -> whoa, chill out
* Silent -> fine, be that way
* Otherwise -> whatever

Is it ever possible that a given input will match two (or more) of these rules? Let's see.

Since the last rule is an "otherwise" rule, it is necessarily exclusive of all others.

The silence rule is exclusive of yelling (assuming that we can only consider a text to be yelling if it has some non-whitespace character) and of questions (since questions necessarily contain the question mark).

But you could have a yelling question, matching the first two rules. For a yelling question, which rule takes precedence? Looking at the description only, I wouldn't know.

The tests have something to say about it though. https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json#L54-L57 says that yelling takes precedence.

What shall we do about the fact that the description does not say which rule takes precedence?

1. Do not define precedence in the description.
2. Define yell > question in description.
3. Define question > yell in description, and change the test in canonical-data.json.

My choice: I do not care.

And, shall we keep the test of the yelling question?

My choice: I do not care.

**Comment by Insti** [comment]
I vote for: Define yell > question in description.

**Comment by Insti** [comment]
I'm also in favor of the simplicity of the description.
So my second preference would be:
Do not define precedence in the description and remove the test for the yelling question.

**Comment by petertseng** [comment]
I looked at the source https://pine.fm/LearnToProgram/chap_06.html to see if it had anything to say, but it did not (since the only options there are shouting BYE, shouting anything other than BYE, and not shouting), so we will have to make this decision ourselves.
