### ISSUE TITLE
Exercise idea: Rational numbers

### ISSUE THREAD

**Issue by Average-user** [exercism/problem-specifications#962]
I've always liked when languages express rationals numbers exactly (like Lisp), and with exactly I mean in fractions. 

So, the idea is simple, the exercise will be to write a bunch of functions/methods that treat fractions, using for example, two-tuples like ```(a,b)```, where ```a``` would be the numerator, and ```b``` the denominator,both being integers numbers . The implementations should deal with divisions by 0 and other problems.

The exact functions to be implemented are yet to be decided. I think a good example of something similar to this, is the [complex-numbers](https://github.com/exercism/problem-specifications/tree/master/exercises/complex-numbers) exercise.

I'll be happy to answer any question if there are.

**Comment by Insti** [comment]
I've changed the subject as the previous subject made no sense to me.

**Comment by cmccandless** [comment]
#1135 closes this and has been merged.
