### ISSUE TITLE
book-store: should we refrain from using floating point?

### ISSUE THREAD

**Issue by petertseng** [exercism/problem-specifications#964]
When I search for "why not use floating point for money" in my preferred search engine, I get many results, such as https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency (by the way, searching for "why use floating point for money" also gives reasons in opposition rather than reasons in support).

Should we take their advice, and instead use integer number of cents?

It's a little tricky because it is sure possible that calculating the discounts may involve floating point math. But not in this case; here the discount values always result in whole numbers of cents. Thus one can conceive of a way to do this without any floating point math.

It also may be a bit jarring to students, since the units will not be the same as those in the description.

I do not maintain any track that has this exercise, so consider this as a curious question of an unknowing outsider. It does not particularly matter to me which choice we take.

There are previous discussions about floating point in space-age (https://github.com/exercism/problem-specifications/pull/880) and triangle (https://github.com/exercism/problem-specifications/issues/798) but my providing these links is not to be construed as an assertion or denial that those past discussions are relevant to this one.

**Comment by petertseng** [comment]
> instead use integer number of cents?

Remember how I was complaining about:

> searching for "why use floating point for money" also gives reasons in opposition rather than reasons in support

Well, I didn't exactly find a reason in support of floating point, but I did find drawbacks of using integers, namely http://floating-point-gui.de/formats/integer/. I won't judge whether every language should choose to use their decimal type versus whether integers or floats are sufficient.

**Comment by petertseng** [comment]
EBWODP:

> Well, I didn't exactly

The word "exactly" should be deleted. I did not even "kind of" find a reason.

**Comment by Insti** [comment]
Surely the use of floating point is up to the tracks?

All the values used in the canonical-data.json should be easily parsable into the relevant dollar/cent values.

I'd have no problem with the json values being in cents, but don't care enough to advocate for a change.

**Comment by NobbZ** [comment]
I took a look at the exercise right now, and since it is about calculating discounts on prices, I do think it is important to encourage the use of proper monetary semantics and accuracy.

Therefore I do suggest to use objects to represent the prices (eg. `{ "dollar": 1, "cent": 99 }`).

Also I'd suggest a comment in the testdata, that asks the testsuites implementor to encourage a proper datatype.

Either provide type annotations that use a proper type from the stdlib or by providing an additional file with an implementation or by injecting it from the testsuite.

I am strictly against asking the student to implement such a datatype in this exercise. (But we could add another exercise that is solely around implementing one)

**Comment by petertseng** [comment]
My recommendations, then:

If we decide that the canonical data should recommend to implementors that floating points be avoided, so too should the canonical data also avoid using floating points.

It is true that we may simply keep the floating points and trust language tracks to transform them, but the idea is to encourage doing what we recommend. Just as Gary Bernhardt [suggested](https://www.destroyallsoftware.com/talks/the-birth-and-death-of-javascript) that the behaviour we see a tool being used for is the behaviour that the tool encourages, I also consider what behaviours the JSON will encourage.

I personally take more of an interest in the grouping logic of this exercise rather than the money-related matters (possible opening for an exercise that does in fact deal with money), so I would be content to recommend+encourage the use of integers rather than some decimal type.

Since I maintain no track that implements this exercise, it is not my priority to take action on my own recommendations, so I leave it for y'all's consideration.

**Comment by ErikSchierboom** [comment]
> If we decide that the canonical data should recommend to implementors that floating points be avoided, so too should the canonical data also avoid using floating points.

One way we could work around using floats is to describe the expected price in number of cents. Would that be an option?

**Comment by petertseng** [comment]
> describe the expected price in number of cents. Would that be an option?

yes

**Comment by rpottsoh** [comment]
> describe the expected price in number of cents. 

This is the best option I have read so far.

Updating the canonical data for cents is not a problem, but what about the README?  It might appear strange / confusing to people to read that something is `¢800` vs `$8.00`.  Include in description.md a statement that monetary amounts will be processed in terms of cents?

**Comment by NobbZ** [comment]
Well, the cent-based amount could be in the JSON only, altogether with a comment explaining that implementors of the exercise should use proper fixed-point or currency datatypes of the corresponding language and not float.
