### ISSUE TITLE
meetup: Test descriptions are unhelpful.

### ISSUE THREAD

**Issue by Insti** [exercism/problem-specifications#974]
The [canonical-data for meetup](https://github.com/exercism/problem-specifications/blob/master/exercises/meetup/canonical-data.json) has a lot of test cases, each of which has a description that just echoes the test input values.

None of the descriptions say why these values are interesting or useful to test.

**Task:**

Update the descriptions so each description describes which particular property of the solution it is trying to test for.

References: [Meetup description](https://github.com/exercism/problem-specifications/blob/master/exercises/meetup/description.md)

**Comment by ErikSchierboom** [comment]
The [test case descriptions](https://github.com/exercism/problem-specifications/blob/main/exercises/meetup/canonical-data.json) have since all been updated, so this issue can be closed.

**Comment by petertseng** [comment]
There have not been any changes to the test case descriptions since the creation of meetup/canonical-data.json.

My comment doesn't recommend for or against closing this issue; it is only saying that if this issue is to be closed, it has to be closed based on an assertion like "we decided that it is okay to close it without updating the descriptions".

**Comment by ErikSchierboom** [comment]
Hmmm, I misread then, my mistake. 

> None of the descriptions say why these values are interesting or useful to test.

Well, most of the values _are_ not interesting :) With meetup, we took a fairly exhaustive approach to the test cases, which makes most of them not very interesting, but mostly useful for checking the code for exhaustiveness. I'd argue that the current descriptions are fine, but I'm open to people disagreeing. 

The fact though that nobody has replied to this in 5 years may give some indication on how others view this, but maybe not.

**Comment by petertseng** [comment]
But there's a pattern to the values. Look at the expected dates for teenth Mondays:

* 2013-05-13
* 2013-08-19
* 2013-09-16

Days in the teenth week can fall between 13th to the 19th inclusive, so the cases have been carefully chosen to test both endpoints and an arbitrary date in the middle. This pattern (testing 13th, 19th, and a date in the middle) is consistently followed for all seven days of the teenth week, so this was a deliberate choice. And failing to note this deliberate choice is losing information.

The choices are not as thorough for the other weeks, but that can be rectified by adding cases.

* first: 1-7
* second: 8-14
* third: 15-21
* fourth: 22-28
* last: several interesting cases here, depending on whether the month has five of that day or four, and also for a February in a leap year.

This does raise an interesting choice of how one would write the description though. Taking an example for teenth Monday of May 2013 which lands on 2013-05-13, would it be written as:

* description: "teenth Monday of a month where it lands on the 13th"
* description: "teenth Monday of a month where it lands on the first possible day"
* description: "teenth Monday of a month where it lands on the 13th, the first possible day"
* other suggestion

**Comment by ErikSchierboom** [comment]
"teenth Monday of a month where it lands on the 13th, the first possible day" contains the most information, so should possibly be preferred over the other two.

Maybe change slightly to:

description: "teenth Monday of a month where it lands on the 13th, the first possible teenth day"
