### ISSUE TITLE
rna-transcription: specify error cases using error-object

### ISSUE THREAD

**Issue by NobbZ** [exercism/problem-specifications#977]
Currently there are 3 error cases in [`rna-transcription`s `canonical-data.json`](https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/canonical-data.json).

Those are specified using an expected value of `null` instead of the “new” and more flexible way of using an `error` object.

Should we change this? And is this error-object described/specified somewhere in a human readable way?

**Comment by Insti** [comment]
Yes we should change this.

The error object is specified in the README in the [Test Data Format](https://github.com/exercism/problem-specifications/blob/master/README.md#test-data-format-canonical-datajson) section. 

> if an error is expected (because the input is invalid, or any other reason), the value at "expected" should be an object containing exactly one property, "error", whose value is a string.

**Comment by ErikSchierboom** [comment]
> Should we change this?

Absolutely!
